# 01 Data preparation

Processing xlsx files from data folder into suitable inputs and generate other input files

In [1]:
import pandas as pd
import numpy as np
import os
import pickle

In [2]:
cell_line ='BC3C_dec'
data_dir = f"/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_{cell_line}/"
info_dir = data_dir
out_dir = f"/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_bmra/blca_publication_OUTPUT_bmra_{cell_line}/00_outputs_2020_{cell_line}/"

#os.makedirs(info_dir, exist_ok = True)
os.makedirs(out_dir, exist_ok = True)

## Modules

Load data about modules and drugs.

In [3]:
os.path.join(info_dir, "ALL_DATA_2020_post.xlsx")

'/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_BC3C_dec/ALL_DATA_2020_post.xlsx'

In [4]:
### DATA
### remove whitespaces in names (modules), remove duplicates

modules_df = pd.read_excel(
    os.path.join(info_dir, "ALL_DATA_2020_post.xlsx"), sheet_name = "modules", index_col = 0)
# display(modules_df)

selected_modules = modules_df.index.tolist()
print(len(selected_modules), ' - Size after reading')

# remove duplicates
selected_modules = modules_df.index.unique().tolist()
print(len(selected_modules), ' - Size after remove duplicates')

# remove whitespaces in modules' names 
selected_modules = [d.strip() for d in selected_modules]

print('Selected modules list: ', len(selected_modules), selected_modules)

10  - Size after reading
10  - Size after remove duplicates
Selected modules list:  10 ['CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'SMAD3']

In [5]:
### DATA
### remove whitespaces in names (modules, drugs), remove duplicates
### check the dimensions of the indicator IC50 1 uM = 1000 nM
### copy-paste as values, numbers, no formulas

IC50_df = pd.read_excel(
    os.path.join(info_dir, "ALL_DATA_2020_post.xlsx"), sheet_name = "IC50s")
IC50_df.drop(columns=['Unnamed: 3'],inplace=True)

print(len(IC50_df.index), ' - Size after reading')
# display(IC50_df)

# rename
IC50_df = IC50_df.rename(columns = {"IC50, uM": "IC50"})

# manually correcting value IC50, Example  for IOX2 -> 30 nM  
#IC50_df.loc[IC50_df.index == 'IOX2', IC50_df.columns == 'IC50'] = 30/1000

# remove non-selected modules, modules' names with whitespaces or empty
#IC50_df = IC50_df[IC50_df.Module.isin(selected_modules)]

#print(len(IC50_df.index), ' - Size after remove modules')
# display(IC50_df)

# remove duplicates 
# Considering certain columns is optional. 
# Indexes, including time indexes are ignored.
IC50_df = IC50_df.drop_duplicates()

print(len(IC50_df.index), ' - Size after remove duplicates')
display(IC50_df)

33  - Size after reading
33  - Size after remove duplicates

                   Drug    Module       IC50
0           JNJ-7706621    CDK1_2    0.02700
1            PHA-793887    CDK1_2    0.18000
2           roscovitine    CDK1_2    2.00000
3             alvocidib    CDK4_6    0.12000
4           palbociclib    CDK4_6    0.04500
5              afatinib      EGFR    0.03000
6             erlotinib      EGFR    0.00600
7             gefitinib      EGFR    0.17100
8             lapatinib      EGFR    0.03240
9            vandetanib      EGFR    1.50000
10           dienestrol  Estrogen  200.00000
11  estradiol-cypionate  Estrogen  200.00000
12           raloxifene  Estrogen    0.01710
13            masitinib      FGFR    2.50000
14            sorafenib      FGFR    1.74000
15               PI-103      PI3K    0.09000
16              AMG-232       p53    0.00180
17              HLI-373       p53    3.00000
18             nutlin-3       p53    0.54000
19                 RITA       p53    9.75000
20            SAR405838       p53    0.02640
21            AS-605240      PI3K    0.15950
22            LY-294002      PI3K    1.36000
23            taselisib      PI3K    0.00262
24         daunorubicin     TOP2A    0.02000
25           epirubicin     TOP2A    0.17000
26           idarubicin     TOP2A    0.00990
27         mitoxantrone     TOP2A    5.30000
28             AZD-8055      PI3K    0.27430
29           serdemetan       p53   62.15000
30            ponatinib      FGFR    0.00660
31            dasatinib       Src    0.00240
32               Agent2     SMAD3   10.00000

In [6]:
modules = IC50_df.Module.unique().tolist()

print('IC50_df  modules list: ', len(modules), modules)
print()
print('Selected modules list: ', len(selected_modules), selected_modules)

### CHECK
print()
print('CHECK: ', len(selected_modules),'=?', len(modules))

n_modules = len(modules)

IC50_df  modules list:  10 ['CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'SMAD3']

Selected modules list:  10 ['CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'SMAD3']

CHECK:  10 =? 10

In [7]:
drugs = IC50_df.Drug.tolist()
print(len(drugs), ' - Size after reading')

# remove duplicates
drugs = IC50_df.Drug.unique().tolist()
print(len(drugs), ' - Size after remove duplicates')

# remove whitespaces in drugs' names (necessary for some)
drugs = [d.strip() for d in drugs]

# remove duplicates after remove whitespaces
drugs = list(set(drugs))
print(len(drugs), ' - Size after remove duplicates without whitespaces')

print('Drugs list: ', len(drugs), drugs)

n_drugs = len(drugs)

33  - Size after reading
33  - Size after remove duplicates
33  - Size after remove duplicates without whitespaces
Drugs list:  33 ['dasatinib', 'RITA', 'daunorubicin', 'afatinib', 'serdemetan', 'vandetanib', 'AS-605240', 'SAR405838', 'taselisib', 'estradiol-cypionate', 'epirubicin', 'palbociclib', 'HLI-373', 'alvocidib', 'dienestrol', 'sorafenib', 'roscovitine', 'gefitinib', 'nutlin-3', 'masitinib', 'PI-103', 'ponatinib', 'idarubicin', 'erlotinib', 'JNJ-7706621', 'mitoxantrone', 'lapatinib', 'LY-294002', 'Agent2', 'raloxifene', 'AMG-232', 'AZD-8055', 'PHA-793887']

## L1000 meta data

Get sig_id for selected drugs.

In [8]:
sig_info_df = pd.read_excel(os.path.join(data_dir, f"sig_info_2020_BC3C.xlsx"), index_col = 0)

display(sig_info_df)

,cell,plate,time,level_3_samples,samples_number,pert_type,pert_drug,targets,targets_number,dose,dose_float
level_5_sig_id,,,,,,,,,,,
ASG002_BC3C_24H:A03,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A03,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A04,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A04,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A05,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A05,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A06,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A06,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:J13,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:J13,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
...,...,...,...,...,...,...,...,...,...,...,...
MOAR012_BC3C_24H:P20,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P20,1,trt_cp,BAY-61-3606,NaN,0,3.33 uM,3.33
MOAR012_BC3C_24H:P21,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P21,1,trt_cp,BAY-61-3606,NaN,0,1.11 uM,1.11
MOAR012_BC3C_24H:P22,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P22,1,trt_cp,ethaverine,NaN,0,10 uM,10.00
MOAR012_BC3C_24H:P23,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P23,1,trt_cp,ethaverine,NaN,0,3.33 uM,3.33
MOAR012_BC3C_24H:P24,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P24,1,trt_cp,ethaverine,NaN,0,1.11 uM,1.11

In [9]:
# now filtering so only the required drugs are present
sig_info_df = sig_info_df.loc[sig_info_df.pert_drug.isin(drugs)]

# here's what we have now
display(sig_info_df)

,cell,plate,time,level_3_samples,samples_number,pert_type,pert_drug,targets,targets_number,dose,dose_float
level_5_sig_id,,,,,,,,,,,
ASG002_BC3C_24H:A10,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A10,1,trt_cp,taselisib,PIK3CA,1,10 uM,10.00
ASG002_BC3C_24H:A11,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A11,1,trt_cp,taselisib,PIK3CA,1,1.11 uM,1.11
ASG002_BC3C_24H:A19,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A19,1,trt_cp,AS-605240,PIK3CG,1,10 uM,10.00
ASG002_BC3C_24H:A20,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A20,1,trt_cp,AS-605240,PIK3CG,1,1.11 uM,1.11
ASG002_BC3C_24H:A21,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A21,1,trt_cp,AS-605240,PIK3CG,1,0.12 uM,0.12
...,...,...,...,...,...,...,...,...,...,...,...
MOAR010_BC3C_24H:K08,BC3C,MOAR010,24 h,MOAR010_BC3C_24H_X1_B36:K08,1,trt_cp,SAR405838,MDM2,1,3.33 uM,3.33
MOAR010_BC3C_24H:K09,BC3C,MOAR010,24 h,MOAR010_BC3C_24H_X1_B36:K09,1,trt_cp,SAR405838,MDM2,1,1.11 uM,1.11
MOAR011_BC3C_24H:F07,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F07,1,trt_cp,serdemetan,MDM2,1,10 uM,10.00
MOAR011_BC3C_24H:F08,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F08,1,trt_cp,serdemetan,MDM2,1,3.33 uM,3.33
MOAR011_BC3C_24H:F09,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F09,1,trt_cp,serdemetan,MDM2,1,1.11 uM,1.11

In [10]:
#previous removed
#rows_remove = ['ASG002_BC3C_24H:F04', 'ASG002_BC3C_24H:F05','ASG002_BC3C_24H:L02',
#               'ASG002_BC3C_24H:O24','ASG002_B                         C3C_24H:L07','ASG002_BC3C_24H:L09',
#               'MOAR010_BC3C_24H:D02', 'ASG002_BC3C_24H:F01','MOAR010_BC3C_24H:D01',
#               'ASG002_BC3C_24H:N19','ASG002_BC3C_24H:N21','ASG002_BC3C_24H:N24',
#               'ASG002_BC3C_24H:I19','ASG002_BC3C_24H:I21','ASG002_BC3C_24H:L17',
#               'ASG002_BC3C_24H:M23','MOAR008_BC3C_24H:L03','MOAR010_BC3C_24H:L20','MOAR011_BC3C_24H:J10',
#               'MOAR008_BC3C_24H:L08','MOAR009_BC3C_24H:C10','MOAR010_BC3C_24H:A13','MOAR010_BC3C_24H:A14','MOAR011_BC3C_24H:F09',
#               'ASG002_BC3C_24H:G01','ASG002_BC3C_24H:P20']

In [11]:
rows_remove = ['ASG002_BC3C_24H:G01',
 'ASG002_BC3C_24H:F15',
 'ASG002_BC3C_24H:N19',
 'ASG002_BC3C_24H:N22',
 'ASG002_BC3C_24H:F15',
 #'ASG002_BC3C_24H:I08',
 'ASG002_BC3C_24H:I19',
 'ASG002_BC3C_24H:B12',
 'MOAR008_BC3C_24H:L07',
 'MOAR008_BC3C_24H:L09',
 'ASG002_BC3C_24H:F04',
 'ASG002_BC3C_24H:P17',
 'ASG002_BC3C_24H:O24',
 #'MOAR010_BC3C_24H:D02',
 'ASG002_BC3C_24H:L18',
 #'MOAR008_BC3C_24H:L03',
 #'MOAR010_BC3C_24H:L21'
 ]

Manually remove  few inhibition from data set, since it does differ from the other data points.

inhib_to_filter = "PF-03758309"
dose_to_filter = 10

id_to_filter = sig_info_df[
    np.logical_and(
        sig_info_df.pert_drug == inhib_to_filter,
        sig_info_df.dose_float == dose_to_filter,
    )
].index.values

print(id_to_filter)

sig_info_df = sig_info_df[~sig_info_df.index.isin(id_to_filter)]
display(sig_info_df)

inhib_to_filter = "roscovitine"
dose_to_filter = 3.33

id_to_filter = sig_info_df[
    np.logical_and(
        sig_info_df.pert_drug == inhib_to_filter,
        sig_info_df.dose_float == dose_to_filter,
    )
].index.values

print(id_to_filter)

sig_info_df = sig_info_df[~sig_info_df.index.isin(id_to_filter)]
display(sig_info_df)

In [12]:
sig_info_df.drop(rows_remove,inplace=True)

In [13]:
exp_ids = sig_info_df.index.unique().tolist()
print('Experiments ids list: ', len(exp_ids))

n_experiments = len(exp_ids)

Experiments ids list:  86

In [14]:
n_experiments = len(exp_ids)
print('Experiments ids list: ', len(exp_ids))

Experiments ids list:  86

Confirm data by checking the drugs of interest against the filtered L1000 meta data.

In [15]:
print(f"Number of drugs of interest:\t{len(drugs)}")
#print(f'Number of drugs in L1000 data:\t{len(sig_info_df.value_counts("drugs"))}')

#sig_info_df.value_counts("drugs")

Number of drugs of interest:	33

## L1000 data

In [16]:
Data_norm_df = pd.read_excel(os.path.join(data_dir, f"Data_norm_2020_BC3C.xlsx"), index_col = 0)
display(Data_norm_df)

,AARS,ABCB6,ABCC5,ABCF1,ABCF3,ABHD4,ABHD6,ABL1,ACAA1,ACAT2,...,ZMIZ1,ZMYM2,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZW10
ASG002_BC3C_24H:A03,-0.191254,-0.055246,0.039596,-0.256266,-0.040419,-0.590523,-0.159396,-0.074319,0.457981,0.409608,...,0.543203,0.494266,-0.011923,-0.225931,0.285054,-0.775246,0.166031,-0.024873,0.238723,0.284204
ASG002_BC3C_24H:A04,-0.265754,-0.317496,0.118696,-0.136665,-0.301569,-0.403023,0.124804,-0.036470,0.311931,0.660457,...,-0.565096,-0.088634,0.122977,-0.047931,0.141804,0.129054,-0.028819,-0.028773,-0.253627,-0.752646
ASG002_BC3C_24H:A05,-0.181954,-0.081597,-0.210304,1.559535,-0.019019,-0.457423,0.071404,0.074080,-0.356119,0.498808,...,0.226104,-0.228034,-0.121023,-0.075331,-0.133146,0.355054,0.022831,-0.084073,0.283123,-0.894896
ASG002_BC3C_24H:A06,0.033446,0.042404,-0.150154,-0.093165,0.053180,-0.053823,0.087704,0.167681,-0.601569,0.383308,...,-0.608596,-0.228835,0.072777,0.082970,-0.570996,2.847754,-0.211670,-0.067273,0.081723,0.338704
ASG002_BC3C_24H:J13,0.204446,0.180704,0.089096,-0.054666,0.053381,0.044877,-0.277396,-0.157419,0.535681,-3.933493,...,-0.318397,0.122265,-0.134323,-0.088931,-0.067996,-0.515847,-0.005069,0.067527,0.002223,0.204904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MOAR012_BC3C_24H:P20,0.647151,0.211700,-0.979200,0.597350,-0.375751,0.388300,0.394524,0.120151,-0.166775,-1.129125,...,-1.598475,-0.552750,0.515151,0.120800,0.082675,0.529700,0.383225,-0.207225,2.268450,-1.248500
MOAR012_BC3C_24H:P21,0.171800,0.046300,-0.145550,-0.295150,0.030849,0.420951,0.222075,0.179800,0.274724,-0.423975,...,-1.650575,0.203600,-0.003250,-0.064800,-0.037675,0.076499,0.201825,0.416875,0.287450,-0.971700
MOAR012_BC3C_24H:P22,0.648700,0.058749,-0.031700,0.408249,-0.753950,0.332200,-0.357525,-0.107650,-0.213575,0.074225,...,0.127625,0.031600,0.103250,-0.249600,0.046375,1.486200,0.440325,0.090075,-0.031650,-0.944300
MOAR012_BC3C_24H:P23,0.090499,-0.469300,-0.611800,0.873550,-0.788450,-0.097199,-0.366575,-0.490600,-0.624675,-0.009275,...,0.054676,-0.596050,0.084600,0.444700,0.431375,-0.921501,0.044926,0.716076,-0.000900,-1.106700
MOAR012_BC3C_24H:P24,0.204801,-1.388700,-0.283400,0.744750,-1.431150,-0.518100,-0.002174,-0.096200,1.198824,0.138525,...,-0.123474,-0.486500,0.049901,-0.598100,-0.259925,0.088650,-0.242075,0.195575,-0.038300,-1.149900

In [17]:
Data_norm_df = Data_norm_df[Data_norm_df.index.isin(exp_ids)]

# arrange experiments in same order as in list
Data_norm_df["sort_col"] = Data_norm_df.index.map({val: i for i, val in enumerate(exp_ids)})
Data_norm_df = Data_norm_df.sort_values("sort_col")
Data_norm_df = Data_norm_df.drop("sort_col", axis = 1)

# transpose
Data_norm_df = Data_norm_df.T

display(Data_norm_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:A15,MOAR010_BC3C_24H:J22,MOAR010_BC3C_24H:J23,MOAR010_BC3C_24H:J24,MOAR010_BC3C_24H:K07,MOAR010_BC3C_24H:K08,MOAR010_BC3C_24H:K09,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09
AARS,-0.496854,0.288446,0.189747,-0.016454,0.080746,0.282346,0.326246,0.303046,0.387546,0.434746,...,0.224383,-0.465317,0.006583,0.227732,1.393332,0.106531,-0.217618,0.584300,0.114500,-0.268751
ABCB6,-0.658596,-0.142196,-0.075397,-0.383796,-0.199996,-0.074197,0.108804,-0.399196,-0.227496,-0.041146,...,0.374653,-0.658898,-0.736548,0.386902,-0.729623,0.225201,0.202852,0.006950,-0.037150,-0.014150
ABCC5,-0.080204,0.231996,-0.329354,-0.225204,0.278446,0.034696,0.396596,-0.255704,-0.254154,-0.002004,...,0.083343,-0.365557,0.184543,0.096643,-0.388082,0.010793,0.011493,-0.238750,0.409550,0.221350
ABCF1,0.202535,0.602335,0.403335,0.313134,-0.083265,-0.056365,-0.387216,0.097235,0.540634,-0.262666,...,-1.130589,-0.940039,0.417610,-0.167539,0.231361,-0.288040,-0.458439,0.142675,0.077875,0.695325
ABCF3,-0.520919,-0.192819,0.001032,-0.096419,0.210881,-0.731118,0.095381,0.313481,-0.078018,-0.257669,...,0.404131,-0.375018,0.305533,-0.088618,0.119233,0.008182,0.201432,-0.468050,-0.140650,-0.353450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF395,1.796254,1.773154,0.668354,0.825354,0.350654,0.205954,-0.998346,0.235354,0.230653,0.440854,...,-1.278881,-1.306905,0.159970,-1.107780,0.037869,0.367270,-0.285181,0.257250,-1.828550,-1.550550
ZNF451,-0.244519,0.116732,0.058081,-0.178169,-0.080619,-0.139119,0.064681,-0.083019,-0.272119,-0.164119,...,0.029882,-0.269068,0.067832,0.015482,-0.113718,0.029882,0.085807,0.080650,0.119950,0.044250
ZNF586,0.097627,0.061027,-0.337573,0.098427,-0.338173,0.017627,-0.197423,-0.078473,-0.300473,-0.147773,...,-0.090739,0.332686,-0.455289,-0.368264,0.090186,-0.182964,0.056085,-0.561900,0.202100,0.043000
ZNF589,0.608573,0.106123,-0.014126,-0.003677,-0.123477,-0.243377,0.044623,-0.021477,0.201823,-0.413227,...,-0.113816,0.402309,0.062659,-0.056591,-0.123891,-0.081541,-0.200241,-0.557600,-0.364600,-0.531500
ZW10,-0.757496,-0.723196,-1.121396,-1.139496,0.077104,-1.088546,0.193104,0.163504,0.372704,-0.677496,...,0.416757,0.017232,-0.588367,-0.121318,-0.659768,0.567533,0.352432,0.113050,-0.269050,0.245600

### Concatenating TGFbRin and SMAD3in LFC2

In [18]:
files_path ='/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_bc3c_oct'

In [19]:
counts = pd.read_csv(
    '/home/jing/Phd_project/project_UCD_blca/blca_DATA/blca_DATA_bc3c_oct/gene_count.xls',
    sep='\t',   
    header=0,index_col=0
)
display(counts)

,D01,D02,D03,T01,T02,T03,S01,S02,S03,gene_name,gene_chr,gene_start,gene_end,gene_strand,gene_length,gene_biotype,gene_description,tf_family
gene_id,,,,,,,,,,,,,,,,,,
ENSG00000156508,236599,217166,230137,246465,277179,265535,291410,287477,279305,EEF1A1,6,73515750,73523797,-,5948,protein_coding,eukaryotic translation elongation factor 1 alp...,-
ENSG00000186081,173372,151121,162044,168813,186988,177195,144747,149534,158903,KRT5,12,52514575,52520687,-,4292,protein_coding,keratin 5 [Source:HGNC Symbol;Acc:HGNC:6442],-
ENSG00000080824,147634,114075,138470,120147,137207,134926,93481,97859,87311,HSP90AA1,14,102080738,102139699,-,5248,protein_coding,heat shock protein 90 alpha family class A mem...,-
ENSG00000187134,105703,95969,88389,103744,120824,114376,95104,108179,106387,AKR1C1,10,4963253,4983283,+,8765,protein_coding,aldo-keto reductase family 1 member C1 [Source...,-
ENSG00000196139,93872,97803,90777,109018,125059,116421,101868,96017,98182,AKR1C3,10,5035354,5107686,+,4532,protein_coding,aldo-keto reductase family 1 member C3 [Source...,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000275063,0,0,0,0,0,0,0,0,0,AC233755.1,KI270726.1,41444,41876,+,351,protein_coding,immunoglobulin heavy variable 4-38-2-like [Sou...,-
ENSG00000275405,0,0,0,0,0,0,0,0,0,RF00003,KI270713.1,21861,22024,-,164,snRNA,NaN,-
ENSG00000275987,0,0,0,0,0,0,0,0,0,RF00003,KI270713.1,30437,30580,-,144,snRNA,NaN,-
ENSG00000277475,0,0,0,0,0,0,0,0,0,AC213203.2,KI270713.1,31698,32528,-,831,protein_coding,NaN,-
ENSG00000268674,0,0,0,0,0,0,0,0,0,AC213203.1,KI270713.1,35407,35916,+,510,protein_coding,Protein FAM231C [Source:UniProtKB/Swiss-Prot;...,-

In [20]:
smad_df  =pd.read_csv(os.path.join(files_path,'augmented_Group_S_vs_D_DEGs.csv'),index_col=0)
display(smad_df)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
ENSG00000156508,0.267818,0.250431,0.258339,0.181589,0.250753,0.219754,0.259317,0.200100,0.236601,0.227299,0.330536,0.244935,0.227655,0.239768,0.164381,0.246356,0.214813,0.262664,0.294040,0.320645
ENSG00000186081,-0.270659,-0.214579,-0.177583,-0.122605,-0.238233,-0.140340,-0.112750,-0.102218,-0.114194,-0.177293,-0.259021,-0.224725,-0.077319,-0.205527,-0.099922,-0.103619,-0.103381,-0.179374,-0.202944,-0.251690
ENSG00000080824,-0.648882,-0.609840,-0.621077,-0.519491,-0.620831,-0.575570,-0.539669,-0.512242,-0.535387,-0.558118,-0.690562,-0.594507,-0.524116,-0.536778,-0.495778,-0.536145,-0.520466,-0.597496,-0.589405,-0.680019
ENSG00000075624,-0.553327,-0.447304,-0.530273,-0.409481,-0.429479,-0.424402,-0.449047,-0.321024,-0.462650,-0.421495,-0.581068,-0.452151,-0.449315,-0.367896,-0.355937,-0.351615,-0.408055,-0.472188,-0.447125,-0.475379
ENSG00000096384,-0.631544,-0.577096,-0.566570,-0.477981,-0.583133,-0.510339,-0.492897,-0.451967,-0.488453,-0.526770,-0.657332,-0.566211,-0.466472,-0.519741,-0.444723,-0.471725,-0.471840,-0.551671,-0.561901,-0.627111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000053702,-2.002080,-1.689436,-1.561071,0.541366,-2.684528,-2.770834,-1.487364,-2.053640,-1.062125,-1.418561,-2.635171,-3.347576,-1.455604,-2.976164,-0.683174,-2.254330,0.179689,-3.332501,-2.159110,-5.245321
ENSG00000184860,-4.867906,-3.830393,-3.064666,-2.068944,-3.196792,-2.044355,-2.590525,-1.043911,-3.145863,-3.208080,-4.767025,-3.626019,-2.830786,-3.678875,-1.930937,-1.055293,-1.382268,-3.876558,-3.180868,-3.062467
ENSG00000279259,2.519366,3.534411,2.960847,1.804856,1.837106,1.713883,2.482235,2.595317,2.774206,2.618790,5.358544,1.328676,3.249234,0.935202,1.353173,1.983776,2.747092,3.341848,2.344522,3.813338
ENSG00000227359,-4.315378,-2.366259,-2.934172,-1.755826,-2.419720,-1.921446,-2.700961,-0.303094,-2.901534,-2.372890,-3.551570,-3.395520,-2.468915,-3.105285,-1.447017,-0.934478,-1.227321,-3.039423,-2.944456,-2.242576
ENSG00000070190,-4.260890,-1.256867,-4.025285,-1.728621,-2.398642,-2.841781,-1.552983,-0.900025,-1.525282,-1.583152,-3.714136,-3.388690,-1.166637,-0.627617,-0.772196,-0.631645,-1.929629,-2.207229,-1.786865,-3.991384

In [21]:
smad_df['symbol']= counts.loc[smad_df.index,'gene_name']
display(smad_df)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V12,V13,V14,V15,V16,V17,V18,V19,V20,symbol
ENSG00000156508,0.267818,0.250431,0.258339,0.181589,0.250753,0.219754,0.259317,0.200100,0.236601,0.227299,...,0.244935,0.227655,0.239768,0.164381,0.246356,0.214813,0.262664,0.294040,0.320645,EEF1A1
ENSG00000186081,-0.270659,-0.214579,-0.177583,-0.122605,-0.238233,-0.140340,-0.112750,-0.102218,-0.114194,-0.177293,...,-0.224725,-0.077319,-0.205527,-0.099922,-0.103619,-0.103381,-0.179374,-0.202944,-0.251690,KRT5
ENSG00000080824,-0.648882,-0.609840,-0.621077,-0.519491,-0.620831,-0.575570,-0.539669,-0.512242,-0.535387,-0.558118,...,-0.594507,-0.524116,-0.536778,-0.495778,-0.536145,-0.520466,-0.597496,-0.589405,-0.680019,HSP90AA1
ENSG00000075624,-0.553327,-0.447304,-0.530273,-0.409481,-0.429479,-0.424402,-0.449047,-0.321024,-0.462650,-0.421495,...,-0.452151,-0.449315,-0.367896,-0.355937,-0.351615,-0.408055,-0.472188,-0.447125,-0.475379,ACTB
ENSG00000096384,-0.631544,-0.577096,-0.566570,-0.477981,-0.583133,-0.510339,-0.492897,-0.451967,-0.488453,-0.526770,...,-0.566211,-0.466472,-0.519741,-0.444723,-0.471725,-0.471840,-0.551671,-0.561901,-0.627111,HSP90AB1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000053702,-2.002080,-1.689436,-1.561071,0.541366,-2.684528,-2.770834,-1.487364,-2.053640,-1.062125,-1.418561,...,-3.347576,-1.455604,-2.976164,-0.683174,-2.254330,0.179689,-3.332501,-2.159110,-5.245321,NRIP2
ENSG00000184860,-4.867906,-3.830393,-3.064666,-2.068944,-3.196792,-2.044355,-2.590525,-1.043911,-3.145863,-3.208080,...,-3.626019,-2.830786,-3.678875,-1.930937,-1.055293,-1.382268,-3.876558,-3.180868,-3.062467,SDR42E1
ENSG00000279259,2.519366,3.534411,2.960847,1.804856,1.837106,1.713883,2.482235,2.595317,2.774206,2.618790,...,1.328676,3.249234,0.935202,1.353173,1.983776,2.747092,3.341848,2.344522,3.813338,AC087741.3
ENSG00000227359,-4.315378,-2.366259,-2.934172,-1.755826,-2.419720,-1.921446,-2.700961,-0.303094,-2.901534,-2.372890,...,-3.395520,-2.468915,-3.105285,-1.447017,-0.934478,-1.227321,-3.039423,-2.944456,-2.242576,AC017074.1
ENSG00000070190,-4.260890,-1.256867,-4.025285,-1.728621,-2.398642,-2.841781,-1.552983,-0.900025,-1.525282,-1.583152,...,-3.388690,-1.166637,-0.627617,-0.772196,-0.631645,-1.929629,-2.207229,-1.786865,-3.991384,DAPP1

In [22]:
smad_lfc = smad_df.set_index('symbol')
smad_lfc = smad_lfc.loc[smad_lfc.index.intersection(Data_norm_df.index)]
display(smad_lfc)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
GAPDH,-0.418152,-0.378634,-0.364679,-0.263892,-0.347446,-0.263073,-0.244382,-0.208759,-0.301027,-0.311857,-0.466722,-0.302955,-0.265909,-0.271792,-0.233447,-0.191365,-0.237988,-0.347047,-0.293119,-0.359380
HSPD1,-0.690897,-0.665134,-0.652550,-0.567147,-0.659815,-0.609033,-0.578545,-0.549631,-0.578327,-0.605370,-0.730267,-0.629661,-0.571679,-0.580900,-0.545108,-0.570301,-0.557540,-0.639824,-0.625826,-0.701300
HSPA8,-0.596020,-0.483657,-0.553548,-0.509347,-0.450671,-0.483620,-0.561689,-0.403153,-0.524346,-0.493066,-0.583500,-0.530125,-0.539842,-0.444983,-0.441469,-0.447797,-0.517435,-0.506071,-0.536500,-0.483699
SPP1,0.183543,0.160707,0.167465,0.152414,0.141925,0.156691,0.175856,0.061337,0.119418,0.116680,0.170852,0.137803,0.149321,0.075414,0.111390,0.155068,0.129231,0.120261,0.168496,0.121010
TXNRD1,-0.369827,-0.405291,-0.334293,-0.257711,-0.399601,-0.312548,-0.209274,-0.234407,-0.237951,-0.291079,-0.404563,-0.292291,-0.228591,-0.259964,-0.261069,-0.255030,-0.199669,-0.325166,-0.274368,-0.379084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CDC42,-0.954408,-1.133006,-1.025483,-0.750016,-1.203452,-0.308864,-0.369969,-0.566596,-0.732181,-0.832729,-1.402006,-0.358399,-0.148742,-0.727734,-0.468275,-0.550377,-0.827254,-0.567495,-0.956274,-0.945379
APOE,1.757115,0.958865,1.180892,0.361918,1.470654,1.152320,0.944884,0.782349,0.704361,1.015152,1.705620,1.908782,0.546101,1.553845,0.355148,0.860957,0.546481,1.397371,1.521237,2.344394
SATB1,1.838739,1.658157,1.726674,0.842176,1.095462,0.900912,0.918231,0.684494,1.300680,1.206626,2.673180,0.971805,1.317559,0.475854,0.570397,0.362617,0.930993,1.660736,0.936688,1.743425
SPDEF,-2.192339,-2.477598,-1.448971,-0.849881,-1.784082,-1.055109,-1.117169,-1.309503,-1.334458,-1.823078,-3.150591,-1.644710,-1.430505,-1.641612,-0.846442,-0.860945,-0.920115,-2.251125,-1.632585,-2.591862
IKZF1,2.532258,2.086759,2.489235,0.768546,1.847149,2.700484,1.752076,1.066432,1.064889,1.193269,3.318253,2.230188,2.070691,0.261644,0.718429,1.667896,0.801357,2.555673,1.495987,3.676369

In [23]:
smad_lfc.columns = ['SMAD_' + col for col in smad_lfc.columns]
display(smad_lfc)

,SMAD_V1,SMAD_V2,SMAD_V3,SMAD_V4,SMAD_V5,SMAD_V6,SMAD_V7,SMAD_V8,SMAD_V9,SMAD_V10,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
GAPDH,-0.418152,-0.378634,-0.364679,-0.263892,-0.347446,-0.263073,-0.244382,-0.208759,-0.301027,-0.311857,-0.466722,-0.302955,-0.265909,-0.271792,-0.233447,-0.191365,-0.237988,-0.347047,-0.293119,-0.359380
HSPD1,-0.690897,-0.665134,-0.652550,-0.567147,-0.659815,-0.609033,-0.578545,-0.549631,-0.578327,-0.605370,-0.730267,-0.629661,-0.571679,-0.580900,-0.545108,-0.570301,-0.557540,-0.639824,-0.625826,-0.701300
HSPA8,-0.596020,-0.483657,-0.553548,-0.509347,-0.450671,-0.483620,-0.561689,-0.403153,-0.524346,-0.493066,-0.583500,-0.530125,-0.539842,-0.444983,-0.441469,-0.447797,-0.517435,-0.506071,-0.536500,-0.483699
SPP1,0.183543,0.160707,0.167465,0.152414,0.141925,0.156691,0.175856,0.061337,0.119418,0.116680,0.170852,0.137803,0.149321,0.075414,0.111390,0.155068,0.129231,0.120261,0.168496,0.121010
TXNRD1,-0.369827,-0.405291,-0.334293,-0.257711,-0.399601,-0.312548,-0.209274,-0.234407,-0.237951,-0.291079,-0.404563,-0.292291,-0.228591,-0.259964,-0.261069,-0.255030,-0.199669,-0.325166,-0.274368,-0.379084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CDC42,-0.954408,-1.133006,-1.025483,-0.750016,-1.203452,-0.308864,-0.369969,-0.566596,-0.732181,-0.832729,-1.402006,-0.358399,-0.148742,-0.727734,-0.468275,-0.550377,-0.827254,-0.567495,-0.956274,-0.945379
APOE,1.757115,0.958865,1.180892,0.361918,1.470654,1.152320,0.944884,0.782349,0.704361,1.015152,1.705620,1.908782,0.546101,1.553845,0.355148,0.860957,0.546481,1.397371,1.521237,2.344394
SATB1,1.838739,1.658157,1.726674,0.842176,1.095462,0.900912,0.918231,0.684494,1.300680,1.206626,2.673180,0.971805,1.317559,0.475854,0.570397,0.362617,0.930993,1.660736,0.936688,1.743425
SPDEF,-2.192339,-2.477598,-1.448971,-0.849881,-1.784082,-1.055109,-1.117169,-1.309503,-1.334458,-1.823078,-3.150591,-1.644710,-1.430505,-1.641612,-0.846442,-0.860945,-0.920115,-2.251125,-1.632585,-2.591862
IKZF1,2.532258,2.086759,2.489235,0.768546,1.847149,2.700484,1.752076,1.066432,1.064889,1.193269,3.318253,2.230188,2.070691,0.261644,0.718429,1.667896,0.801357,2.555673,1.495987,3.676369

In [24]:
Data_norm_df[smad_lfc.columns] = 0

In [25]:
common_idx = Data_norm_df.index.intersection(smad_lfc.index)
Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]

/tmp/ipykernel_1458237/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.80006032 -0.38077041  0.6067599   0.14613308  1.04119834  0.64850065
  0.33453216 -0.3657465  -0.14819256 -0.93501364  0.2000188  -0.20626723
 -0.54663673  0.37336362 -0.33119211 -0.45995065 -0.39305895  0.17315114
  1.80734362  1.34024181  0.32793335  0.54169673  0.40003945  1.75711503
  0.2348163   0.40610619 -0.27040384  0.74169684 -0.37149541 -0.22467869
 -0.89065041 -0.14976776 -0.35416148 -0.35196214 -0.30704198 -1.10837272
 -0.68850645 -0.18754113 -0.25961763  0.44222036  0.71956938  0.31011175
 -0.87380603 -0.25761065 -0.35763975  0.29971468  0.49584234  0.71244868
 -0.12837556 -0.82204431 -0.56970768  0.51936367 -0.25994771 -0.31303677
  0.29745721  0.52000627 -0.43751303  0.81274654 -0.30501018 -0.4858665
 -1.15673013  0.61185731 -0.83667314 -1.04763391 -0.8749282  -0.85027437
 -0.80667006 -1.15082152 -0.50176086 -0.28247085 -0.57403414 -0.89586339
 -0.30154763 -1.27864636 -0.64428637 -0.34732146 -0.95440842 -0.58400207
 -0.56164047  0.42910928 -0.7194021   0.45394428 -0.40140866 -0.21552794
  0.21660092 -0.40331345  0.57083078 -0.40620457 -0.87154168 -0.93037528
  0.42318783 -0.55677381  0.51991449 -0.21498862 -0.62889894 -0.7310395
  0.83344799 -0.38436892 -0.46528423  0.22162629  0.56548572 -0.2879666
 -0.15450754  0.23302806 -0.61538875 -0.89331121  0.50987186  0.63446117
  0.70321349 -0.16774786  0.32471221 -0.25056786 -0.38379283 -0.48411309
 -0.51167024 -0.68777637  0.47633003  0.88099401 -0.34805496 -0.41444802
  1.51419685  0.2910269  -0.71760529  0.29995767 -0.28067722  0.49664637
 -0.35536628 -0.33340661 -0.2413385  -0.44966508 -0.34742168  0.65514237
 -0.15515501 -0.39359499 -0.29369876 -0.55719443  0.72754183 -0.32067279
 -0.71387578 -0.34421475 -0.65133345  0.59417723 -0.76814647 -1.91697024
  0.65747656 -0.38098042  0.16168959 -0.7632737   0.90268032 -0.36226437
  0.77827209  0.41275804 -0.64405918 -0.42535875 -0.71045734  0.13518809
 -0.55650268 -0.41295036 -0.56538223 -0.53872827  0.88577918 -0.42567881
 -0.43090046 -0.28807682  0.85838231  0.31897246  0.26637661 -0.21632547
 -1.12315095 -0.82766375 -0.68913927 -0.31375431  0.58341011 -0.73445097
 -0.47166555 -0.15677545 -0.21379924  1.29547683  1.22290772  0.96166435
  0.36886261 -0.81006161 -0.85387961 -1.1871119  -0.2401783   0.62922691
  0.86680208  0.40595944 -0.31492843  0.50744346 -0.67256484  0.38366318
 -0.41815186  0.47397905  0.73707082  0.63721299 -0.55849735  0.47263805
 -0.49081177 -0.45068031  0.18195014  0.74879301  0.41771788 -0.1786751
 -0.5430082   0.64096438 -0.71133666 -0.31225251 -0.46303779 -0.27645976
 -0.22821213 -0.40210804 -0.57045036  0.81007135  0.4948709   0.23253504
 -1.03575012  0.99647286  1.61112651  0.28649853 -0.64963052  0.68241769
 -0.31198809 -0.43641235 -0.59602028 -0.69089668 -0.32231635  0.52552738
  0.19314204 -0.22711298  0.60796881 -0.31743094  0.73493596 -0.53248104
 -0.79964915  0.28195728  0.3211772   0.91022181  2.532258    0.22494879
 -0.53276114 -0.49982166 -0.27995073  1.69769375 -0.24047415 -0.51080838
 -0.28206341  1.07371611 -0.460241   -0.31179495  0.4608802   0.54341875
  0.38977444  0.52080105 -0.29653071 -0.22272926  0.65384671 -0.33339561
 -0.91778996 -0.2111408  -1.29054925 -0.93478164  0.30076322 -0.62784199
 -0.65753317  0.39963969 -0.3074642  -0.43309201  0.70687333  0.7377968
  0.27786023  0.16097203 -0.40075001 -0.53347244  0.36945323 -0.32444274
  0.35309277 -0.2687524   0.54656124 -0.24678238  0.41918071 -0.59181359
 -0.43087589 -0.53568816 -0.17992484 -0.54931721 -0.46386096  0.27749566
 -2.39635246 -0.48659073 -0.23703151 -0.6712405  -0.20484458 -0.53127669
 -0.3412399  -0.37263312  0.22141131 -0.17980212  1.05136226  0.25722156
 -0.52356672 -1.35643877 -1.18134223  0.78260107  0.64500387 -0.22459746
 -0.71755907  0.80418554  0.4710218  -0.13781126 -0.32107344  0.69813824
  0.53999481 -0.39215783  0.72070946 -0.44353451 -0.18303722  0.32914763
  0.17164109 -0.6694949  -0.4821728   0.24732522  0.81183522  0.715652
 -0.40249091 -0.35127292 -0.55109385 -0.86886966 -0.58357378 -0.83971426
 -0.31077941 -0.52336476 -0.71145402  0.52490292  0.51151939 -0.50301667
 -0.44189499 -0.67016456 -0.3444173   0.29396459 -0.40383193 -0.32912858
  1.51386157 -0.1462138  -0.38845946 -0.26313285  0.82857291  0.17357201
 -0.16108357  0.78066782 -0.33709611  0.48994201 -0.18548486  0.84637851
  0.26582518 -0.57073344  0.33038371  0.37837935 -0.91984055  0.35008438
 -0.26504017 -0.23372037  0.43898518 -1.42578916 -0.38684193 -0.35103443
 -0.43278917 -0.42805825 -0.62739196 -0.41629353 -0.61326218 -0.38814303
 -0.4447628  -0.38735456 -0.4364791   0.48048099  0.52426529  0.32939162
 -0.71915598 -0.16204169  0.63236839  0.47613798 -0.17852488  0.73102265
 -0.41131916 -0.38189302  0.82484482 -0.4850706  -0.22774964  0.49137732
  0.21635493 -0.41373926 -0.4698664  -0.48275075 -0.79930386 -0.64744814
  0.62168446 -0.23886301  0.69007616  0.3362596   0.20808997 -0.61516283
 -0.52835607 -0.40158525  0.7859417  -0.27988758  0.44092763  0.41634757
 -0.50631788  0.52363286 -0.65180043  0.80701024 -0.28007376  0.42093398
 -0.4290547   0.21189755 -0.35746049 -0.47281174 -1.27724438  0.7918108
 -0.49253264 -0.25602181 -0.29296379 -0.35162089  0.33067683 -0.81767305
 -0.55895066 -0.86625121 -0.81108965 -0.50082874  1.83873857  0.25287176
  0.36134852 -0.53201562 -0.13418389 -0.48507031  0.37651687 -0.33315134
  0.76836107  0.3565912   0.39250447  0.28448581  0.62697861 -0.58530492
 -0.20462772 -0.56502919 -0.17330545 -0.29629042 -0.3868664  -0.27603618
 -0.64335139  0.96325689  0.41119468  0.74821012 -0.65469231  0.28732422
 -2.19233894  0.43322592  0.18354273  0.25345175 -0.35795164 -0.21755911
  0.69036499  0.63540615  0.13754378  0.59654199 -0.37021297  0.33806098
  0.25788149 -0.30026738 -0.24329598 -1.28309101  0.47158918  0.65314343
  0.22319372 -0.39501256 -0.61818327  1.10413375  1.36548635 -0.29148678
 -0.64033398 -0.52596999  0.32062153  0.37791436 -0.39910946  0.39407903
  0.53273892 -0.41518692 -0.43191329 -0.41824202 -0.453712   -1.07268551
 -1.06240836 -0.44950575  0.3892222   0.36986823 -0.18350884 -0.37753094
 -0.25019958 -0.66991449  0.16381632  0.41061141 -0.38552137  0.37202201
  0.38811619 -0.62891642 -0.18233203 -0.39643173 -0.36755889 -0.8102038
 -0.22679034 -0.2582321  -0.26007243  0.37635416 -0.73705663 -0.70716273
  1.2188438   0.33447069  0.65388253  0.66163962  1.2353296  -0.36147451
 -0.36906384 -0.39628777 -0.26544208 -0.63053441 -0.36982696 -0.23805516
 -0.96685488  0.32365573  0.7686388   0.209128   -0.45899359 -0.44502292
  0.25882973  0.19679428 -0.38225258 -0.3698888  -0.26953199 -0.29739171
 -0.38154621  0.77757521  0.99630614 -0.43658014 -0.39520264  0.20658216
 -0.54837826  0.49732045  0.2508183   0.35138356  0.75865424 -0.24626907
 -0.13741468  0.41862184  0.33407303 -0.69142026 -0.42177633]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]
/tmp/ipykernel_1458237/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.72335254 -0.27060418  0.54086516  0.11913994  1.03810434  0.66274374
  0.34247537 -0.18842255 -0.11829654 -0.93144919  0.27374193 -0.07310747
 -0.4805432   0.29850472 -0.26315125 -0.4191094  -0.36663469  0.22997872
  1.81136342  1.12840133  0.08849673  0.55860181  0.08858616  0.95886487
  0.28350024  0.4630527  -0.31406311  0.73520501 -0.30588061 -0.1883028
 -0.79712742 -0.0091266  -0.32841942 -0.20164506 -0.25301066 -1.06627093
 -0.6226932  -0.23864557 -0.19249846  0.54964817  0.77002825  0.38752694
 -0.83754687 -0.22347755 -0.24211468  0.37394213  0.54881599  0.7684978
 -0.15250735 -0.79735781 -0.53880534  0.41314402 -0.22200375 -0.20304191
  0.33575039  0.33184812 -0.3729469   0.72852517 -0.42611407 -0.51388042
 -1.10625244  0.689385   -0.78159081 -1.0129503  -0.84886501 -0.76996197
 -0.68538552 -1.08345059 -0.27612098 -0.23820651 -0.61488487 -0.87389555
 -0.15632202 -1.2382144  -0.66318027 -0.37831853 -1.13300575 -0.55060774
 -0.53151954  0.84298498 -0.66982258  0.51459945 -0.32441521 -0.30723087
  0.24993185 -0.32108674  0.35813176 -0.37050092 -0.82082588 -0.90869622
  0.35897536 -0.51735972  0.18593928 -0.19439705 -0.68925309 -0.66218697
  0.7934388  -0.32701523 -0.37301501  0.25016575  0.56090769 -0.26032039
 -0.08929913  0.26879543 -0.60472271 -0.92788716  0.36759015  0.58315272
  0.70014062 -0.1675599   0.33475672 -0.19182794 -0.30429502 -0.39098622
 -0.49190164 -0.63805832  0.41641665  0.83206358 -0.22589615 -0.41215422
  1.37021027  0.34090609 -0.61246034  0.27762789 -0.28659503  0.5330865
 -0.19115469 -0.28584619 -0.35418437 -0.46747962 -0.16567071  0.61054751
  0.0180187  -0.28226053 -0.19000943 -0.53873795  0.73575003 -0.22908048
 -0.69701526 -0.43865113 -0.57364343  0.56413754 -0.74518068 -1.72112876
  0.7208995  -0.39775746  0.12221427 -0.71255367  0.94852665 -0.27281921
  0.72857203  0.40831643 -0.38264361 -0.3200317  -0.57974647  0.00626839
 -0.52840689 -0.38918678 -0.56309407 -0.49469414  0.78922179 -0.42707134
 -0.50671993 -0.23579071  0.83413805  0.22643631  0.35044236 -0.08660325
 -1.04256961 -0.81303636 -0.56171852 -0.32845688  0.53199741 -0.6917304
 -0.36692818 -0.26144513 -0.17995865  1.25761188  1.23718237  0.89623749
  0.37173689 -0.77059228 -0.56743616 -1.16145678 -0.19402878  0.55822712
  1.14110613  0.3953743  -0.22033737  0.44748535 -0.58558383  0.24533947
 -0.37863357  0.30316855  0.66574694  0.60806924 -0.64433588  0.39605633
 -0.48308079 -0.33983432  0.34268649  0.70676636  0.46711781 -0.2194376
 -0.51971294  0.61956905 -0.66520517 -0.30929673 -0.43056302 -0.17590354
 -0.09732245 -0.32491803 -0.54190906  0.73255163  0.47937658  0.28002926
 -0.82959684  1.00141347  1.63196151  0.17500111 -0.66008827  0.77071305
 -0.0874868  -0.34399004 -0.4836565  -0.66513367 -0.21858694  0.45135509
  0.24468973 -0.12937354  0.75060369 -0.23529141  0.56488122 -0.38379794
 -0.7841726   0.31664796  0.02910188  1.02833041  2.08675875  0.33332774
 -0.57219308 -0.43301646 -0.3225914   1.73446646 -0.2502209  -0.53505087
 -0.15651117  1.07180066 -0.32636403 -0.15282268  0.48089241  0.53937884
  0.177341    0.42656325 -0.30355139 -0.22587514  0.57650869 -0.39361651
 -0.88972165 -0.13124944 -1.25851252 -0.89955311  0.35447194 -0.54619818
 -0.66421889  0.34531672 -0.19170236 -0.32805826  0.64208394  0.41217807
  0.29432754  0.21304567 -0.40154786 -0.48268952  0.27788484 -0.3075342
  0.35335816 -0.27184797  0.56001359 -0.17794168  0.22291124 -0.45031015
 -0.34732926 -0.55736719 -0.19089618 -0.56282107 -0.43969694  0.2842801
 -2.4017956  -0.3652337  -0.22567677 -0.6797106  -0.14866827 -0.50834835
 -0.38313191 -0.29397632  0.29464029 -0.23435879  0.86327284  0.25581081
 -0.46076086 -1.31681908 -1.08267553  0.69524381  0.20117192 -0.34080757
 -0.69574701  0.77709829  0.41178738 -0.01026501 -0.2740785   0.64973259
  0.00497867 -0.41315534  0.66279225 -0.42432626 -0.11019998  0.26217008
  0.22095615 -0.64853369 -0.55427731  0.29412057  0.83880363  0.68220709
 -0.3215679  -0.35295092 -0.44507078 -0.81958363 -0.54538682 -0.81664714
 -0.36148829 -0.45017845 -0.63896326  0.5598874   0.52384336 -0.53399351
 -0.2980644  -0.66081763 -0.35323049  0.31595436 -0.37869941 -0.31205581
  1.41439406 -0.13516808 -0.3232065  -0.25639732  0.8182968   0.25807306
 -0.1423715   0.74662037 -0.23291484  0.56338557 -0.05883878  0.74027379
  0.16526012 -0.36606487  0.12091143  0.37141507 -0.48599018  0.29589107
 -0.31174255 -0.24728981  0.34321067 -1.39789097 -0.25844442 -0.30722921
 -0.48115586 -0.37469012 -0.40742497 -0.31269196 -0.71141167 -0.38936515
 -0.31821752 -0.30139614 -0.42148482  0.41552109  0.70648566  0.29696626
 -0.61889471 -0.04618156  0.70731263  0.47699472 -0.03662266  0.63621394
 -0.39874002 -0.39551331  0.91056651 -0.40252226 -0.22811275  0.42069568
  0.08202693 -0.33603507 -0.0762612  -0.38028513 -0.76039869 -0.47018299
  0.53962011 -0.1609916   0.60405698  0.31324513  0.27481762 -0.59886521
 -0.47517911 -0.34567658  0.69639888 -0.22992919  0.23290438  0.44955285
 -0.51657302  0.3213087  -0.59519352  0.75123231 -0.16296131  0.59346669
 -0.3427965   0.26001002 -0.29282075 -0.39111325 -1.28167449  0.78821258
 -0.49047198 -0.24462125 -0.3728449  -0.3530104   0.35453536 -0.76000562
 -0.50847954 -0.8388662  -0.77106736 -0.48195489  1.6581568   0.26837936
  0.41012173 -0.55784937 -0.12237509 -0.50281825  0.31447503 -0.21669332
  0.65232154  0.40060075  0.35337287  0.33083707  0.60627065 -0.40002925
 -0.19086521 -0.57702339 -0.1118639  -0.33708386 -0.37813451 -0.29698703
 -0.63298641  0.96352561  0.32434185  0.71285592 -0.56410197  0.37964055
 -2.47759828  0.23789829  0.16070694  0.15262576 -0.46474757 -0.31188606
  0.6314915   0.58140254  0.18373006  0.3004657  -0.32585748  0.24813526
  0.23583888 -0.25581866 -0.28399222 -0.92796864  0.45418984  0.65641355
  0.28259564 -0.37698907 -0.76328222  0.5453736   1.33175948 -0.27875428
 -0.53084053 -0.52280845  0.26437554  0.34316864 -0.38787165  0.24795375
  0.21478497 -0.49754076 -0.32591614 -0.40239115 -0.44095753 -0.9606388
 -1.08967737 -0.43928912  0.33603404  0.42356639 -0.31487359 -0.29013942
 -0.20816386 -0.54440612  0.23204463  0.44946495 -0.32144376  0.44893207
  0.43573613 -0.53961471 -0.04893838 -0.38650526 -0.36540458 -0.78418149
 -0.22687513 -0.19593196 -0.24698569  0.43680933 -0.68665468 -0.7069126
  1.24135163  0.18953288  0.31477324  0.45113145  1.16074285 -0.35296327
 -0.36509146 -0.4271405  -0.16998501 -0.57447124 -0.40529124 -0.09630049
 -0.95718147  0.29564828  0.68786238  0.14723332 -0.39082847 -0.30811479
  0.34792553  0.13146078 -0.33384668 -0.30772484 -0.28193693 -0.30987893
 -0.34993228  0.71902425  0.90712768 -0.35624536 -0.35419528  0.25129839
 -0.41877534  0.49757772  0.4752921   0.32108866  0.7456354  -0.28182508
 -0.12763909  0.3129133   0.06499953 -0.58446144 -0.35508918]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]
/tmp/ipykernel_1458237/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.77537487 -0.31442553  0.56262093  0.10835197  1.0039888   0.59484648
  0.30054524 -0.28887373 -0.25816145 -0.88024437  0.17613884 -0.15498075
 -0.45177083  0.26231319 -0.20959453 -0.29953972 -0.34523555  0.21838738
  1.73833605  1.3250437   0.30374116  0.51556491  0.20038979  1.18089157
  0.22585974  0.33138281 -0.25886754  0.69576981 -0.41336533 -0.13502606
 -0.77259807 -0.27059716 -0.33218288 -0.39402747 -0.23816384 -1.06722424
 -0.55293746 -0.16469066 -0.28832897  0.43711652  0.68393549  0.28276381
 -0.79508238 -0.17642924 -0.33933156  0.43302483  0.42597293  0.65433174
 -0.24486978 -0.77487017 -0.53307044  0.48970797 -0.2963119  -0.20259415
  0.25108206  0.38993914 -0.43023661  0.7158183  -0.26470115 -0.28503049
 -1.03265685  0.5860109  -0.80877488 -0.98239303 -0.82958819 -0.81400116
 -0.65435968 -1.09748349 -0.44550413 -0.3160452  -0.41026947 -0.86609507
 -0.25855852 -1.21229734 -0.52947808 -0.3163109  -1.02548271 -0.46917885
 -0.48621964  0.46520536 -0.67384514  0.34421067 -0.40118573 -0.27863075
  0.29900453 -0.35535457  0.4872977  -0.41392964 -0.83448889 -0.94950321
  0.33531104 -0.53115219  0.51002248 -0.20435089 -0.58311136 -0.62842264
  0.78344123 -0.28627925 -0.31583975  0.21433644  0.57487509 -0.21212619
 -0.20026883  0.18782681 -0.5307722  -0.75745088  0.4206532   0.57927582
  0.73667108 -0.14385482  0.27196189 -0.16340386 -0.33853674 -0.39485152
 -0.42837773 -0.66563739  0.50242593  0.83392536 -0.32906161 -0.38913967
  1.4698136   0.27608238 -0.69105638  0.25179811 -0.237728    0.49161394
 -0.37154003 -0.30874597 -0.40130326 -0.40694029 -0.33127989  0.64715222
 -0.15938803 -0.30849047 -0.31096436 -0.53895738  0.53407357 -0.29873904
 -0.59200852 -0.23679291 -0.57334983  0.5439192  -0.70818215 -1.86697309
  0.50657326 -0.38666886  0.16677791 -0.60561596  0.88495257 -0.33429703
  0.77031309  0.32742629 -0.62195332 -0.29919572 -0.83865371  0.21098943
 -0.53472779 -0.40238686 -0.51350727 -0.51936894  0.81675256 -0.37060774
 -0.33787375 -0.28387729  0.74917955  0.25439171  0.18102079 -0.19946458
 -1.13448004 -0.49508403 -0.59749468 -0.22990785  0.55804482 -0.72922727
 -0.50343438 -0.30106505 -0.20043241  0.69309558  1.19250976  1.02076356
  0.32665971 -0.73778567 -0.85219965 -1.12648214 -0.22142834  0.54878947
  0.65086389  0.35903937 -0.28066688  0.4426674  -0.61631472  0.44266395
 -0.36467948  0.38114114  0.68623176  0.54777464 -0.58341928  0.56153958
 -0.42619962 -0.3716846   0.13211685  0.72202389  0.34458854 -0.23698685
 -0.49935064  0.59333131 -0.60469104 -0.16060448 -0.45949568 -0.20227433
 -0.15301995 -0.37038081 -0.55596134  0.76032207  0.40638404  0.2456281
 -0.96432011  0.95126058  1.56231592  0.31585459 -0.62470544  0.59236628
 -0.35179708 -0.41999032 -0.55354763 -0.65255034 -0.31374683  0.49504313
  0.18475278 -0.23887985  0.45495891 -0.28472095  0.69534863 -0.50954155
 -0.70783551  0.17523724  0.22923991  0.76157287  2.48923458  0.17322759
 -0.48538736 -0.46216797 -0.22007053  1.63254283 -0.19889902 -0.42915734
 -0.22821686  1.02594603 -0.14774627 -0.2805885   0.41255259  0.50735153
  0.31045807  0.38552256 -0.23165017 -0.20099082  0.44004428 -0.41824521
 -0.90730846 -0.23523198 -1.25100068 -0.89205342  0.25061814 -0.6055653
 -0.61898808  0.3060842  -0.27157566 -0.44195864  0.66393444  0.85383122
  0.2072456   0.13120625 -0.28858867 -0.4002929   0.30549188 -0.40030435
  0.32424339 -0.24438021  0.49011692 -0.22109696  0.36774984 -0.49312211
 -0.3905584  -0.53059193 -0.1252815  -0.49232405 -0.43972585  0.24973473
 -2.34597422 -0.48040462 -0.17957041 -0.55882003 -0.22438111 -0.29716542
 -0.36188122 -0.36472243  0.25648043 -0.15727588  0.75410576  0.24960099
 -0.49015882 -1.28801271 -1.11046502  0.70233261  0.50026539 -0.18917027
 -0.6822733   0.76528681  0.34912661 -0.16223937 -0.34898869  0.66362652
  0.48696941 -0.30806137  0.69315516 -0.35848584 -0.17598209  0.20914308
  0.3130628  -0.63253054 -0.4742456   0.18089236  0.76539457  0.65693457
 -0.41205035 -0.25268451 -0.49872566 -0.83619574 -0.51931551 -0.77095235
 -0.33547472 -0.45992981 -0.67079145  0.48774041  0.45772605 -0.34177878
 -0.36136935 -0.63381757 -0.33348035  0.2310997  -0.34766864 -0.25356665
  1.46078365 -0.23565593 -0.34597975 -0.29832202  0.79185285  0.18384116
 -0.28479773  0.76351532 -0.23553871  0.43440445 -0.24149605  0.82990049
  0.12747677 -0.42144714  0.27914935  0.28810406 -0.91735878  0.27369514
 -0.28657506 -0.27666514  0.39489771 -1.3819702  -0.29478409 -0.22337951
 -0.47151826 -0.28310666 -0.57540625 -0.33791373 -0.52672998 -0.3898663
 -0.30278228 -0.28305555 -0.35898248  0.43372125  0.54449591  0.27247278
 -0.66005545 -0.23068462  0.5187424   0.43909166 -0.20414528  0.66085522
 -0.41010111 -0.39486413  0.73134528 -0.43630828 -0.21750624  0.33807918
  0.31015281 -0.31181706 -0.47947937 -0.37360626 -0.64835426 -0.66213889
  0.56286458 -0.17632089  0.62945065  0.29396822  0.17176798 -0.51065335
 -0.47633163 -0.37547064  0.80258247 -0.27198527  0.36617145  0.38905256
 -0.45700385  0.77600152 -0.56034305  0.72676432 -0.36438401  0.31905246
 -0.39635575  0.17980255 -0.25912333 -0.45491256 -1.14295324  0.71574448
 -0.45708624 -0.20437558 -0.19575263 -0.31279286  0.31690788 -0.75816794
 -0.51196829 -0.74525101 -0.74303781 -0.40719188  1.72667406  0.38873964
  0.2901509  -0.47830457 -0.2523344  -0.34125173  0.39538214 -0.20765517
  0.68344826  0.26198438  0.4527495   0.26694956  0.50960727 -0.5486746
 -0.16686625 -0.5289534  -0.22133141 -0.27174558 -0.36914107 -0.31522565
 -0.64670061  0.92906257  0.2539914   0.68136383 -0.6638999   0.25669868

In [26]:
Data_norm_df

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
AARS,-0.496854,0.288446,0.189747,-0.016454,0.080746,0.282346,0.326246,0.303046,0.387546,0.434746,...,0.846946,0.739186,0.728520,0.661815,0.627668,0.680916,0.700434,0.746670,0.755803,0.789433
ABCB6,-0.658596,-0.142196,-0.075397,-0.383796,-0.199996,-0.074197,0.108804,-0.399196,-0.227496,-0.041146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ABCC5,-0.080204,0.231996,-0.329354,-0.225204,0.278446,0.034696,0.396596,-0.255704,-0.254154,-0.002004,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ABCF1,0.202535,0.602335,0.403335,0.313134,-0.083265,-0.056365,-0.387216,0.097235,0.540634,-0.262666,...,-0.374807,-0.352552,-0.198751,-0.306206,-0.173180,-0.224540,-0.200641,-0.301348,-0.327189,-0.400115
ABCF3,-0.520919,-0.192819,0.001032,-0.096419,0.210881,-0.731118,0.095381,0.313481,-0.078018,-0.257669,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF395,1.796254,1.773154,0.668354,0.825354,0.350654,0.205954,-0.998346,0.235354,0.230653,0.440854,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNF451,-0.244519,0.116732,0.058081,-0.178169,-0.080619,-0.139119,0.064681,-0.083019,-0.272119,-0.164119,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNF586,0.097627,0.061027,-0.337573,0.098427,-0.338173,0.017627,-0.197423,-0.078473,-0.300473,-0.147773,...,-0.796426,-0.374528,-0.369905,-0.345740,-0.201382,-0.056259,-0.226123,-0.499067,-0.395016,-0.387449
ZNF589,0.608573,0.106123,-0.014126,-0.003677,-0.123477,-0.243377,0.044623,-0.021477,0.201823,-0.413227,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZW10,-0.757496,-0.723196,-1.121396,-1.139496,0.077104,-1.088546,0.193104,0.163504,0.372704,-0.677496,...,-0.459066,-0.264433,-0.275769,-0.127617,-0.208151,-0.176909,-0.227164,-0.306851,-0.245169,-0.314552

In [27]:
genes = Data_norm_df.index.tolist()
print('Landmark genes list: ', len(genes), genes)

n_genes = len(genes)

Landmark genes list:  978 ['AARS', 'ABCB6', 'ABCC5', 'ABCF1', 'ABCF3', 'ABHD4', 'ABHD6', 'ABL1', 'ACAA1', 'ACAT2', 'ACBD3', 'ACD', 'ACLY', 'ACOT9', 'ADAM10', 'ADAT1', 'ADGRE5', 'ADGRG1', 'ADH5', 'ADI1', 'ADO', 'ADRB2', 'AGL', 'AKAP8', 'AKAP8L', 'AKR7A2', 'AKT1', 'ALAS1', 'ALDH7A1', 'ALDOA', 'ALDOC', 'AMDHD2', 'ANKRD10', 'ANO10', 'ANXA7', 'APBB2', 'APOE', 'APP', 'APPBP2', 'ARFIP2', 'ARHGAP1', 'ARHGEF12', 'ARHGEF2', 'ARID4B', 'ARID5B', 'ARL4C', 'ARNT2', 'ARPP19', 'ASAH1', 'ASCC3', 'ATF1', 'ATF5', 'ATF6', 'ATG3', 'ATMIN', 'ATP11B', 'ATP1B1', 'ATP2C1', 'ATP6V0B', 'ATP6V1D', 'AURKA', 'AURKB', 'AXIN1', 'B4GAT1', 'BACE2', 'BAD', 'BAG3', 'BAMBI', 'BAX', 'BCL2', 'BCL7B', 'BDH1', 'BECN1', 'BHLHE40', 'BID', 'BIRC2', 'BIRC5', 'BLCAP', 'BLMH', 'BLVRA', 'BMP4', 'BNIP3', 'BNIP3L', 'BPHL', 'BRCA1', 'BTK', 'BUB1B', 'BZW2', 'C2CD2', 'C2CD2L', 'C2CD5', 'C5', 'CAB39', 'CALM3', 'CALU', 'CAMSAP2', 'CANT1', 'CAPN1', 'CARMIL1', 'CASC3', 'CASK', 'CASP10', 'CASP2', 'CASP3', 'CASP7', 'CAST', 'CAT', 'CBLB', 'CBR1', 'CBR3', 'CCDC85B', 'CCDC86', 'CCDC92', 'CCL2', 'CCNA1', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND1', 'CCND3', 'CCNE2', 'CCNF', 'CCNH', 'CCP110', 'CD320', 'CD40', 'CD44', 'CD58', 'CDC20', 'CDC25A', 'CDC25B', 'CDC42', 'CDC45', 'CDCA4', 'CDH3', 'CDK1', 'CDK19', 'CDK2', 'CDK4', 'CDK5R1', 'CDK6', 'CDK7', 'CDKN1A', 'CDKN1B', 'CDKN2A', 'CEBPA', 'CEBPD', 'CEBPZ', 'CEMIP2', 'CENPE', 'CEP57', 'CERK', 'CETN3', 'CFLAR', 'CGRRF1', 'CHAC1', 'CHEK1', 'CHEK2', 'CHERP', 'CHIC2', 'CHMP4A', 'CHMP6', 'CHN1', 'CHP1', 'CIAO3', 'CIAPIN1', 'CIRBP', 'CISD1', 'CLIC4', 'CLPX', 'CLSTN1', 'CLTB', 'CLTC', 'CNDP2', 'CNOT4', 'CNPY3', 'COASY', 'COG2', 'COG4', 'COG7', 'COL1A1', 'COL4A1', 'COPB2', 'COPS7A', 'COQ8A', 'CORO1A', 'CPNE3', 'CPSF4', 'CREB1', 'CREG1', 'CRELD2', 'CRK', 'CRKL', 'CRTAP', 'CRYZ', 'CSK', 'CSNK1A1', 'CSNK1E', 'CSNK2A2', 'CSRP1', 'CTNNAL1', 'CTNND1', 'CTSD', 'CTSL', 'CTTN', 'CXCL2', 'CXCR4', 'CYB561', 'CYCS', 'CYTH1', 'DAG1', 'DAXX', 'DCK', 'DCTD', 'DCUN1D4', 'DDB2', 'DDIT4', 'DDR1', 'DDX10', 'DDX42', 'DECR1', 'DENND2D', 'DERA', 'DFFA', 'DFFB', 'DHDDS', 'DHRS7', 'DHX29', 'DIPK1A', 'DLD', 'DMAC2L', 'DMTF1', 'DNAJA3', 'DNAJB1', 'DNAJB2', 'DNAJB6', 'DNAJC15', 'DNM1', 'DNM1L', 'DNMT1', 'DNMT3A', 'DNTTIP2', 'DPH2', 'DRAP1', 'DSG2', 'DUSP11', 'DUSP14', 'DUSP22', 'DUSP3', 'DUSP4', 'DUSP6', 'DYNLT3', 'DYRK3', 'E2F2', 'EAPP', 'EBNA1BP2', 'EBP', 'ECD', 'ECH1', 'EDEM1', 'EDN1', 'EED', 'EFCAB14', 'EGF', 'EGFR', 'EGR1', 'EIF4EBP1', 'EIF4G1', 'EIF5', 'ELAC2', 'ELAVL1', 'ELOVL6', 'ELP1', 'EML3', 'ENOPH1', 'ENOSF1', 'EPB41L2', 'EPHA3', 'EPHB2', 'EPN2', 'EPRS', 'ERBB2', 'ERBB3', 'ERO1A', 'ETFB', 'ETS1', 'ETV1', 'EVL', 'EXOSC4', 'EXT1', 'EZH2', 'FAH', 'FAIM', 'FAM20B', 'FAM57A', 'FAS', 'FASTKD5', 'FAT1', 'FBXL12', 'FBXO11', 'FBXO21', 'FBXO7', 'FCHO1', 'FDFT1', 'FEZ2', 'FGFR2', 'FGFR4', 'FHL2', 'FIS1', 'FKBP14', 'FKBP4', 'FOS', 'FOSL1', 'FOXJ3', 'FOXO3', 'FOXO4', 'FPGS', 'FRS2', 'FSD1', 'FUT1', 'FYN', 'FZD1', 'FZD7', 'G3BP1', 'GAA', 'GABPB1', 'GADD45A', 'GADD45B', 'GALE', 'GAPDH', 'GATA2', 'GATA3', 'GDPD5', 'GFOD1', 'GFPT1', 'GHR', 'GLI2', 'GLOD4', 'GLRX', 'GMNN', 'GNA11', 'GNA15', 'GNAI1', 'GNAI2', 'GNAS', 'GNB5', 'GNPDA1', 'GOLT1B', 'GPATCH8', 'GPC1', 'GPER1', 'GRB10', 'GRB7', 'GRN', 'GRWD1', 'GSTM2', 'GSTZ1', 'GTF2A2', 'GTF2E2', 'GTPBP8', 'H2AFV', 'HACD3', 'HADH', 'HAT1', 'HDAC2', 'HDAC6', 'HDGFL3', 'HEATR1', 'HEBP1', 'HERC6', 'HERPUD1', 'HES1', 'HIF1A', 'HIST1H2BK', 'HIST2H2BE', 'HK1', 'HLA-DMA', 'HLA-DRA', 'HMG20B', 'HMGA2', 'HMGCR', 'HMGCS1', 'HMOX1', 'HOMER2', 'HOOK2', 'HOXA10', 'HOXA5', 'HPRT1', 'HS2ST1', 'HSD17B10', 'HSD17B11', 'HSPA1A', 'HSPA4', 'HSPA8', 'HSPB1', 'HSPD1', 'HTATSF1', 'HTRA1', 'HYOU1', 'IARS2', 'ICAM1', 'ICAM3', 'ICMT', 'ID2', 'IDE', 'IER3', 'IFNAR1', 'IFRD2', 'IGF1R', 'IGF2BP2', 'IGF2R', 'IGFBP3', 'IGHMBP2', 'IKBKB', 'IKBKE', 'IKZF1', 'IL13RA1', 'IL1B', 'IL4R', 'ILK', 'INPP1', 'INPP4B', 'INSIG1', 'INTS3', 'IPO13', 'IQGAP1', 'ISOC1', 'ITFG1', 'ITGAE', 'ITGB1BP1', 'ITGB5', 'JADE2', 'JMJD6', 'JPT2', 'JUN', 'KAT6A', 'KAT6B', 'KCNK1', 'KCTD5', 'KDELR2', 'KDM3A', 'KDM5A', 'KDM5B', 'KEAP1', 'KHDC4', 'KIAA0100', 'KIAA0355', 'KIAA0753', 'KIF14', 'KIF1BP', 'KIF20A', 'KIF2C', 'KIF5C', 'KIT', 'KLHDC2', 'KLHL21', 'KLHL9', 'KTN1', 'LAGE3', 'LAMA3', 'LAP3', 'LBR', 'LGALS8', 'LGMN', 'LIG1', 'LIPA', 'LOXL1', 'LPAR2', 'LPGAT1', 'LRP10', 'LRPAP1', 'LRRC41', 'LSM5', 'LSM6', 'LSR', 'LYN', 'LYPLA1', 'LYRM1', 'MACF1', 'MALT1', 'MAMLD1', 'MAN2B1', 'MAP2K5', 'MAP3K4', 'MAP4K4', 'MAP7', 'MAPK13', 'MAPK1IP1L', 'MAPK9', 'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MAST2', 'MAT2A', 'MBNL1', 'MBNL2', 'MBOAT7', 'MBTPS1', 'MCM3', 'MCOLN1', 'MCUR1', 'ME2', 'MEF2C', 'MELK', 'MEST', 'METRN', 'MFSD10', 'MICALL1', 'MIF', 'MINDY1', 'MKNK1', 'MLEC', 'MLLT11', 'MMP1', 'MMP2', 'MNAT1', 'MOK', 'MPC2', 'MPZL1', 'MRPL12', 'MRPL19', 'MRPS16', 'MRPS2', 'MSH6', 'MSRA', 'MTA1', 'MTERF3', 'MTF2', 'MTFR1', 'MTHFD2', 'MUC1', 'MVP', 'MYBL2', 'MYC', 'MYCBP', 'MYCBP2', 'MYL9', 'MYLK', 'MYO10', 'NCAPD2', 'NCK1', 'NCK2', 'NCOA3', 'NENF', 'NET1', 'NFATC3', 'NFATC4', 'NFE2L2', 'NFIL3', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NGRN', 'NIPSNAP1', 'NISCH', 'NIT1', 'NMT1', 'NNT', 'NOL3', 'NOLC1', 'NOS3', 'NOSIP', 'NOTCH1', 'NPC1', 'NPDC1', 'NPEPL1', 'NPRL2', 'NR1H2', 'NR2F6', 'NR3C1', 'NRAS', 'NRIP1', 'NSDHL', 'NT5DC2', 'NUCB2', 'NUDCD3', 'NUDT9', 'NUP133', 'NUP62', 'NUP85', 'NUP88', 'NUP93', 'NUSAP1', 'NVL', 'ORC1', 'OXA1L', 'OXCT1', 'OXSR1', 'P4HA2', 'P4HTM', 'PACSIN3', 'PAF1', 'PAFAH1B1', 'PAFAH1B3', 'PAICS', 'PAK1', 'PAK4', 'PAK6', 'PAN2', 'PARP1', 'PARP2', 'PAX8', 'PCBD1', 'PCCB', 'PCK2', 'PCM1', 'PCMT1', 'PCNA', 'PDGFA', 'PDHX', 'PDIA5', 'PDLIM1', 'PDS5A', 'PECR', 'PEX11A', 'PFKL', 'PGAM1', 'PGM1', 'PGRMC1', 'PHGDH', 'PHKA1', 'PHKB', 'PHKG2', 'PIGB', 'PIH1D1', 'PIK3C2B', 'PIK3C3', 'PIK3CA', 'PIK3R3', 'PIK3R4', 'PIN1', 'PIP4K2B', 'PKIG', 'PLA2G15', 'PLA2G4A', 'PLCB3', 'PLEKHJ1', 'PLEKHM1', 'PLK1', 'PLOD3', 'PLP2', 'PLS1', 'PLSCR1', 'PLSCR3', 'PMAIP1', 'PMM2', 'PNKP', 'PNP', 'POLB', 'POLD4', 'POLE2', 'POLG2', 'POLR1C', 'POLR2I', 'POLR2K', 'POP4', 'PPARD', 'PPARG', 'PPIC', 'PPIE', 'PPOX', 'PPP1R13B', 'PPP2R3C', 'PPP2R5A', 'PPP2R5E', 'PRAF2', 'PRCP', 'PRKACA', 'PRKAG2', 'PRKCD', 'PRKCH', 'PRKCQ', 'PRKX', 'PROS1', 'PRPF4', 'PRR15L', 'PRR7', 'PRSS23', 'PRUNE1', 'PSIP1', 'PSMB10', 'PSMB8', 'PSMD10', 'PSMD2', 'PSMD4', 'PSMD9', 'PSME1', 'PSME2', 'PSMF1', 'PSMG1', 'PSRC1', 'PTGS2', 'PTK2', 'PTK2B', 'PTPN1', 'PTPN12', 'PTPN6', 'PTPRC', 'PTPRF', 'PTPRK', 'PUF60', 'PWP1', 'PXMP2', 'PXN', 'PYCR1', 'PYGL', 'RAB11FIP2', 'RAB21', 'RAB27A', 'RAB31', 'RAB4A', 'RAC2', 'RAD51C', 'RAD9A', 'RAE1', 'RAI14', 'RALA', 'RALB', 'RALGDS', 'RAP1GAP', 'RASA1', 'RB1', 'RBKS', 'RBM15B', 'RBM34', 'RBM6', 'REEP5', 'RELB', 'RFC2', 'RFC5', 'RFNG', 'RFX5', 'RGS2', 'RHEB', 'RHOA', 'RNF167', 'RNH1', 'RNMT', 'RNPS1', 'RPA1', 'RPA2', 'RPA3', 'RPIA', 'RPL39L', 'RPN1', 'RPP38', 'RPS5', 'RPS6', 'RPS6KA1', 'RRAGA', 'RRP12', 'RRP1B', 'RRP8', 'RRS1', 'RSU1', 'RTN2', 'RUVBL1', 'RXYLT1', 'S100A13', 'S100A4', 'SACM1L', 'SATB1', 'SCAND1', 'SCARB1', 'SCCPDH', 'SCP2', 'SCRN1', 'SCYL3', 'SDHB', 'SENP6', 'SERPINE1', 'SESN1', 'SFN', 'SGCB', 'SH3BP5', 'SHB', 'SHC1', 'SIRT3', 'SKIV2L', 'SKP1', 'SLC11A2', 'SLC1A4', 'SLC25A13', 'SLC25A14', 'SLC25A4', 'SLC25A46', 'SLC27A3', 'SLC2A6', 'SLC35A1', 'SLC35A3', 'SLC35B1', 'SLC35F2', 'SLC37A4', 'SLC5A6', 'SMAD3', 'SMARCA4', 'SMARCC1', 'SMARCD2', 'SMC1A', 'SMC3', 'SMC4', 'SMNDC1', 'SNAP25', 'SNCA', 'SNX11', 'SNX13', 'SNX6', 'SNX7', 'SOCS2', 'SORBS3', 'SOX2', 'SOX4', 'SPAG4', 'SPAG7', 'SPDEF', 'SPEN', 'SPP1', 'SPR', 'SPRED2', 'SPTAN1', 'SPTLC2', 'SQOR', 'SQSTM1', 'SRC', 'SSBP2', 'ST3GAL5', 'ST6GALNAC2', 'ST7', 'STAMBP', 'STAP2', 'STAT1', 'STAT3', 'STAT5B', 'STIMATE', 'STK10', 'STK25', 'STMN1', 'STUB1', 'STX1A', 'STX4', 'STXBP1', 'STXBP2', 'SUPV3L1', 'SUV39H1', 'SUZ12', 'SYK', 'SYNE2', 'SYNGR3', 'SYPL1', 'TARBP1', 'TATDN2', 'TBC1D31', 'TBC1D9B', 'TBP', 'TBPL1', 'TBX2', 'TBXA2R', 'TCEA2', 'TCEAL4', 'TCERG1', 'TCFL5', 'TCTA', 'TCTN1', 'TENT4A', 'TERF2IP', 'TERT', 'TES', 'TESK1', 'TEX10', 'TFAP2A', 'TFDP1', 'TGFB3', 'TGFBR2', 'THAP11', 'TIAM1', 'TICAM1', 'TIMELESS', 'TIMM17B', 'TIMM22', 'TIMM9', 'TIMP2', 'TIPARP', 'TJP1', 'TLE1', 'TLK2', 'TLR4', 'TM9SF2', 'TM9SF3', 'TMCO1', 'TMED10', 'TMEM109', 'TMEM50A', 'TMEM97', 'TNFRSF21', 'TNIP1', 'TOMM34', 'TOMM70', 'TOP2A', 'TOPBP1', 'TOR1A', 'TP53', 'TP53BP1', 'TP53BP2', 'TPD52L2', 'TPM1', 'TRAK2', 'TRAM2', 'TRAP1', 'TRAPPC3', 'TRAPPC6A', 'TRIB1', 'TRIB3', 'TRIM13', 'TRIM2', 'TSC22D3', 'TSEN2', 'TSKU', 'TSPAN3', 'TSPAN4', 'TSPAN6', 'TSTA3', 'TUBB6', 'TWF2', 'TXLNA', 'TXNDC9', 'TXNL4B', 'TXNRD1', 'UBE2A', 'UBE2C', 'UBE2J1', 'UBE2L6', 'UBE3B', 'UBE3C', 'UBQLN2', 'UBR7', 'UFM1', 'UGDH', 'USP1', 'USP14', 'USP22', 'USP6NL', 'USP7', 'UTP14A', 'VAPB', 'VAT1', 'VAV3', 'VDAC1', 'VGLL4', 'VPS28', 'VPS72', 'WASF3', 'WASHC4', 'WASHC5', 'WDR61', 'WDR7', 'WDTC1', 'WFS1', 'WIPF2', 'WRB', 'XBP1', 'XPNPEP1', 'XPO7', 'YKT6', 'YME1L1', 'YTHDF1', 'ZDHHC6', 'ZFP36', 'ZMIZ1', 'ZMYM2', 'ZNF131', 'ZNF274', 'ZNF318', 'ZNF395', 'ZNF451', 'ZNF586', 'ZNF589', 'ZW10']

## Inhibitor concentrations, IC50, and perturbation matrices

In [28]:
inhib_conc_matrix = np.zeros((n_modules, n_experiments))
ic50_matrix = np.ones((n_modules, n_experiments))
gamma_matrix = np.zeros((n_modules, n_experiments))

In [29]:

for i, module in enumerate(modules):
    drugs_for_module = IC50_df.Drug[IC50_df.Module == module].tolist()
    for drug in drugs_for_module:
        # get IC50 for this drug
        ic50 = IC50_df.IC50[IC50_df.Drug == drug].values
#       gamma = IC50_df.Gamma[IC50_df.Drug == drug].values
        print(drug, ic50)
        assert ic50.size == 1
#       assert gamma.size == 1
        # get experiments with this drug
        exp_with_drug = sig_info_df.index[sig_info_df.pert_drug == drug].tolist()
        print(exp_with_drug) 
        for exp_id in exp_with_drug:
            j = exp_ids.index(exp_id)
            print(j)
            # extract inhibitor concentration
            inhib_conc = sig_info_df.dose_float[sig_info_df.index == exp_id].values
            assert inhib_conc.size == 1
            # insert values in matrices
            inhib_conc_matrix[i, j] = inhib_conc.item()
            ic50_matrix[i, j] = ic50.item()
#           gamma_matrix[i, j] = gamma.item()

JNJ-7706621 [0.027]
['ASG002_BC3C_24H:N13', 'ASG002_BC3C_24H:N14', 'ASG002_BC3C_24H:N15']
51
52
53
PHA-793887 [0.18]
['ASG002_BC3C_24H:L01', 'ASG002_BC3C_24H:L02', 'ASG002_BC3C_24H:L03']
43
44
45
roscovitine [2.]
['ASG002_BC3C_24H:E22', 'ASG002_BC3C_24H:E23', 'ASG002_BC3C_24H:E24']
15
16
17
alvocidib [0.12]
['ASG002_BC3C_24H:F05', 'ASG002_BC3C_24H:F06']
21
22
palbociclib [0.045]
['ASG002_BC3C_24H:P16', 'ASG002_BC3C_24H:P18']
66
67
afatinib [0.03]
['ASG002_BC3C_24H:N23', 'ASG002_BC3C_24H:N24']
56
57
erlotinib [0.006]
['ASG002_BC3C_24H:H16', 'ASG002_BC3C_24H:H17', 'ASG002_BC3C_24H:H18']
30
31
32
gefitinib [0.171]
['ASG002_BC3C_24H:F16', 'ASG002_BC3C_24H:F17', 'ASG002_BC3C_24H:F18']
25
26
27
lapatinib [0.0324]
['ASG002_BC3C_24H:I13', 'ASG002_BC3C_24H:I14', 'ASG002_BC3C_24H:I15']
38
39
40
vandetanib [1.5]
['ASG002_BC3C_24H:N20', 'ASG002_BC3C_24H:N21']
54
55
dienestrol [200.]
['ASG002_BC3C_24H:M22', 'ASG002_BC3C_24H:M23', 'ASG002_BC3C_24H:M24']
48
49
50
estradiol-cypionate [200.]
['ASG002_BC3C_24H:L16', 'ASG002_BC3C_24H:L17']
46
47
raloxifene [0.0171]
['ASG002_BC3C_24H:O10', 'ASG002_BC3C_24H:O11', 'ASG002_BC3C_24H:O12']
58
59
60
masitinib [2.5]
['ASG002_BC3C_24H:E19', 'ASG002_BC3C_24H:E20', 'ASG002_BC3C_24H:E21']
12
13
14
sorafenib [1.74]
['ASG002_BC3C_24H:F13', 'ASG002_BC3C_24H:F14']
23
24
ponatinib [0.0066]
['ASG002_BC3C_24H:I20', 'ASG002_BC3C_24H:I21']
41
42
PI-103 [0.09]
['ASG002_BC3C_24H:O22', 'ASG002_BC3C_24H:O23']
61
62
AS-605240 [0.1595]
['ASG002_BC3C_24H:A19', 'ASG002_BC3C_24H:A20', 'ASG002_BC3C_24H:A21']
2
3
4
LY-294002 [1.36]
['ASG002_BC3C_24H:F01', 'ASG002_BC3C_24H:F02', 'ASG002_BC3C_24H:F03']
18
19
20
taselisib [0.00262]
['ASG002_BC3C_24H:A10', 'ASG002_BC3C_24H:A11']
0
1
AZD-8055 [0.2743]
[]
AMG-232 [0.0018]
['ASG002_BC3C_24H:B10', 'ASG002_BC3C_24H:B11']
5
6
HLI-373 [3.]
['MOAR008_BC3C_24H:L08']
70
nutlin-3 [0.54]
['ASG002_BC3C_24H:C13', 'ASG002_BC3C_24H:C14', 'ASG002_BC3C_24H:C15', 'MOAR009_BC3C_24H:C10', 'MOAR009_BC3C_24H:C11', 'MOAR009_BC3C_24H:C12']
9
10
11
71
72
73
RITA [9.75]
['ASG002_BC3C_24H:B14', 'ASG002_BC3C_24H:B15', 'MOAR010_BC3C_24H:A13', 'MOAR010_BC3C_24H:A14', 'MOAR010_BC3C_24H:A15']
7
8
74
75
76
SAR405838 [0.0264]
['MOAR010_BC3C_24H:K07', 'MOAR010_BC3C_24H:K08', 'MOAR010_BC3C_24H:K09']
80
81
82
serdemetan [62.15]
['MOAR010_BC3C_24H:J22', 'MOAR010_BC3C_24H:J23', 'MOAR010_BC3C_24H:J24', 'MOAR011_BC3C_24H:F07', 'MOAR011_BC3C_24H:F08', 'MOAR011_BC3C_24H:F09']
77
78
79
83
84
85
daunorubicin [0.02]
['ASG002_BC3C_24H:I05', 'ASG002_BC3C_24H:I06']
33
34
epirubicin [0.17]
['ASG002_BC3C_24H:G02', 'ASG002_BC3C_24H:G03']
28
29
idarubicin [0.0099]
['ASG002_BC3C_24H:P20', 'ASG002_BC3C_24H:P21']
68
69
mitoxantrone [5.3]
['ASG002_BC3C_24H:P07', 'ASG002_BC3C_24H:P08', 'ASG002_BC3C_24H:P09']
63
64
65
dasatinib [0.0024]
['ASG002_BC3C_24H:I07', 'ASG002_BC3C_24H:I08', 'ASG002_BC3C_24H:I09']
35
36
37
Agent2 [10.]
[]

In [30]:
inhib_conc_matrix

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,  0.12,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,
         0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,  0.12,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  , 10.  ,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,
         0.12,  0.  ,  0.  , 10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  , 10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         1.11,  0.12,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  , 10.  ,  1.11, 10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,  0.12,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  , 10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.11,  0.12,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [10.  ,  1.11, 10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,  1.11,  1.11,  0.08,
        10.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  3.33, 10.  ,
         3.33,  1.11, 10.  ,  3.33,  1.11, 10.  ,  3.33,  1.11, 10.  ,
         3.33,  1.11, 10.  ,  3.33,  1.11],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  1.11,  0.12,  0.  ,  0.  ,  0.  ,  1.11,  0.12,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        10.  ,  1.11,  0.12,  0.  ,  0.  ,  1.11,  0.12,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.  ,
         1.11,  0.12,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [31]:
# transform matrices into pandas dfs for export with row and column names
inhib_conc_df = pd.DataFrame(inhib_conc_matrix, index = modules, columns = exp_ids)
ic50_df = pd.DataFrame(ic50_matrix, index = modules, columns = exp_ids)
# gamma_df = pd.DataFrame(gamma_matrix, index = modules, columns = exp_ids)

# create binary perturbation matrix
pert_df = pd.DataFrame(
    np.where(inhib_conc_matrix != 0, 1, 0),
    index = inhib_conc_df.index,
    columns = inhib_conc_df.columns,
)

In [32]:
display(ic50_df)
# display(gamma_df)
display(inhib_conc_df)
display(pert_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:A15,MOAR010_BC3C_24H:J22,MOAR010_BC3C_24H:J23,MOAR010_BC3C_24H:J24,MOAR010_BC3C_24H:K07,MOAR010_BC3C_24H:K08,MOAR010_BC3C_24H:K09,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09
CDK1_2,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
CDK4_6,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
EGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
Estrogen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
FGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
PI3K,0.00262,0.00262,0.1595,0.1595,0.1595,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
p53,1.00000,1.00000,1.0000,1.0000,1.0000,0.0018,0.0018,9.75,9.75,0.54,...,9.75,62.15,62.15,62.15,0.0264,0.0264,0.0264,62.15,62.15,62.15
TOP2A,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
Src,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00
SMAD3,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.0000,1.0000,1.0000,1.00,1.00,1.00

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:A15,MOAR010_BC3C_24H:J22,MOAR010_BC3C_24H:J23,MOAR010_BC3C_24H:J24,MOAR010_BC3C_24H:K07,MOAR010_BC3C_24H:K08,MOAR010_BC3C_24H:K09,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09
CDK1_2,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
CDK4_6,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
EGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
Estrogen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
FGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
PI3K,10.0,1.11,10.0,1.11,0.12,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
p53,0.0,0.00,0.0,0.00,0.00,10.0,1.11,1.11,0.08,10.0,...,1.11,10.0,3.33,1.11,10.0,3.33,1.11,10.0,3.33,1.11
TOP2A,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
Src,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00
SMAD3,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:A15,MOAR010_BC3C_24H:J22,MOAR010_BC3C_24H:J23,MOAR010_BC3C_24H:J24,MOAR010_BC3C_24H:K07,MOAR010_BC3C_24H:K08,MOAR010_BC3C_24H:K09,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09
CDK1_2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDK4_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
EGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Estrogen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PI3K,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
p53,0,0,0,0,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
TOP2A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Src,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMAD3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
cols = list(smad_lfc.columns)

ic50_df[cols] = 1.0
inhib_conc_df[cols] = 0.0
pert_df[cols] = 0

In [34]:
ic50_df

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
CDK1_2,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
CDK4_6,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
EGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Estrogen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
FGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
PI3K,0.00262,0.00262,0.1595,0.1595,0.1595,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
p53,1.00000,1.00000,1.0000,1.0000,1.0000,0.0018,0.0018,9.75,9.75,0.54,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
TOP2A,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Src,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
SMAD3,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [71]:
ic50_df.loc['SMAD3',smad_lfc.columns] = 7

In [72]:
inhib_conc_df.loc['SMAD3',smad_lfc.columns] = 10

In [73]:
pert_df.loc['SMAD3',smad_lfc.columns] = 1

In [74]:
display(ic50_df)
# display(gamma_df)
display(inhib_conc_df)
display(pert_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
CDK1_2,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
CDK4_6,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
EGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Estrogen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
FGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
PI3K,0.00262,0.00262,0.1595,0.1595,0.1595,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
p53,1.00000,1.00000,1.0000,1.0000,1.0000,0.0018,0.0018,9.75,9.75,0.54,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
TOP2A,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Src,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
SMAD3,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
CDK1_2,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CDK4_6,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Estrogen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
FGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PI3K,10.0,1.11,10.0,1.11,0.12,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
p53,0.0,0.00,0.0,0.00,0.00,10.0,1.11,1.11,0.08,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TOP2A,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Src,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SMAD3,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
CDK1_2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDK4_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
EGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Estrogen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PI3K,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
p53,0,0,0,0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
TOP2A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Src,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMAD3,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

## Global responses for DPD modules

According to our discussion, $R$ for DPD vectors can not be calculated with the same formula as for pathway activities. Instead we are assuming:

\begin{equation}
R_{DPD},j = DPD = STV_{DPD} \cdot Data_j
\end{equation}

In [75]:
# load STV data frame
STVs = pd.read_excel(os.path.join(info_dir, "ALL_DATA_2020_post.xlsx"), sheet_name = "STV", index_col = 0)
STV_df = pd.DataFrame(np.zeros((len(Data_norm_df.index), 7)), index = Data_norm_df.index, columns = STVs.columns)
STV_df.loc[STVs.index] = STVs

display(STV_df)

        DPD_BL   DPD_onc  DPD_risk  DPD_T2  DPD_Ta  DPD_immuno  DPD_immuno_0
AARS       0.0  0.078480  0.000000     0.0     0.0         0.0      0.000000
ABCB6      0.0  0.027123 -0.153918     0.0     0.0         0.0      0.016004
ABCC5      0.0  0.002120  0.000000     0.0     0.0         0.0     -0.006153
ABCF1      0.0 -0.028956 -0.026418     0.0     0.0         0.0     -0.036127
ABCF3      0.0  0.036668  0.000000     0.0     0.0         0.0     -0.004999
...        ...       ...       ...     ...     ...         ...           ...
ZNF395     0.0  0.000000  0.000000     0.0     0.0         0.0      0.010048
ZNF451     0.0  0.013401  0.000000     0.0     0.0         0.0     -0.009844
ZNF586     0.0  0.000000  0.006341     0.0     0.0         0.0      0.039816
ZNF589     0.0  0.000000  0.000000     0.0     0.0         0.0      0.018821
ZW10       0.0  0.009721  0.000000     0.0     0.0         0.0     -0.055413

[978 rows x 7 columns]

In [76]:
STV_df = STV_df[['DPD_onc','DPD_risk','DPD_immuno_0']]

In [77]:
# create empty DPD data frame
DPD_df = pd.DataFrame(
    np.zeros((len(Data_norm_df.columns), len(STV_df.columns))),
    index = Data_norm_df.columns,
    columns = STV_df.columns,
)

# populate
for exp_id in DPD_df.index:
    for state in STV_df.columns:
        DPD_df.loc[exp_id, state] = np.dot(Data_norm_df.T.loc[exp_id], STV_df.loc[:, state])

display(DPD_df)

                      DPD_onc  DPD_risk  DPD_immuno_0
ASG002_BC3C_24H:A10 -0.610595 -0.925192     -0.355927
ASG002_BC3C_24H:A11 -0.935965 -0.306921     -0.645334
ASG002_BC3C_24H:A19 -0.048492  0.525629     -0.050693
ASG002_BC3C_24H:A20 -0.647615 -0.031134     -0.482723
ASG002_BC3C_24H:A21  0.031647 -0.330139      0.330559
...                       ...       ...           ...
SMAD_V16            -0.604095 -0.674103     -0.376065
SMAD_V17            -0.604703 -0.921762     -0.344518
SMAD_V18            -0.868657 -1.018414     -0.435230
SMAD_V19            -0.735838 -0.894276     -0.458314
SMAD_V20            -1.067839 -1.174936     -0.516428

[106 rows x 3 columns]

In [78]:
# transform to R global
R_global_DPD_df = DPD_df.T
display(R_global_DPD_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD_V11,SMAD_V12,SMAD_V13,SMAD_V14,SMAD_V15,SMAD_V16,SMAD_V17,SMAD_V18,SMAD_V19,SMAD_V20
DPD_onc,-0.610595,-0.935965,-0.048492,-0.647615,0.031647,0.185961,0.911044,-0.079380,-0.459700,-0.521396,...,-1.136556,-0.816184,-0.719059,-0.512580,-0.501753,-0.604095,-0.604703,-0.868657,-0.735838,-1.067839
DPD_risk,-0.925192,-0.306921,0.525629,-0.031134,-0.330139,0.097778,-0.162965,-0.190680,0.055438,-0.322754,...,-1.388249,-0.919212,-0.884448,-0.677994,-0.688052,-0.674103,-0.921762,-1.018414,-0.894276,-1.174936
DPD_immuno_0,-0.355927,-0.645334,-0.050693,-0.482723,0.330559,-0.716308,0.157080,-0.374256,-0.223585,-0.426159,...,-0.481136,-0.512503,-0.448582,-0.323753,-0.239786,-0.376065,-0.344518,-0.435230,-0.458314,-0.516428

## Save outputs

In [79]:
# save metadata as pickle
all_metadata = {
    "modules": modules,
    "n_modules": n_modules,
    "drugs": drugs,
    "n_drugs": n_drugs,
    "exp_ids": exp_ids,
    "n_experiments": n_experiments,
    "genes": genes,
    "n_genes": n_genes,
}

print(all_metadata)

with open(os.path.join(out_dir, "metadata.pickle"), "wb") as f:
    pickle.dump(all_metadata, f, protocol = pickle.HIGHEST_PROTOCOL)

{'modules': ['CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'SMAD3'], 'n_modules': 10, 'drugs': ['dasatinib', 'RITA', 'daunorubicin', 'afatinib', 'serdemetan', 'vandetanib', 'AS-605240', 'SAR405838', 'taselisib', 'estradiol-cypionate', 'epirubicin', 'palbociclib', 'HLI-373', 'alvocidib', 'dienestrol', 'sorafenib', 'roscovitine', 'gefitinib', 'nutlin-3', 'masitinib', 'PI-103', 'ponatinib', 'idarubicin', 'erlotinib', 'JNJ-7706621', 'mitoxantrone', 'lapatinib', 'LY-294002', 'Agent2', 'raloxifene', 'AMG-232', 'AZD-8055', 'PHA-793887'], 'n_drugs': 33, 'exp_ids': ['ASG002_BC3C_24H:A10', 'ASG002_BC3C_24H:A11', 'ASG002_BC3C_24H:A19', 'ASG002_BC3C_24H:A20', 'ASG002_BC3C_24H:A21', 'ASG002_BC3C_24H:B10', 'ASG002_BC3C_24H:B11', 'ASG002_BC3C_24H:B14', 'ASG002_BC3C_24H:B15', 'ASG002_BC3C_24H:C13', 'ASG002_BC3C_24H:C14', 'ASG002_BC3C_24H:C15', 'ASG002_BC3C_24H:E19', 'ASG002_BC3C_24H:E20', 'ASG002_BC3C_24H:E21', 'ASG002_BC3C_24H:E22', 'ASG002_BC3C_24H:E23', 'ASG002_BC3C_24H:E24', 'ASG002_BC3C_24H:F01', 'ASG002_BC3C_24H:F02', 'ASG002_BC3C_24H:F03', 'ASG002_BC3C_24H:F05', 'ASG002_BC3C_24H:F06', 'ASG002_BC3C_24H:F13', 'ASG002_BC3C_24H:F14', 'ASG002_BC3C_24H:F16', 'ASG002_BC3C_24H:F17', 'ASG002_BC3C_24H:F18', 'ASG002_BC3C_24H:G02', 'ASG002_BC3C_24H:G03', 'ASG002_BC3C_24H:H16', 'ASG002_BC3C_24H:H17', 'ASG002_BC3C_24H:H18', 'ASG002_BC3C_24H:I05', 'ASG002_BC3C_24H:I06', 'ASG002_BC3C_24H:I07', 'ASG002_BC3C_24H:I08', 'ASG002_BC3C_24H:I09', 'ASG002_BC3C_24H:I13', 'ASG002_BC3C_24H:I14', 'ASG002_BC3C_24H:I15', 'ASG002_BC3C_24H:I20', 'ASG002_BC3C_24H:I21', 'ASG002_BC3C_24H:L01', 'ASG002_BC3C_24H:L02', 'ASG002_BC3C_24H:L03', 'ASG002_BC3C_24H:L16', 'ASG002_BC3C_24H:L17', 'ASG002_BC3C_24H:M22', 'ASG002_BC3C_24H:M23', 'ASG002_BC3C_24H:M24', 'ASG002_BC3C_24H:N13', 'ASG002_BC3C_24H:N14', 'ASG002_BC3C_24H:N15', 'ASG002_BC3C_24H:N20', 'ASG002_BC3C_24H:N21', 'ASG002_BC3C_24H:N23', 'ASG002_BC3C_24H:N24', 'ASG002_BC3C_24H:O10', 'ASG002_BC3C_24H:O11', 'ASG002_BC3C_24H:O12', 'ASG002_BC3C_24H:O22', 'ASG002_BC3C_24H:O23', 'ASG002_BC3C_24H:P07', 'ASG002_BC3C_24H:P08', 'ASG002_BC3C_24H:P09', 'ASG002_BC3C_24H:P16', 'ASG002_BC3C_24H:P18', 'ASG002_BC3C_24H:P20', 'ASG002_BC3C_24H:P21', 'MOAR008_BC3C_24H:L08', 'MOAR009_BC3C_24H:C10', 'MOAR009_BC3C_24H:C11', 'MOAR009_BC3C_24H:C12', 'MOAR010_BC3C_24H:A13', 'MOAR010_BC3C_24H:A14', 'MOAR010_BC3C_24H:A15', 'MOAR010_BC3C_24H:J22', 'MOAR010_BC3C_24H:J23', 'MOAR010_BC3C_24H:J24', 'MOAR010_BC3C_24H:K07', 'MOAR010_BC3C_24H:K08', 'MOAR010_BC3C_24H:K09', 'MOAR011_BC3C_24H:F07', 'MOAR011_BC3C_24H:F08', 'MOAR011_BC3C_24H:F09'], 'n_experiments': 86, 'genes': ['AARS', 'ABCB6', 'ABCC5', 'ABCF1', 'ABCF3', 'ABHD4', 'ABHD6', 'ABL1', 'ACAA1', 'ACAT2', 'ACBD3', 'ACD', 'ACLY', 'ACOT9', 'ADAM10', 'ADAT1', 'ADGRE5', 'ADGRG1', 'ADH5', 'ADI1', 'ADO', 'ADRB2', 'AGL', 'AKAP8', 'AKAP8L', 'AKR7A2', 'AKT1', 'ALAS1', 'ALDH7A1', 'ALDOA', 'ALDOC', 'AMDHD2', 'ANKRD10', 'ANO10', 'ANXA7', 'APBB2', 'APOE', 'APP', 'APPBP2', 'ARFIP2', 'ARHGAP1', 'ARHGEF12', 'ARHGEF2', 'ARID4B', 'ARID5B', 'ARL4C', 'ARNT2', 'ARPP19', 'ASAH1', 'ASCC3', 'ATF1', 'ATF5', 'ATF6', 'ATG3', 'ATMIN', 'ATP11B', 'ATP1B1', 'ATP2C1', 'ATP6V0B', 'ATP6V1D', 'AURKA', 'AURKB', 'AXIN1', 'B4GAT1', 'BACE2', 'BAD', 'BAG3', 'BAMBI', 'BAX', 'BCL2', 'BCL7B', 'BDH1', 'BECN1', 'BHLHE40', 'BID', 'BIRC2', 'BIRC5', 'BLCAP', 'BLMH', 'BLVRA', 'BMP4', 'BNIP3', 'BNIP3L', 'BPHL', 'BRCA1', 'BTK', 'BUB1B', 'BZW2', 'C2CD2', 'C2CD2L', 'C2CD5', 'C5', 'CAB39', 'CALM3', 'CALU', 'CAMSAP2', 'CANT1', 'CAPN1', 'CARMIL1', 'CASC3', 'CASK', 'CASP10', 'CASP2', 'CASP3', 'CASP7', 'CAST', 'CAT', 'CBLB', 'CBR1', 'CBR3', 'CCDC85B', 'CCDC86', 'CCDC92', 'CCL2', 'CCNA1', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND1', 'CCND3', 'CCNE2', 'CCNF', 'CCNH', 'CCP110', 'CD320', 'CD40', 'CD44', 'CD58', 'CDC20', 'CDC25A', 'CDC25B', 'CDC42', 'CDC45', 'CDCA4', 'CDH3', 'CDK1', 'CDK19', 'CDK2', 'CDK4', 'CDK5R1', 'CDK6', 'CDK7', 'CDKN1A', 'CDKN1B', 'CDKN2A', 'CEBPA', 'CEBPD', 'CEBPZ', 'CEMIP2', 'CENPE', 'CEP57', 'CERK', 'CETN3', 'CFLAR', 'CGRRF1', 'CHAC1', 'CHEK1', 'CHEK2', 'CHERP', 'CHIC2', 'CHMP4A', 'CHMP6', 'CHN1', 'CHP1', 'CIAO3', 'CIAPIN1', 'CIRBP', 'CISD1', 'CLIC4', 'CLPX', 'CLSTN1', 'CLTB', 'CLTC', 'CNDP2', 'CNOT4', 'CNPY3', 'COASY', 'COG2', 'COG4', 'COG7', 'COL1A1', 'COL4A1', 'COPB2', 'COPS7A', 'COQ8A', 'CORO1A', 'CPNE3', 'CPSF4', 'CREB1', 'CREG1', 'CRELD2', 'CRK', 'CRKL', 'CRTAP', 'CRYZ', 'CSK', 'CSNK1A1', 'CSNK1E', 'CSNK2A2', 'CSRP1', 'CTNNAL1', 'CTNND1', 'CTSD', 'CTSL', 'CTTN', 'CXCL2', 'CXCR4', 'CYB561', 'CYCS', 'CYTH1', 'DAG1', 'DAXX', 'DCK', 'DCTD', 'DCUN1D4', 'DDB2', 'DDIT4', 'DDR1', 'DDX10', 'DDX42', 'DECR1', 'DENND2D', 'DERA', 'DFFA', 'DFFB', 'DHDDS', 'DHRS7', 'DHX29', 'DIPK1A', 'DLD', 'DMAC2L', 'DMTF1', 'DNAJA3', 'DNAJB1', 'DNAJB2', 'DNAJB6', 'DNAJC15', 'DNM1', 'DNM1L', 'DNMT1', 'DNMT3A', 'DNTTIP2', 'DPH2', 'DRAP1', 'DSG2', 'DUSP11', 'DUSP14', 'DUSP22', 'DUSP3', 'DUSP4', 'DUSP6', 'DYNLT3', 'DYRK3', 'E2F2', 'EAPP', 'EBNA1BP2', 'EBP', 'ECD', 'ECH1', 'EDEM1', 'EDN1', 'EED', 'EFCAB14', 'EGF', 'EGFR', 'EGR1', 'EIF4EBP1', 'EIF4G1', 'EIF5', 'ELAC2', 'ELAVL1', 'ELOVL6', 'ELP1', 'EML3', 'ENOPH1', 'ENOSF1', 'EPB41L2', 'EPHA3', 'EPHB2', 'EPN2', 'EPRS', 'ERBB2', 'ERBB3', 'ERO1A', 'ETFB', 'ETS1', 'ETV1', 'EVL', 'EXOSC4', 'EXT1', 'EZH2', 'FAH', 'FAIM', 'FAM20B', 'FAM57A', 'FAS', 'FASTKD5', 'FAT1', 'FBXL12', 'FBXO11', 'FBXO21', 'FBXO7', 'FCHO1', 'FDFT1', 'FEZ2', 'FGFR2', 'FGFR4', 'FHL2', 'FIS1', 'FKBP14', 'FKBP4', 'FOS', 'FOSL1', 'FOXJ3', 'FOXO3', 'FOXO4', 'FPGS', 'FRS2', 'FSD1', 'FUT1', 'FYN', 'FZD1', 'FZD7', 'G3BP1', 'GAA', 'GABPB1', 'GADD45A', 'GADD45B', 'GALE', 'GAPDH', 'GATA2', 'GATA3', 'GDPD5', 'GFOD1', 'GFPT1', 'GHR', 'GLI2', 'GLOD4', 'GLRX', 'GMNN', 'GNA11', 'GNA15', 'GNAI1', 'GNAI2', 'GNAS', 'GNB5', 'GNPDA1', 'GOLT1B', 'GPATCH8', 'GPC1', 'GPER1', 'GRB10', 'GRB7', 'GRN', 'GRWD1', 'GSTM2', 'GSTZ1', 'GTF2A2', 'GTF2E2', 'GTPBP8', 'H2AFV', 'HACD3', 'HADH', 'HAT1', 'HDAC2', 'HDAC6', 'HDGFL3', 'HEATR1', 'HEBP1', 'HERC6', 'HERPUD1', 'HES1', 'HIF1A', 'HIST1H2BK', 'HIST2H2BE', 'HK1', 'HLA-DMA', 'HLA-DRA', 'HMG20B', 'HMGA2', 'HMGCR', 'HMGCS1', 'HMOX1', 'HOMER2', 'HOOK2', 'HOXA10', 'HOXA5', 'HPRT1', 'HS2ST1', 'HSD17B10', 'HSD17B11', 'HSPA1A', 'HSPA4', 'HSPA8', 'HSPB1', 'HSPD1', 'HTATSF1', 'HTRA1', 'HYOU1', 'IARS2', 'ICAM1', 'ICAM3', 'ICMT', 'ID2', 'IDE', 'IER3', 'IFNAR1', 'IFRD2', 'IGF1R', 'IGF2BP2', 'IGF2R', 'IGFBP3', 'IGHMBP2', 'IKBKB', 'IKBKE', 'IKZF1', 'IL13RA1', 'IL1B', 'IL4R', 'ILK', 'INPP1', 'INPP4B', 'INSIG1', 'INTS3', 'IPO13', 'IQGAP1', 'ISOC1', 'ITFG1', 'ITGAE', 'ITGB1BP1', 'ITGB5', 'JADE2', 'JMJD6', 'JPT2', 'JUN', 'KAT6A', 'KAT6B', 'KCNK1', 'KCTD5', 'KDELR2', 'KDM3A', 'KDM5A', 'KDM5B', 'KEAP1', 'KHDC4', 'KIAA0100', 'KIAA0355', 'KIAA0753', 'KIF14', 'KIF1BP', 'KIF20A', 'KIF2C', 'KIF5C', 'KIT', 'KLHDC2', 'KLHL21', 'KLHL9', 'KTN1', 'LAGE3', 'LAMA3', 'LAP3', 'LBR', 'LGALS8', 'LGMN', 'LIG1', 'LIPA', 'LOXL1', 'LPAR2', 'LPGAT1', 'LRP10', 'LRPAP1', 'LRRC41', 'LSM5', 'LSM6', 'LSR', 'LYN', 'LYPLA1', 'LYRM1', 'MACF1', 'MALT1', 'MAMLD1', 'MAN2B1', 'MAP2K5', 'MAP3K4', 'MAP4K4', 'MAP7', 'MAPK13', 'MAPK1IP1L', 'MAPK9', 'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MAST2', 'MAT2A', 'MBNL1', 'MBNL2', 'MBOAT7', 'MBTPS1', 'MCM3', 'MCOLN1', 'MCUR1', 'ME2', 'MEF2C', 'MELK', 'MEST', 'METRN', 'MFSD10', 'MICALL1', 'MIF', 'MINDY1', 'MKNK1', 'MLEC', 'MLLT11', 'MMP1', 'MMP2', 'MNAT1', 'MOK', 'MPC2', 'MPZL1', 'MRPL12', 'MRPL19', 'MRPS16', 'MRPS2', 'MSH6', 'MSRA', 'MTA1', 'MTERF3', 'MTF2', 'MTFR1', 'MTHFD2', 'MUC1', 'MVP', 'MYBL2', 'MYC', 'MYCBP', 'MYCBP2', 'MYL9', 'MYLK', 'MYO10', 'NCAPD2', 'NCK1', 'NCK2', 'NCOA3', 'NENF', 'NET1', 'NFATC3', 'NFATC4', 'NFE2L2', 'NFIL3', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NGRN', 'NIPSNAP1', 'NISCH', 'NIT1', 'NMT1', 'NNT', 'NOL3', 'NOLC1', 'NOS3', 'NOSIP', 'NOTCH1', 'NPC1', 'NPDC1', 'NPEPL1', 'NPRL2', 'NR1H2', 'NR2F6', 'NR3C1', 'NRAS', 'NRIP1', 'NSDHL', 'NT5DC2', 'NUCB2', 'NUDCD3', 'NUDT9', 'NUP133', 'NUP62', 'NUP85', 'NUP88', 'NUP93', 'NUSAP1', 'NVL', 'ORC1', 'OXA1L', 'OXCT1', 'OXSR1', 'P4HA2', 'P4HTM', 'PACSIN3', 'PAF1', 'PAFAH1B1', 'PAFAH1B3', 'PAICS', 'PAK1', 'PAK4', 'PAK6', 'PAN2', 'PARP1', 'PARP2', 'PAX8', 'PCBD1', 'PCCB', 'PCK2', 'PCM1', 'PCMT1', 'PCNA', 'PDGFA', 'PDHX', 'PDIA5', 'PDLIM1', 'PDS5A', 'PECR', 'PEX11A', 'PFKL', 'PGAM1', 'PGM1', 'PGRMC1', 'PHGDH', 'PHKA1', 'PHKB', 'PHKG2', 'PIGB', 'PIH1D1', 'PIK3C2B', 'PIK3C3', 'PIK3CA', 'PIK3R3', 'PIK3R4', 'PIN1', 'PIP4K2B', 'PKIG', 'PLA2G15', 'PLA2G4A', 'PLCB3', 'PLEKHJ1', 'PLEKHM1', 'PLK1', 'PLOD3', 'PLP2', 'PLS1', 'PLSCR1', 'PLSCR3', 'PMAIP1', 'PMM2', 'PNKP', 'PNP', 'POLB', 'POLD4', 'POLE2', 'POLG2', 'POLR1C', 'POLR2I', 'POLR2K', 'POP4', 'PPARD', 'PPARG', 'PPIC', 'PPIE', 'PPOX', 'PPP1R13B', 'PPP2R3C', 'PPP2R5A', 'PPP2R5E', 'PRAF2', 'PRCP', 'PRKACA', 'PRKAG2', 'PRKCD', 'PRKCH', 'PRKCQ', 'PRKX', 'PROS1', 'PRPF4', 'PRR15L', 'PRR7', 'PRSS23', 'PRUNE1', 'PSIP1', 'PSMB10', 'PSMB8', 'PSMD10', 'PSMD2', 'PSMD4', 'PSMD9', 'PSME1', 'PSME2', 'PSMF1', 'PSMG1', 'PSRC1', 'PTGS2', 'PTK2', 'PTK2B', 'PTPN1', 'PTPN12', 'PTPN6', 'PTPRC', 'PTPRF', 'PTPRK', 'PUF60', 'PWP1', 'PXMP2', 'PXN', 'PYCR1', 'PYGL', 'RAB11FIP2', 'RAB21', 'RAB27A', 'RAB31', 'RAB4A', 'RAC2', 'RAD51C', 'RAD9A', 'RAE1', 'RAI14', 'RALA', 'RALB', 'RALGDS', 'RAP1GAP', 'RASA1', 'RB1', 'RBKS', 'RBM15B', 'RBM34', 'RBM6', 'REEP5', 'RELB', 'RFC2', 'RFC5', 'RFNG', 'RFX5', 'RGS2', 'RHEB', 'RHOA', 'RNF167', 'RNH1', 'RNMT', 'RNPS1', 'RPA1', 'RPA2', 'RPA3', 'RPIA', 'RPL39L', 'RPN1', 'RPP38', 'RPS5', 'RPS6', 'RPS6KA1', 'RRAGA', 'RRP12', 'RRP1B', 'RRP8', 'RRS1', 'RSU1', 'RTN2', 'RUVBL1', 'RXYLT1', 'S100A13', 'S100A4', 'SACM1L', 'SATB1', 'SCAND1', 'SCARB1', 'SCCPDH', 'SCP2', 'SCRN1', 'SCYL3', 'SDHB', 'SENP6', 'SERPINE1', 'SESN1', 'SFN', 'SGCB', 'SH3BP5', 'SHB', 'SHC1', 'SIRT3', 'SKIV2L', 'SKP1', 'SLC11A2', 'SLC1A4', 'SLC25A13', 'SLC25A14', 'SLC25A4', 'SLC25A46', 'SLC27A3', 'SLC2A6', 'SLC35A1', 'SLC35A3', 'SLC35B1', 'SLC35F2', 'SLC37A4', 'SLC5A6', 'SMAD3', 'SMARCA4', 'SMARCC1', 'SMARCD2', 'SMC1A', 'SMC3', 'SMC4', 'SMNDC1', 'SNAP25', 'SNCA', 'SNX11', 'SNX13', 'SNX6', 'SNX7', 'SOCS2', 'SORBS3', 'SOX2', 'SOX4', 'SPAG4', 'SPAG7', 'SPDEF', 'SPEN', 'SPP1', 'SPR', 'SPRED2', 'SPTAN1', 'SPTLC2', 'SQOR', 'SQSTM1', 'SRC', 'SSBP2', 'ST3GAL5', 'ST6GALNAC2', 'ST7', 'STAMBP', 'STAP2', 'STAT1', 'STAT3', 'STAT5B', 'STIMATE', 'STK10', 'STK25', 'STMN1', 'STUB1', 'STX1A', 'STX4', 'STXBP1', 'STXBP2', 'SUPV3L1', 'SUV39H1', 'SUZ12', 'SYK', 'SYNE2', 'SYNGR3', 'SYPL1', 'TARBP1', 'TATDN2', 'TBC1D31', 'TBC1D9B', 'TBP', 'TBPL1', 'TBX2', 'TBXA2R', 'TCEA2', 'TCEAL4', 'TCERG1', 'TCFL5', 'TCTA', 'TCTN1', 'TENT4A', 'TERF2IP', 'TERT', 'TES', 'TESK1', 'TEX10', 'TFAP2A', 'TFDP1', 'TGFB3', 'TGFBR2', 'THAP11', 'TIAM1', 'TICAM1', 'TIMELESS', 'TIMM17B', 'TIMM22', 'TIMM9', 'TIMP2', 'TIPARP', 'TJP1', 'TLE1', 'TLK2', 'TLR4', 'TM9SF2', 'TM9SF3', 'TMCO1', 'TMED10', 'TMEM109', 'TMEM50A', 'TMEM97', 'TNFRSF21', 'TNIP1', 'TOMM34', 'TOMM70', 'TOP2A', 'TOPBP1', 'TOR1A', 'TP53', 'TP53BP1', 'TP53BP2', 'TPD52L2', 'TPM1', 'TRAK2', 'TRAM2', 'TRAP1', 'TRAPPC3', 'TRAPPC6A', 'TRIB1', 'TRIB3', 'TRIM13', 'TRIM2', 'TSC22D3', 'TSEN2', 'TSKU', 'TSPAN3', 'TSPAN4', 'TSPAN6', 'TSTA3', 'TUBB6', 'TWF2', 'TXLNA', 'TXNDC9', 'TXNL4B', 'TXNRD1', 'UBE2A', 'UBE2C', 'UBE2J1', 'UBE2L6', 'UBE3B', 'UBE3C', 'UBQLN2', 'UBR7', 'UFM1', 'UGDH', 'USP1', 'USP14', 'USP22', 'USP6NL', 'USP7', 'UTP14A', 'VAPB', 'VAT1', 'VAV3', 'VDAC1', 'VGLL4', 'VPS28', 'VPS72', 'WASF3', 'WASHC4', 'WASHC5', 'WDR61', 'WDR7', 'WDTC1', 'WFS1', 'WIPF2', 'WRB', 'XBP1', 'XPNPEP1', 'XPO7', 'YKT6', 'YME1L1', 'YTHDF1', 'ZDHHC6', 'ZFP36', 'ZMIZ1', 'ZMYM2', 'ZNF131', 'ZNF274', 'ZNF318', 'ZNF395', 'ZNF451', 'ZNF586', 'ZNF589', 'ZW10'], 'n_genes': 978}

In [80]:
# save doses and perturbation matrix
inhib_conc_df.to_csv(os.path.join(out_dir, "inhib_conc_annotated.csv"))
ic50_df.to_csv(os.path.join(out_dir, "ic50_annotated.csv"))
# gamma_df.to_csv(os.path.join(out_dir, "gamma_annotated.csv"))
pert_df.to_csv(os.path.join(out_dir, "pert_annotated.csv"))

In [81]:
# save log fold change L1000 data
Data_norm_df.to_csv(os.path.join(out_dir, "L1000_Data_norm_data.csv"))

In [82]:
# save R_global for DPDs
R_global_DPD_df.to_csv(os.path.join(out_dir, "R_global_DPDonly_annotated.csv"))