# 01 Data preparation

Processing xlsx files from data folder into suitable inputs and generate other input files

In [1]:
import pandas as pd
import numpy as np
import os
import pickle

In [2]:
cell_line ='BC3C'
data_dir = f"/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_{cell_line}/"
info_dir = data_dir
out_dir = f"/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_bmra/blca_publication_OUTPUT_bmra_{cell_line}_oct_aug/00_outputs_2020_{cell_line}/"

#os.makedirs(info_dir, exist_ok = True)
os.makedirs(out_dir, exist_ok = True)

## Modules

Load data about modules and drugs.

In [3]:
os.path.join(info_dir, "ALL_DATA_2020_oct25.xlsx")

'/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_LINCS/00_outputs_2020_BC3C/ALL_DATA_2020_oct25.xlsx'

In [4]:
### DATA
### remove whitespaces in names (modules), remove duplicates

modules_df = pd.read_excel(
    os.path.join(info_dir, "ALL_DATA_2020_oct25.xlsx"), sheet_name = "modules", index_col = 0)
# display(modules_df)

selected_modules = modules_df.index.tolist()
print(len(selected_modules), ' - Size after reading')

# remove duplicates
selected_modules = modules_df.index.unique().tolist()
print(len(selected_modules), ' - Size after remove duplicates')

# remove whitespaces in modules' names 
selected_modules = [d.strip() for d in selected_modules]

print('Selected modules list: ', len(selected_modules), selected_modules)

12  - Size after reading
12  - Size after remove duplicates
Selected modules list:  12 ['CDK1_2', 'CDK4_6', 'EGFR', 'PI3K', 'FGFR', 'TOP2A', 'p53', 'Src', 'Estrogen', 'Androgen', 'TGFb', 'SMAD3']

In [5]:
### DATA
### remove whitespaces in names (modules, drugs), remove duplicates
### check the dimensions of the indicator IC50 1 uM = 1000 nM
### copy-paste as values, numbers, no formulas

IC50_df = pd.read_excel(
    os.path.join(info_dir, "ALL_DATA_2020_oct25.xlsx"), sheet_name = "IC50s")
IC50_df.drop(columns=['Unnamed: 3','Unnamed: 4'],inplace=True)

print(len(IC50_df.index), ' - Size after reading')
# display(IC50_df)

# rename
IC50_df = IC50_df.rename(columns = {"IC50, uM": "IC50"})

# manually correcting value IC50, Example  for IOX2 -> 30 nM  
#IC50_df.loc[IC50_df.index == 'IOX2', IC50_df.columns == 'IC50'] = 30/1000

# remove non-selected modules, modules' names with whitespaces or empty
IC50_df = IC50_df[IC50_df.Module.isin(selected_modules)]

print(len(IC50_df.index), ' - Size after remove modules')
# display(IC50_df)

# remove duplicates 
# Considering certain columns is optional. 
# Indexes, including time indexes are ignored.
IC50_df = IC50_df.drop_duplicates()

print(len(IC50_df.index), ' - Size after remove duplicates')
display(IC50_df)

42  - Size after reading
42  - Size after remove modules
42  - Size after remove duplicates

                       Drug    Module       IC50
0           flufenamic-acid  Androgen    3.00000
1                nandrolone  Androgen    9.00000
2               oxandrolone  Androgen  190.30000
3    testosterone-enanthate  Androgen  200.00000
4   testosterone-propionate  Androgen  124.00000
5               JNJ-7706621    CDK1_2    0.02700
6                PHA-793887    CDK1_2    0.18000
7               roscovitine    CDK1_2    2.00000
8                 alvocidib    CDK4_6    0.12000
9               palbociclib    CDK4_6    0.04500
10                 afatinib      EGFR    0.03000
11                erlotinib      EGFR    0.00600
12                gefitinib      EGFR    0.17100
13                lapatinib      EGFR    0.03240
14               vandetanib      EGFR    1.50000
15               dienestrol  Estrogen  200.00000
16      estradiol-cypionate  Estrogen  200.00000
17               raloxifene  Estrogen    0.01710
18                masitinib      FGFR    2.50000
19                sorafenib      FGFR    1.74000
20               KU-0063794      PI3K    0.03000
21                   PI-103      PI3K    0.09000
22                  AMG-232       p53    0.00180
23                  HLI-373       p53    3.00000
24                 nutlin-3       p53    0.54000
25                     RITA       p53    9.75000
26                SAR405838       p53    0.02640
27                AS-605240      PI3K    0.15950
28                 GDC-0349      PI3K    3.00000
29                LY-294002      PI3K    1.36000
30               NVP-BEZ235      PI3K    1.71000
31                taselisib      PI3K    0.00262
32             daunorubicin     TOP2A    0.02000
33               epirubicin     TOP2A    0.17000
34               idarubicin     TOP2A    0.00990
35             mitoxantrone     TOP2A    5.30000
36                 AZD-8055      PI3K    0.27430
37               serdemetan       p53   62.15000
38                ponatinib      FGFR    0.00660
39                dasatinib       Src    0.00240
40                   Agent1      TGFb  200.00000
41                   Agent2     SMAD3   10.00000

In [6]:
modules = IC50_df.Module.unique().tolist()

print('IC50_df  modules list: ', len(modules), modules)
print()
print('Selected modules list: ', len(selected_modules), selected_modules)

### CHECK
print()
print('CHECK: ', len(selected_modules),'=?', len(modules))

n_modules = len(modules)

IC50_df  modules list:  12 ['Androgen', 'CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'TGFb', 'SMAD3']

Selected modules list:  12 ['CDK1_2', 'CDK4_6', 'EGFR', 'PI3K', 'FGFR', 'TOP2A', 'p53', 'Src', 'Estrogen', 'Androgen', 'TGFb', 'SMAD3']

CHECK:  12 =? 12

In [7]:
drugs = IC50_df.Drug.tolist()
print(len(drugs), ' - Size after reading')

# remove duplicates
drugs = IC50_df.Drug.unique().tolist()
print(len(drugs), ' - Size after remove duplicates')

# remove whitespaces in drugs' names (necessary for some)
drugs = [d.strip() for d in drugs]

# remove duplicates after remove whitespaces
drugs = list(set(drugs))
print(len(drugs), ' - Size after remove duplicates without whitespaces')

print('Drugs list: ', len(drugs), drugs)

n_drugs = len(drugs)

42  - Size after reading
42  - Size after remove duplicates
42  - Size after remove duplicates without whitespaces
Drugs list:  42 ['estradiol-cypionate', 'nutlin-3', 'sorafenib', 'NVP-BEZ235', 'AZD-8055', 'idarubicin', 'PI-103', 'Agent1', 'PHA-793887', 'KU-0063794', 'erlotinib', 'GDC-0349', 'Agent2', 'alvocidib', 'SAR405838', 'JNJ-7706621', 'testosterone-propionate', 'HLI-373', 'AMG-232', 'afatinib', 'flufenamic-acid', 'roscovitine', 'AS-605240', 'vandetanib', 'lapatinib', 'dasatinib', 'epirubicin', 'serdemetan', 'RITA', 'nandrolone', 'ponatinib', 'testosterone-enanthate', 'LY-294002', 'daunorubicin', 'palbociclib', 'gefitinib', 'raloxifene', 'taselisib', 'masitinib', 'dienestrol', 'mitoxantrone', 'oxandrolone']

## L1000 meta data

Get sig_id for selected drugs.

In [8]:
sig_info_df = pd.read_excel(os.path.join(data_dir, f"sig_info_2020_{cell_line}.xlsx"), index_col = 0)

display(sig_info_df)

,cell,plate,time,level_3_samples,samples_number,pert_type,pert_drug,targets,targets_number,dose,dose_float
level_5_sig_id,,,,,,,,,,,
ASG002_BC3C_24H:A03,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A03,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A04,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A04,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A05,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A05,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:A06,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A06,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
ASG002_BC3C_24H:J13,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:J13,1,ctl_vehicle,DMSO,DMSO_No_target,0,0 uM,0.00
...,...,...,...,...,...,...,...,...,...,...,...
MOAR012_BC3C_24H:P20,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P20,1,trt_cp,BAY-61-3606,NaN,0,3.33 uM,3.33
MOAR012_BC3C_24H:P21,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P21,1,trt_cp,BAY-61-3606,NaN,0,1.11 uM,1.11
MOAR012_BC3C_24H:P22,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P22,1,trt_cp,ethaverine,NaN,0,10 uM,10.00
MOAR012_BC3C_24H:P23,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P23,1,trt_cp,ethaverine,NaN,0,3.33 uM,3.33
MOAR012_BC3C_24H:P24,BC3C,MOAR012,24 h,MOAR012_BC3C_24H_X1_B36:P24,1,trt_cp,ethaverine,NaN,0,1.11 uM,1.11

In [9]:
# now filtering so only the required drugs are present
sig_info_df = sig_info_df.loc[sig_info_df.pert_drug.isin(drugs)]

# here's what we have now
display(sig_info_df)

,cell,plate,time,level_3_samples,samples_number,pert_type,pert_drug,targets,targets_number,dose,dose_float
level_5_sig_id,,,,,,,,,,,
ASG002_BC3C_24H:A10,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A10,1,trt_cp,taselisib,PIK3CA,1,10 uM,10.00
ASG002_BC3C_24H:A11,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A11,1,trt_cp,taselisib,PIK3CA,1,1.11 uM,1.11
ASG002_BC3C_24H:A19,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A19,1,trt_cp,AS-605240,PIK3CG,1,10 uM,10.00
ASG002_BC3C_24H:A20,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A20,1,trt_cp,AS-605240,PIK3CG,1,1.11 uM,1.11
ASG002_BC3C_24H:A21,BC3C,ASG002,24 h,ASG002_BC3C_24H_X1_B35:A21,1,trt_cp,AS-605240,PIK3CG,1,0.12 uM,0.12
...,...,...,...,...,...,...,...,...,...,...,...
MOAR011_BC3C_24H:C11,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:C11,1,trt_cp,testosterone-enanthate,AR,1,3.33 uM,3.33
MOAR011_BC3C_24H:F07,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F07,1,trt_cp,serdemetan,MDM2,1,10 uM,10.00
MOAR011_BC3C_24H:F08,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F08,1,trt_cp,serdemetan,MDM2,1,3.33 uM,3.33
MOAR011_BC3C_24H:F09,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:F09,1,trt_cp,serdemetan,MDM2,1,1.11 uM,1.11
MOAR011_BC3C_24H:J10,BC3C,MOAR011,24 h,MOAR011_BC3C_24H_X1_B36:J10,1,trt_cp,nandrolone,"AR, CYP19A1, MAOA, MAOB, NISCH",5,10 uM,10.00

In [10]:
#previous removed
#rows_remove = ['ASG002_BC3C_24H:F04', 'ASG002_BC3C_24H:F05','ASG002_BC3C_24H:L02',
#               'ASG002_BC3C_24H:O24','ASG002_B                         C3C_24H:L07','ASG002_BC3C_24H:L09',
#               'MOAR010_BC3C_24H:D02', 'ASG002_BC3C_24H:F01','MOAR010_BC3C_24H:D01',
#               'ASG002_BC3C_24H:N19','ASG002_BC3C_24H:N21','ASG002_BC3C_24H:N24',
#               'ASG002_BC3C_24H:I19','ASG002_BC3C_24H:I21','ASG002_BC3C_24H:L17',
#               'ASG002_BC3C_24H:M23','MOAR008_BC3C_24H:L03','MOAR010_BC3C_24H:L20','MOAR011_BC3C_24H:J10',
#               'MOAR008_BC3C_24H:L08','MOAR009_BC3C_24H:C10','MOAR010_BC3C_24H:A13','MOAR010_BC3C_24H:A14','MOAR011_BC3C_24H:F09',
#               'ASG002_BC3C_24H:G01','ASG002_BC3C_24H:P20']

In [11]:
rows_remove = ['ASG002_BC3C_24H:G01',
 'ASG002_BC3C_24H:F15',
 'ASG002_BC3C_24H:N19',
 'ASG002_BC3C_24H:N22',
 'ASG002_BC3C_24H:F15',
 #'ASG002_BC3C_24H:I08',
 'ASG002_BC3C_24H:I19',
 'ASG002_BC3C_24H:B12',
 'MOAR008_BC3C_24H:L07',
 'MOAR008_BC3C_24H:L09',
 'ASG002_BC3C_24H:F04',
 'ASG002_BC3C_24H:P17',
 'ASG002_BC3C_24H:O24',
 'MOAR010_BC3C_24H:D02',
 'ASG002_BC3C_24H:L18',
 'MOAR008_BC3C_24H:L03',
 'MOAR010_BC3C_24H:L21']

Manually remove  few inhibition from data set, since it does differ from the other data points.

inhib_to_filter = "PF-03758309"
dose_to_filter = 10

id_to_filter = sig_info_df[
    np.logical_and(
        sig_info_df.pert_drug == inhib_to_filter,
        sig_info_df.dose_float == dose_to_filter,
    )
].index.values

print(id_to_filter)

sig_info_df = sig_info_df[~sig_info_df.index.isin(id_to_filter)]
display(sig_info_df)

inhib_to_filter = "roscovitine"
dose_to_filter = 3.33

id_to_filter = sig_info_df[
    np.logical_and(
        sig_info_df.pert_drug == inhib_to_filter,
        sig_info_df.dose_float == dose_to_filter,
    )
].index.values

print(id_to_filter)

sig_info_df = sig_info_df[~sig_info_df.index.isin(id_to_filter)]
display(sig_info_df)

In [12]:
sig_info_df.drop(rows_remove,inplace=True)

In [13]:
exp_ids = sig_info_df.index.unique().tolist()
print('Experiments ids list: ', len(exp_ids))

n_experiments = len(exp_ids)

Experiments ids list:  104

In [14]:
n_experiments = len(exp_ids)
print('Experiments ids list: ', len(exp_ids))

Experiments ids list:  104

Confirm data by checking the drugs of interest against the filtered L1000 meta data.

In [15]:
print(f"Number of drugs of interest:\t{len(drugs)}")
#print(f'Number of drugs in L1000 data:\t{len(sig_info_df.value_counts("drugs"))}')

#sig_info_df.value_counts("drugs")

Number of drugs of interest:	42

## L1000 data

In [16]:
Data_norm_df = pd.read_excel(os.path.join(data_dir, f"Data_norm_2020_{cell_line}.xlsx"), index_col = 0)
display(Data_norm_df)

,AARS,ABCB6,ABCC5,ABCF1,ABCF3,ABHD4,ABHD6,ABL1,ACAA1,ACAT2,...,ZMIZ1,ZMYM2,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZW10
ASG002_BC3C_24H:A03,-0.191254,-0.055246,0.039596,-0.256266,-0.040419,-0.590523,-0.159396,-0.074319,0.457981,0.409608,...,0.543203,0.494266,-0.011923,-0.225931,0.285054,-0.775246,0.166031,-0.024873,0.238723,0.284204
ASG002_BC3C_24H:A04,-0.265754,-0.317496,0.118696,-0.136665,-0.301569,-0.403023,0.124804,-0.036470,0.311931,0.660457,...,-0.565096,-0.088634,0.122977,-0.047931,0.141804,0.129054,-0.028819,-0.028773,-0.253627,-0.752646
ASG002_BC3C_24H:A05,-0.181954,-0.081597,-0.210304,1.559535,-0.019019,-0.457423,0.071404,0.074080,-0.356119,0.498808,...,0.226104,-0.228034,-0.121023,-0.075331,-0.133146,0.355054,0.022831,-0.084073,0.283123,-0.894896
ASG002_BC3C_24H:A06,0.033446,0.042404,-0.150154,-0.093165,0.053180,-0.053823,0.087704,0.167681,-0.601569,0.383308,...,-0.608596,-0.228835,0.072777,0.082970,-0.570996,2.847754,-0.211670,-0.067273,0.081723,0.338704
ASG002_BC3C_24H:J13,0.204446,0.180704,0.089096,-0.054666,0.053381,0.044877,-0.277396,-0.157419,0.535681,-3.933493,...,-0.318397,0.122265,-0.134323,-0.088931,-0.067996,-0.515847,-0.005069,0.067527,0.002223,0.204904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MOAR012_BC3C_24H:P20,0.647151,0.211700,-0.979200,0.597350,-0.375751,0.388300,0.394524,0.120151,-0.166775,-1.129125,...,-1.598475,-0.552750,0.515151,0.120800,0.082675,0.529700,0.383225,-0.207225,2.268450,-1.248500
MOAR012_BC3C_24H:P21,0.171800,0.046300,-0.145550,-0.295150,0.030849,0.420951,0.222075,0.179800,0.274724,-0.423975,...,-1.650575,0.203600,-0.003250,-0.064800,-0.037675,0.076499,0.201825,0.416875,0.287450,-0.971700
MOAR012_BC3C_24H:P22,0.648700,0.058749,-0.031700,0.408249,-0.753950,0.332200,-0.357525,-0.107650,-0.213575,0.074225,...,0.127625,0.031600,0.103250,-0.249600,0.046375,1.486200,0.440325,0.090075,-0.031650,-0.944300
MOAR012_BC3C_24H:P23,0.090499,-0.469300,-0.611800,0.873550,-0.788450,-0.097199,-0.366575,-0.490600,-0.624675,-0.009275,...,0.054676,-0.596050,0.084600,0.444700,0.431375,-0.921501,0.044926,0.716076,-0.000900,-1.106700
MOAR012_BC3C_24H:P24,0.204801,-1.388700,-0.283400,0.744750,-1.431150,-0.518100,-0.002174,-0.096200,1.198824,0.138525,...,-0.123474,-0.486500,0.049901,-0.598100,-0.259925,0.088650,-0.242075,0.195575,-0.038300,-1.149900

In [17]:
Data_norm_df = Data_norm_df[Data_norm_df.index.isin(exp_ids)]

# arrange experiments in same order as in list
Data_norm_df["sort_col"] = Data_norm_df.index.map({val: i for i, val in enumerate(exp_ids)})
Data_norm_df = Data_norm_df.sort_values("sort_col")
Data_norm_df = Data_norm_df.drop("sort_col", axis = 1)

# transpose
Data_norm_df = Data_norm_df.T

display(Data_norm_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:L20,MOAR011_BC3C_24H:C01,MOAR011_BC3C_24H:C02,MOAR011_BC3C_24H:C03,MOAR011_BC3C_24H:C10,MOAR011_BC3C_24H:C11,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09,MOAR011_BC3C_24H:J10
AARS,-0.496854,0.288446,0.189747,-0.016454,0.080746,0.282346,0.326246,0.303046,0.387546,0.434746,...,-0.012317,0.215100,-0.178100,-0.007000,0.024000,0.007400,0.584300,0.114500,-0.268751,0.031399
ABCB6,-0.658596,-0.142196,-0.075397,-0.383796,-0.199996,-0.074197,0.108804,-0.399196,-0.227496,-0.041146,...,-0.661323,0.127850,0.081150,-0.026850,-0.152851,0.122550,0.006950,-0.037150,-0.014150,-0.029350
ABCC5,-0.080204,0.231996,-0.329354,-0.225204,0.278446,0.034696,0.396596,-0.255704,-0.254154,-0.002004,...,-0.051357,0.197500,0.119350,0.212450,-0.177250,0.138650,-0.238750,0.409550,0.221350,0.568950
ABCF1,0.202535,0.602335,0.403335,0.313134,-0.083265,-0.056365,-0.387216,0.097235,0.540634,-0.262666,...,-0.555990,-0.036825,-0.080325,0.059175,0.307175,0.580075,0.142675,0.077875,0.695325,0.322875
ABCF3,-0.520919,-0.192819,0.001032,-0.096419,0.210881,-0.731118,0.095381,0.313481,-0.078018,-0.257669,...,0.447982,-0.378251,0.003950,0.127300,-0.197401,-0.128351,-0.468050,-0.140650,-0.353450,-0.012850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF395,1.796254,1.773154,0.668354,0.825354,0.350654,0.205954,-0.998346,0.235354,0.230653,0.440854,...,-0.050680,0.300250,-0.265350,-0.380850,-0.330950,-1.844650,0.257250,-1.828550,-1.550550,-0.612350
ZNF451,-0.244519,0.116732,0.058081,-0.178169,-0.080619,-0.139119,0.064681,-0.083019,-0.272119,-0.164119,...,-0.083718,-0.324500,0.080550,-0.114950,-0.337650,-0.024950,0.080650,0.119950,0.044250,-0.151550
ZNF586,0.097627,0.061027,-0.337573,0.098427,-0.338173,0.017627,-0.197423,-0.078473,-0.300473,-0.147773,...,-0.123664,-0.304650,-0.259400,0.163600,-0.428700,-0.069200,-0.561900,0.202100,0.043000,0.073700
ZNF589,0.608573,0.106123,-0.014126,-0.003677,-0.123477,-0.243377,0.044623,-0.021477,0.201823,-0.413227,...,0.007359,-0.315500,-0.013900,-0.035050,1.836400,-0.223300,-0.557600,-0.364600,-0.531500,-0.343400
ZW10,-0.757496,-0.723196,-1.121396,-1.139496,0.077104,-1.088546,0.193104,0.163504,0.372704,-0.677496,...,0.211432,-0.142150,0.443400,-0.145650,0.433800,0.048100,0.113050,-0.269050,0.245600,0.049950

### Concatenating TGFbRin and SMAD3in LFC2

In [18]:
files_path ='/home/jing/Phd_project/project_UCD_blca/blca_publication_OUTPUT/blca_publication_OUTPUT_bc3c_oct'

In [19]:
counts = pd.read_csv(
    '/home/jing/Phd_project/project_UCD_blca/blca_DATA/blca_DATA_bc3c_oct/gene_count.xls',
    sep='\t',   
    header=0,index_col=0
)
display(counts)

,D01,D02,D03,T01,T02,T03,S01,S02,S03,gene_name,gene_chr,gene_start,gene_end,gene_strand,gene_length,gene_biotype,gene_description,tf_family
gene_id,,,,,,,,,,,,,,,,,,
ENSG00000156508,236599,217166,230137,246465,277179,265535,291410,287477,279305,EEF1A1,6,73515750,73523797,-,5948,protein_coding,eukaryotic translation elongation factor 1 alp...,-
ENSG00000186081,173372,151121,162044,168813,186988,177195,144747,149534,158903,KRT5,12,52514575,52520687,-,4292,protein_coding,keratin 5 [Source:HGNC Symbol;Acc:HGNC:6442],-
ENSG00000080824,147634,114075,138470,120147,137207,134926,93481,97859,87311,HSP90AA1,14,102080738,102139699,-,5248,protein_coding,heat shock protein 90 alpha family class A mem...,-
ENSG00000187134,105703,95969,88389,103744,120824,114376,95104,108179,106387,AKR1C1,10,4963253,4983283,+,8765,protein_coding,aldo-keto reductase family 1 member C1 [Source...,-
ENSG00000196139,93872,97803,90777,109018,125059,116421,101868,96017,98182,AKR1C3,10,5035354,5107686,+,4532,protein_coding,aldo-keto reductase family 1 member C3 [Source...,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000275063,0,0,0,0,0,0,0,0,0,AC233755.1,KI270726.1,41444,41876,+,351,protein_coding,immunoglobulin heavy variable 4-38-2-like [Sou...,-
ENSG00000275405,0,0,0,0,0,0,0,0,0,RF00003,KI270713.1,21861,22024,-,164,snRNA,NaN,-
ENSG00000275987,0,0,0,0,0,0,0,0,0,RF00003,KI270713.1,30437,30580,-,144,snRNA,NaN,-
ENSG00000277475,0,0,0,0,0,0,0,0,0,AC213203.2,KI270713.1,31698,32528,-,831,protein_coding,NaN,-
ENSG00000268674,0,0,0,0,0,0,0,0,0,AC213203.1,KI270713.1,35407,35916,+,510,protein_coding,Protein FAM231C [Source:UniProtKB/Swiss-Prot;...,-

In [20]:
tgfb_df = pd.read_csv(os.path.join(files_path,'augmented_Group_T_vs_D_DEGs.csv'),index_col=0)
display(tgfb_df)
smad_df  =pd.read_csv(os.path.join(files_path,'augmented_Group_S_vs_D_DEGs.csv'),index_col=0)
display(smad_df)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
ENSG00000156508,0.201061,0.173573,0.202641,0.176735,0.132901,0.257407,0.111420,0.173126,0.141177,0.082286,0.095872,0.161413,0.241042,0.222366,0.236890,0.192645,0.206299,0.107757,0.130863,0.219968
ENSG00000187134,0.021823,0.300893,0.267662,0.293666,0.201794,0.173898,0.199301,0.058201,0.273452,0.273660,0.123448,0.276374,0.303793,0.257057,0.287959,0.141542,0.255065,0.115740,0.153871,0.211205
ENSG00000196139,0.123042,0.390659,0.411170,0.292168,0.266489,0.189001,0.231022,0.159906,0.412510,0.323906,0.131149,0.397332,0.300021,0.334547,0.263392,0.169997,0.279720,0.150318,0.257796,0.364778
ENSG00000075624,-0.292043,-0.200682,-0.197221,-0.272745,-0.242856,-0.416965,-0.231833,-0.266039,-0.165688,-0.156133,-0.213593,-0.198982,-0.339592,-0.307785,-0.384031,-0.275137,-0.345786,-0.220557,-0.164550,-0.228457
ENSG00000151632,0.096060,0.335307,0.324412,0.254603,0.220380,0.124327,0.173548,0.084769,0.330582,0.275151,0.092567,0.332995,0.250335,0.265957,0.193553,0.124103,0.240624,0.113041,0.189223,0.282659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000143590,1.357461,0.838161,-0.009501,1.151821,0.968775,1.256215,1.248668,1.150430,0.523499,1.075849,0.871366,0.646154,1.186204,2.253030,1.775349,1.269010,1.445227,0.825412,0.077452,0.868504
ENSG00000224186,0.901672,1.283645,1.193499,1.233316,1.230683,1.222674,1.226041,0.627548,1.705221,1.082202,0.116156,1.573791,1.197308,1.650068,0.848380,0.640848,1.695109,0.577007,0.938254,1.156662
ENSG00000267698,0.375276,1.096940,1.222448,1.185693,0.643781,1.137254,1.154811,0.726687,1.413238,1.072395,0.319942,1.108474,1.343758,1.760660,1.252416,0.968138,1.073060,0.480426,1.024734,1.200079
ENSG00000105427,1.479687,0.996351,1.235749,1.190506,0.612649,1.825561,0.772510,1.249845,0.795893,0.564786,0.616805,0.854932,1.707409,1.904058,1.630702,1.535507,1.285501,0.726487,0.909379,1.534727
ENSG00000142303,-3.409422,-5.063597,-3.680588,-4.595817,-4.970700,-2.985522,-4.340321,-2.510572,-5.095903,-5.313280,-2.912222,-5.332142,-3.927450,-5.178173,-3.639434,-2.666930,-5.304884,-3.377381,-2.895661,-3.887291

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
ENSG00000156508,0.267818,0.250431,0.258339,0.181589,0.250753,0.219754,0.259317,0.200100,0.236601,0.227299,0.330536,0.244935,0.227655,0.239768,0.164381,0.246356,0.214813,0.262664,0.294040,0.320645
ENSG00000186081,-0.270659,-0.214579,-0.177583,-0.122605,-0.238233,-0.140340,-0.112750,-0.102218,-0.114194,-0.177293,-0.259021,-0.224725,-0.077319,-0.205527,-0.099922,-0.103619,-0.103381,-0.179374,-0.202944,-0.251690
ENSG00000080824,-0.648882,-0.609840,-0.621077,-0.519491,-0.620831,-0.575570,-0.539669,-0.512242,-0.535387,-0.558118,-0.690562,-0.594507,-0.524116,-0.536778,-0.495778,-0.536145,-0.520466,-0.597496,-0.589405,-0.680019
ENSG00000075624,-0.553327,-0.447304,-0.530273,-0.409481,-0.429479,-0.424402,-0.449047,-0.321024,-0.462650,-0.421495,-0.581068,-0.452151,-0.449315,-0.367896,-0.355937,-0.351615,-0.408055,-0.472188,-0.447125,-0.475379
ENSG00000096384,-0.631544,-0.577096,-0.566570,-0.477981,-0.583133,-0.510339,-0.492897,-0.451967,-0.488453,-0.526770,-0.657332,-0.566211,-0.466472,-0.519741,-0.444723,-0.471725,-0.471840,-0.551671,-0.561901,-0.627111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000053702,-2.002080,-1.689436,-1.561071,0.541366,-2.684528,-2.770834,-1.487364,-2.053640,-1.062125,-1.418561,-2.635171,-3.347576,-1.455604,-2.976164,-0.683174,-2.254330,0.179689,-3.332501,-2.159110,-5.245321
ENSG00000184860,-4.867906,-3.830393,-3.064666,-2.068944,-3.196792,-2.044355,-2.590525,-1.043911,-3.145863,-3.208080,-4.767025,-3.626019,-2.830786,-3.678875,-1.930937,-1.055293,-1.382268,-3.876558,-3.180868,-3.062467
ENSG00000279259,2.519366,3.534411,2.960847,1.804856,1.837106,1.713883,2.482235,2.595317,2.774206,2.618790,5.358544,1.328676,3.249234,0.935202,1.353173,1.983776,2.747092,3.341848,2.344522,3.813338
ENSG00000227359,-4.315378,-2.366259,-2.934172,-1.755826,-2.419720,-1.921446,-2.700961,-0.303094,-2.901534,-2.372890,-3.551570,-3.395520,-2.468915,-3.105285,-1.447017,-0.934478,-1.227321,-3.039423,-2.944456,-2.242576
ENSG00000070190,-4.260890,-1.256867,-4.025285,-1.728621,-2.398642,-2.841781,-1.552983,-0.900025,-1.525282,-1.583152,-3.714136,-3.388690,-1.166637,-0.627617,-0.772196,-0.631645,-1.929629,-2.207229,-1.786865,-3.991384

In [21]:
tgfb_df['symbol']= counts.loc[tgfb_df.index,'gene_name']
display(tgfb_df)
smad_df['symbol']= counts.loc[smad_df.index,'gene_name']
display(smad_df)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V12,V13,V14,V15,V16,V17,V18,V19,V20,symbol
ENSG00000156508,0.201061,0.173573,0.202641,0.176735,0.132901,0.257407,0.111420,0.173126,0.141177,0.082286,...,0.161413,0.241042,0.222366,0.236890,0.192645,0.206299,0.107757,0.130863,0.219968,EEF1A1
ENSG00000187134,0.021823,0.300893,0.267662,0.293666,0.201794,0.173898,0.199301,0.058201,0.273452,0.273660,...,0.276374,0.303793,0.257057,0.287959,0.141542,0.255065,0.115740,0.153871,0.211205,AKR1C1
ENSG00000196139,0.123042,0.390659,0.411170,0.292168,0.266489,0.189001,0.231022,0.159906,0.412510,0.323906,...,0.397332,0.300021,0.334547,0.263392,0.169997,0.279720,0.150318,0.257796,0.364778,AKR1C3
ENSG00000075624,-0.292043,-0.200682,-0.197221,-0.272745,-0.242856,-0.416965,-0.231833,-0.266039,-0.165688,-0.156133,...,-0.198982,-0.339592,-0.307785,-0.384031,-0.275137,-0.345786,-0.220557,-0.164550,-0.228457,ACTB
ENSG00000151632,0.096060,0.335307,0.324412,0.254603,0.220380,0.124327,0.173548,0.084769,0.330582,0.275151,...,0.332995,0.250335,0.265957,0.193553,0.124103,0.240624,0.113041,0.189223,0.282659,AKR1C2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000143590,1.357461,0.838161,-0.009501,1.151821,0.968775,1.256215,1.248668,1.150430,0.523499,1.075849,...,0.646154,1.186204,2.253030,1.775349,1.269010,1.445227,0.825412,0.077452,0.868504,EFNA3
ENSG00000224186,0.901672,1.283645,1.193499,1.233316,1.230683,1.222674,1.226041,0.627548,1.705221,1.082202,...,1.573791,1.197308,1.650068,0.848380,0.640848,1.695109,0.577007,0.938254,1.156662,C5orf66
ENSG00000267698,0.375276,1.096940,1.222448,1.185693,0.643781,1.137254,1.154811,0.726687,1.413238,1.072395,...,1.108474,1.343758,1.760660,1.252416,0.968138,1.073060,0.480426,1.024734,1.200079,AC002116.2
ENSG00000105427,1.479687,0.996351,1.235749,1.190506,0.612649,1.825561,0.772510,1.249845,0.795893,0.564786,...,0.854932,1.707409,1.904058,1.630702,1.535507,1.285501,0.726487,0.909379,1.534727,CNFN
ENSG00000142303,-3.409422,-5.063597,-3.680588,-4.595817,-4.970700,-2.985522,-4.340321,-2.510572,-5.095903,-5.313280,...,-5.332142,-3.927450,-5.178173,-3.639434,-2.666930,-5.304884,-3.377381,-2.895661,-3.887291,ADAMTS10

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V12,V13,V14,V15,V16,V17,V18,V19,V20,symbol
ENSG00000156508,0.267818,0.250431,0.258339,0.181589,0.250753,0.219754,0.259317,0.200100,0.236601,0.227299,...,0.244935,0.227655,0.239768,0.164381,0.246356,0.214813,0.262664,0.294040,0.320645,EEF1A1
ENSG00000186081,-0.270659,-0.214579,-0.177583,-0.122605,-0.238233,-0.140340,-0.112750,-0.102218,-0.114194,-0.177293,...,-0.224725,-0.077319,-0.205527,-0.099922,-0.103619,-0.103381,-0.179374,-0.202944,-0.251690,KRT5
ENSG00000080824,-0.648882,-0.609840,-0.621077,-0.519491,-0.620831,-0.575570,-0.539669,-0.512242,-0.535387,-0.558118,...,-0.594507,-0.524116,-0.536778,-0.495778,-0.536145,-0.520466,-0.597496,-0.589405,-0.680019,HSP90AA1
ENSG00000075624,-0.553327,-0.447304,-0.530273,-0.409481,-0.429479,-0.424402,-0.449047,-0.321024,-0.462650,-0.421495,...,-0.452151,-0.449315,-0.367896,-0.355937,-0.351615,-0.408055,-0.472188,-0.447125,-0.475379,ACTB
ENSG00000096384,-0.631544,-0.577096,-0.566570,-0.477981,-0.583133,-0.510339,-0.492897,-0.451967,-0.488453,-0.526770,...,-0.566211,-0.466472,-0.519741,-0.444723,-0.471725,-0.471840,-0.551671,-0.561901,-0.627111,HSP90AB1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000053702,-2.002080,-1.689436,-1.561071,0.541366,-2.684528,-2.770834,-1.487364,-2.053640,-1.062125,-1.418561,...,-3.347576,-1.455604,-2.976164,-0.683174,-2.254330,0.179689,-3.332501,-2.159110,-5.245321,NRIP2
ENSG00000184860,-4.867906,-3.830393,-3.064666,-2.068944,-3.196792,-2.044355,-2.590525,-1.043911,-3.145863,-3.208080,...,-3.626019,-2.830786,-3.678875,-1.930937,-1.055293,-1.382268,-3.876558,-3.180868,-3.062467,SDR42E1
ENSG00000279259,2.519366,3.534411,2.960847,1.804856,1.837106,1.713883,2.482235,2.595317,2.774206,2.618790,...,1.328676,3.249234,0.935202,1.353173,1.983776,2.747092,3.341848,2.344522,3.813338,AC087741.3
ENSG00000227359,-4.315378,-2.366259,-2.934172,-1.755826,-2.419720,-1.921446,-2.700961,-0.303094,-2.901534,-2.372890,...,-3.395520,-2.468915,-3.105285,-1.447017,-0.934478,-1.227321,-3.039423,-2.944456,-2.242576,AC017074.1
ENSG00000070190,-4.260890,-1.256867,-4.025285,-1.728621,-2.398642,-2.841781,-1.552983,-0.900025,-1.525282,-1.583152,...,-3.388690,-1.166637,-0.627617,-0.772196,-0.631645,-1.929629,-2.207229,-1.786865,-3.991384,DAPP1

In [22]:
tgfb_lfc = tgfb_df.set_index('symbol')
tgfb_lfc = tgfb_lfc.loc[tgfb_lfc.index.intersection(Data_norm_df.index)]
display(tgfb_lfc)
smad_lfc = smad_df.set_index('symbol')
smad_lfc = smad_lfc.loc[smad_lfc.index.intersection(Data_norm_df.index)]
display(smad_lfc)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
HSPA8,-0.530289,-0.477385,-0.436713,-0.528967,-0.493244,-0.606866,-0.485275,-0.472977,-0.449245,-0.440122,-0.418003,-0.477159,-0.571660,-0.600743,-0.589029,-0.499383,-0.602073,-0.443212,-0.396937,-0.483488
SPP1,0.159662,0.146542,0.142407,0.206866,0.105709,0.241887,0.111868,0.092238,0.098278,0.109076,0.085087,0.125302,0.261620,0.233034,0.224159,0.177952,0.220070,0.103411,0.095625,0.151448
TXNRD1,0.227017,0.405422,0.379856,0.314378,0.373750,0.212434,0.329854,0.237377,0.458494,0.408085,0.224692,0.443613,0.271237,0.366149,0.254673,0.193701,0.348133,0.255639,0.297679,0.361113
RPS6,0.065750,0.418455,0.452260,0.357832,0.252752,0.216795,0.212395,0.086446,0.400799,0.339476,0.136190,0.403186,0.386860,0.310118,0.304955,0.177218,0.306467,0.147238,0.265408,0.348292
SQSTM1,0.311035,0.193522,0.174994,0.219349,0.178965,0.306141,0.183410,0.269540,0.142242,0.112636,0.181588,0.163727,0.269911,0.280338,0.293796,0.293321,0.245053,0.182702,0.164228,0.241946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FGFR2,-0.656417,-0.923720,-0.718321,-0.813559,-0.905516,-0.722763,-0.784525,-0.582475,-0.941571,-0.876477,-0.463210,-0.982695,-0.786935,-1.103338,-0.863460,-0.515432,-1.031858,-0.543613,-0.466746,-0.827796
COL1A1,-0.398945,-0.894996,-0.977012,-0.820676,-0.836227,-0.657243,-0.622016,-0.214788,-1.020809,-0.914895,-0.343304,-1.061736,-0.806189,-0.771189,-0.523551,-0.255636,-0.996917,-0.523229,-0.642004,-0.727426
SERPINE1,-0.849420,-1.279898,-1.096244,-1.293849,-1.232850,-1.176774,-1.047198,-0.644365,-1.239111,-1.191251,-0.684917,-1.344047,-1.321566,-1.370653,-1.243274,-0.757512,-1.535370,-0.812538,-0.738066,-1.050789
CHAC1,2.341970,2.874138,2.668303,2.638395,2.607622,2.354635,2.525517,2.198984,2.967931,2.667660,1.906206,2.938006,2.601913,3.067016,2.484619,2.237992,2.823817,2.099446,2.290345,2.765239
KIF5C,-0.575622,-0.928652,-0.440901,-0.735573,-0.446025,-0.392959,-0.710490,-0.743284,-0.727906,-0.636460,-0.298085,-0.649287,-0.754739,-1.438407,-1.074332,-0.910484,-0.578716,-0.205458,-0.266277,-0.949759

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
GAPDH,-0.418152,-0.378634,-0.364679,-0.263892,-0.347446,-0.263073,-0.244382,-0.208759,-0.301027,-0.311857,-0.466722,-0.302955,-0.265909,-0.271792,-0.233447,-0.191365,-0.237988,-0.347047,-0.293119,-0.359380
HSPD1,-0.690897,-0.665134,-0.652550,-0.567147,-0.659815,-0.609033,-0.578545,-0.549631,-0.578327,-0.605370,-0.730267,-0.629661,-0.571679,-0.580900,-0.545108,-0.570301,-0.557540,-0.639824,-0.625826,-0.701300
HSPA8,-0.596020,-0.483657,-0.553548,-0.509347,-0.450671,-0.483620,-0.561689,-0.403153,-0.524346,-0.493066,-0.583500,-0.530125,-0.539842,-0.444983,-0.441469,-0.447797,-0.517435,-0.506071,-0.536500,-0.483699
SPP1,0.183543,0.160707,0.167465,0.152414,0.141925,0.156691,0.175856,0.061337,0.119418,0.116680,0.170852,0.137803,0.149321,0.075414,0.111390,0.155068,0.129231,0.120261,0.168496,0.121010
TXNRD1,-0.369827,-0.405291,-0.334293,-0.257711,-0.399601,-0.312548,-0.209274,-0.234407,-0.237951,-0.291079,-0.404563,-0.292291,-0.228591,-0.259964,-0.261069,-0.255030,-0.199669,-0.325166,-0.274368,-0.379084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CDC42,-0.954408,-1.133006,-1.025483,-0.750016,-1.203452,-0.308864,-0.369969,-0.566596,-0.732181,-0.832729,-1.402006,-0.358399,-0.148742,-0.727734,-0.468275,-0.550377,-0.827254,-0.567495,-0.956274,-0.945379
APOE,1.757115,0.958865,1.180892,0.361918,1.470654,1.152320,0.944884,0.782349,0.704361,1.015152,1.705620,1.908782,0.546101,1.553845,0.355148,0.860957,0.546481,1.397371,1.521237,2.344394
SATB1,1.838739,1.658157,1.726674,0.842176,1.095462,0.900912,0.918231,0.684494,1.300680,1.206626,2.673180,0.971805,1.317559,0.475854,0.570397,0.362617,0.930993,1.660736,0.936688,1.743425
SPDEF,-2.192339,-2.477598,-1.448971,-0.849881,-1.784082,-1.055109,-1.117169,-1.309503,-1.334458,-1.823078,-3.150591,-1.644710,-1.430505,-1.641612,-0.846442,-0.860945,-0.920115,-2.251125,-1.632585,-2.591862
IKZF1,2.532258,2.086759,2.489235,0.768546,1.847149,2.700484,1.752076,1.066432,1.064889,1.193269,3.318253,2.230188,2.070691,0.261644,0.718429,1.667896,0.801357,2.555673,1.495987,3.676369

In [23]:
tgfb_lfc.columns = ['TGFbRin_' + col for col in tgfb_lfc.columns]
smad_lfc.columns = ['SMAD3in_' + col for col in smad_lfc.columns]
display(tgfb_lfc)
display(smad_lfc)

,TGFbRin_V1,TGFbRin_V2,TGFbRin_V3,TGFbRin_V4,TGFbRin_V5,TGFbRin_V6,TGFbRin_V7,TGFbRin_V8,TGFbRin_V9,TGFbRin_V10,TGFbRin_V11,TGFbRin_V12,TGFbRin_V13,TGFbRin_V14,TGFbRin_V15,TGFbRin_V16,TGFbRin_V17,TGFbRin_V18,TGFbRin_V19,TGFbRin_V20
HSPA8,-0.530289,-0.477385,-0.436713,-0.528967,-0.493244,-0.606866,-0.485275,-0.472977,-0.449245,-0.440122,-0.418003,-0.477159,-0.571660,-0.600743,-0.589029,-0.499383,-0.602073,-0.443212,-0.396937,-0.483488
SPP1,0.159662,0.146542,0.142407,0.206866,0.105709,0.241887,0.111868,0.092238,0.098278,0.109076,0.085087,0.125302,0.261620,0.233034,0.224159,0.177952,0.220070,0.103411,0.095625,0.151448
TXNRD1,0.227017,0.405422,0.379856,0.314378,0.373750,0.212434,0.329854,0.237377,0.458494,0.408085,0.224692,0.443613,0.271237,0.366149,0.254673,0.193701,0.348133,0.255639,0.297679,0.361113
RPS6,0.065750,0.418455,0.452260,0.357832,0.252752,0.216795,0.212395,0.086446,0.400799,0.339476,0.136190,0.403186,0.386860,0.310118,0.304955,0.177218,0.306467,0.147238,0.265408,0.348292
SQSTM1,0.311035,0.193522,0.174994,0.219349,0.178965,0.306141,0.183410,0.269540,0.142242,0.112636,0.181588,0.163727,0.269911,0.280338,0.293796,0.293321,0.245053,0.182702,0.164228,0.241946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FGFR2,-0.656417,-0.923720,-0.718321,-0.813559,-0.905516,-0.722763,-0.784525,-0.582475,-0.941571,-0.876477,-0.463210,-0.982695,-0.786935,-1.103338,-0.863460,-0.515432,-1.031858,-0.543613,-0.466746,-0.827796
COL1A1,-0.398945,-0.894996,-0.977012,-0.820676,-0.836227,-0.657243,-0.622016,-0.214788,-1.020809,-0.914895,-0.343304,-1.061736,-0.806189,-0.771189,-0.523551,-0.255636,-0.996917,-0.523229,-0.642004,-0.727426
SERPINE1,-0.849420,-1.279898,-1.096244,-1.293849,-1.232850,-1.176774,-1.047198,-0.644365,-1.239111,-1.191251,-0.684917,-1.344047,-1.321566,-1.370653,-1.243274,-0.757512,-1.535370,-0.812538,-0.738066,-1.050789
CHAC1,2.341970,2.874138,2.668303,2.638395,2.607622,2.354635,2.525517,2.198984,2.967931,2.667660,1.906206,2.938006,2.601913,3.067016,2.484619,2.237992,2.823817,2.099446,2.290345,2.765239
KIF5C,-0.575622,-0.928652,-0.440901,-0.735573,-0.446025,-0.392959,-0.710490,-0.743284,-0.727906,-0.636460,-0.298085,-0.649287,-0.754739,-1.438407,-1.074332,-0.910484,-0.578716,-0.205458,-0.266277,-0.949759

,SMAD3in_V1,SMAD3in_V2,SMAD3in_V3,SMAD3in_V4,SMAD3in_V5,SMAD3in_V6,SMAD3in_V7,SMAD3in_V8,SMAD3in_V9,SMAD3in_V10,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
GAPDH,-0.418152,-0.378634,-0.364679,-0.263892,-0.347446,-0.263073,-0.244382,-0.208759,-0.301027,-0.311857,-0.466722,-0.302955,-0.265909,-0.271792,-0.233447,-0.191365,-0.237988,-0.347047,-0.293119,-0.359380
HSPD1,-0.690897,-0.665134,-0.652550,-0.567147,-0.659815,-0.609033,-0.578545,-0.549631,-0.578327,-0.605370,-0.730267,-0.629661,-0.571679,-0.580900,-0.545108,-0.570301,-0.557540,-0.639824,-0.625826,-0.701300
HSPA8,-0.596020,-0.483657,-0.553548,-0.509347,-0.450671,-0.483620,-0.561689,-0.403153,-0.524346,-0.493066,-0.583500,-0.530125,-0.539842,-0.444983,-0.441469,-0.447797,-0.517435,-0.506071,-0.536500,-0.483699
SPP1,0.183543,0.160707,0.167465,0.152414,0.141925,0.156691,0.175856,0.061337,0.119418,0.116680,0.170852,0.137803,0.149321,0.075414,0.111390,0.155068,0.129231,0.120261,0.168496,0.121010
TXNRD1,-0.369827,-0.405291,-0.334293,-0.257711,-0.399601,-0.312548,-0.209274,-0.234407,-0.237951,-0.291079,-0.404563,-0.292291,-0.228591,-0.259964,-0.261069,-0.255030,-0.199669,-0.325166,-0.274368,-0.379084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CDC42,-0.954408,-1.133006,-1.025483,-0.750016,-1.203452,-0.308864,-0.369969,-0.566596,-0.732181,-0.832729,-1.402006,-0.358399,-0.148742,-0.727734,-0.468275,-0.550377,-0.827254,-0.567495,-0.956274,-0.945379
APOE,1.757115,0.958865,1.180892,0.361918,1.470654,1.152320,0.944884,0.782349,0.704361,1.015152,1.705620,1.908782,0.546101,1.553845,0.355148,0.860957,0.546481,1.397371,1.521237,2.344394
SATB1,1.838739,1.658157,1.726674,0.842176,1.095462,0.900912,0.918231,0.684494,1.300680,1.206626,2.673180,0.971805,1.317559,0.475854,0.570397,0.362617,0.930993,1.660736,0.936688,1.743425
SPDEF,-2.192339,-2.477598,-1.448971,-0.849881,-1.784082,-1.055109,-1.117169,-1.309503,-1.334458,-1.823078,-3.150591,-1.644710,-1.430505,-1.641612,-0.846442,-0.860945,-0.920115,-2.251125,-1.632585,-2.591862
IKZF1,2.532258,2.086759,2.489235,0.768546,1.847149,2.700484,1.752076,1.066432,1.064889,1.193269,3.318253,2.230188,2.070691,0.261644,0.718429,1.667896,0.801357,2.555673,1.495987,3.676369

In [24]:
Data_norm_df[tgfb_lfc.columns] = 0
Data_norm_df[smad_lfc.columns] = 0

In [25]:
common_idx = Data_norm_df.index.intersection(tgfb_lfc.index)
Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]

/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 5.28251709e-01  2.06263668e-01  1.01446107e-02  3.36793362e-01
  3.45504087e-01 -2.44635057e-01 -8.50516973e-02 -3.17276999e-01
 -7.17139948e-01  1.61261127e-01 -1.96195405e-01 -1.91874850e-01
 -4.49587839e-01  3.78476943e-01 -9.20940423e-02  3.06889987e-01
 -1.59735062e-01 -2.58191709e-01  3.04920285e-01 -3.18172339e-01
 -5.89846350e-02 -1.98023268e-01 -2.62904916e-01 -2.02040768e-01
  1.55948464e-01 -2.14846524e-01  2.95102511e-01 -5.29210430e-01
 -3.44309412e-01 -1.76411990e-01 -7.37473402e-01 -1.77229244e-01
 -1.05339946e-01 -1.56901404e-01  1.62048713e-01 -1.55048147e-02
 -1.73165075e-01  1.57906385e-01  1.20529824e-01  2.00503064e-01
 -2.74975987e-01 -4.22271150e-01 -3.59730476e-02 -3.61780682e-01
  3.20912593e-01 -2.29496093e-01 -9.65260750e-02 -2.31077445e-01
 -2.38106204e-01  4.96045035e-01 -2.60437102e-01  2.34196954e+00
  2.42633726e-01 -2.33820326e-01 -2.14931592e-02 -3.98945088e-01
 -6.17906128e-01 -4.00757363e-02  1.23328936e-01  1.08090251e-01
  8.74124200e-02  3.80659258e-01  1.09831437e-01  3.63266043e-01
 -2.07818975e-01 -3.72625075e-02  1.05439402e+00 -2.13077815e-01
  9.08164769e-02  4.30084547e-01  9.27306450e-02 -1.99372031e-01
 -1.34408419e-01  1.77725941e-01 -7.02302467e-02 -8.85307457e-01
 -2.18438729e-01 -2.11428873e-01  2.19246799e-01  2.52835626e-01
 -2.17326190e-01 -1.70076311e+00 -1.37140304e-01  5.87366440e-01
  4.47483873e-01  1.51817728e-01 -1.58707928e-01 -2.92263931e-01
 -1.58323535e-01 -3.43501559e-01  1.19912937e-02 -3.48996617e-01
 -2.27903780e-01 -6.56416960e-01 -4.44883752e-01  1.44907608e-01
 -2.08137513e-01 -9.88523991e-01 -2.50286178e-01 -5.43436068e-02
  3.23796201e-01  2.21555873e-01  2.90874134e-01  3.51056976e-01
  3.93868593e-01 -2.69787825e-01 -2.34636431e-01 -3.42394577e-02
  2.33214967e-01 -3.06547810e-01 -1.75453440e-01  4.60329466e-01
  3.53659146e-03 -4.85497016e-02  1.82689643e-01  4.65992475e-01
 -8.53218053e-01 -2.00474036e-01 -6.89039409e-01  6.01326384e-01
 -1.32714231e-01 -1.73724219e-01 -4.63113492e-01 -5.30289311e-01
 -1.97382365e-01 -2.23597637e-01  3.56005890e-01 -7.80411658e-01
 -1.31612722e-01 -2.11148436e-02  1.68339236e-01 -4.46158449e-01
  2.09431489e-01  2.22158866e-01 -3.43661055e-01 -5.23925645e-01
 -1.20650628e-01 -4.97458883e-01 -9.54636150e-02 -1.81865291e-01
  2.01328113e-01 -2.44330456e-01 -8.34318851e-02 -2.01263536e-01
 -2.02507760e-01 -5.75622185e-01 -1.31998278e-02 -5.59216343e-01
 -3.21202680e-01 -1.91853985e-01  4.59581347e-01 -9.51042897e-02
 -2.51838742e-01  3.12226391e-01 -1.27158597e-01 -2.33747309e-01
  3.48064448e-01 -2.62249869e-01  1.32396727e-01 -1.52603421e-01
  8.09531494e-02 -3.88492715e-02  6.54325045e-01 -8.46832869e-01
  5.87811307e-02  6.28780048e-02  5.46306218e-01  2.04568972e-01
 -2.15531631e-01  4.23629395e-01 -2.74150000e-01  2.61607764e-01
 -5.88712422e-03 -1.08094902e-01 -4.13969003e-02 -1.90476165e-01
  1.89432878e-01 -3.19042384e-01 -1.13140768e-01  1.25182777e-01
  1.26130661e-01  1.08104009e+00 -2.65280703e-01 -1.13880872e-01
  7.18201109e-01  1.65543098e-01  2.99056574e-01 -2.02120247e-01
  1.99806285e-01 -2.41978667e-01  1.13115803e-01  1.54027749e-01
  3.74653644e-01 -1.74870205e-01  3.41748004e-03 -9.27515142e-02
 -1.67267883e-01 -6.30855225e-02  4.10897178e-01  1.83162715e-01
  1.04553950e-01  2.55980900e-02 -2.23511217e-01 -1.11225793e-01
 -5.56111446e-01  3.76944002e-01 -1.37741908e-01 -4.13444727e-01
  3.60267574e-01 -2.10749019e-01 -5.85565684e-02  1.31989110e-01
  1.44816385e-01  8.70157847e-02  6.70416469e-02  6.57499841e-02
  1.34873047e-01 -3.03307921e-01 -1.12853923e-01  3.34206689e-01
 -2.42330665e-01  2.09638123e-01  8.23478135e-02 -8.49420287e-01
 -2.62121773e-01  3.49364424e-01  1.38812294e-01 -5.90944198e-02
 -2.20853610e-01  5.93478227e-03  9.33462946e-02 -3.79522043e-01
  1.59661768e-01  1.63476256e-01  3.11034613e-01  6.69444511e-01
 -6.80278618e-02  2.13782837e-01  1.08101477e-01 -3.48786660e-01
 -9.30016842e-01  1.99297557e-01  5.22163947e-02 -2.91619360e-01
 -6.71456495e-01 -2.21444568e-02 -1.05457005e-01 -1.43601638e-01
 -1.47027984e-01 -3.56242748e-01 -1.89137506e-01 -5.93640621e-01
 -2.28742966e-01  6.60916709e-02  2.43772412e-01  1.05857216e+00
  3.45294471e-01  5.59256789e-01  2.40423402e-01  8.61268663e-02
 -2.79951146e-01 -3.30742028e-01  2.27017048e-01 -1.35020733e-01
  1.04651723e-01  4.19489149e-01  7.19093810e-04 -1.21789268e-01
  2.45311695e-01  2.69296740e-01 -1.67570814e-01  3.31580878e-01]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]
/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.4646952   0.37965819  0.23954395  0.25570399  0.34681282 -0.41921246
 -0.24019825 -0.27420345 -0.88829476  0.37281795 -0.28322571 -0.30153333
 -0.76998573  0.44309834 -0.32276042  0.2519177  -0.29652034 -0.46278442
  0.24335158 -0.3017262  -0.34449056 -0.19951664 -0.31984381 -0.06655876
  0.57366597 -0.52081996  0.47683256 -0.74879227 -0.60436754 -0.4875987
 -0.99095409 -0.18863772 -0.30583085 -0.1795561   0.14810466 -0.23288584
 -0.12670382  0.22008514  0.43686522  0.50432848 -0.56674467 -0.34394724
 -0.49885167 -0.19971911  0.46375343 -0.08564975 -0.44240482 -0.12073708
 -0.17489781  0.51601097 -0.36578066  2.87413772  0.07814318 -0.36037637
 -0.21807749 -0.89499644 -0.76668176 -0.19906617  0.39008514  0.46713821
  0.19499104  0.39102974  0.27996226  0.19442529 -0.40864748 -0.20925719
  0.95903515 -0.37721937  0.2883872   0.7387344   0.29214846 -0.45438635
 -0.37289822  0.60427803 -0.28271204 -0.4763739  -0.63902466 -0.37736427
  0.43189455  0.30516072 -0.42475392 -1.90739492 -0.23647418  0.89083194
  0.29584668  0.24262198 -0.47626121 -0.37178628 -0.32157904 -0.1575104
  0.35454149 -0.39580668 -0.40547922 -0.9237195  -0.32423086  0.54378926
 -0.43687958 -1.15862795 -0.24675691 -0.27586546  0.69416433  0.38585582
  0.55768077  0.15187608  0.48789766 -0.15722771 -0.43834412 -0.32956116
  0.11107928 -0.60317783 -0.28813945  0.41005517  0.36288644 -0.21434422
  0.28136658  0.36462467 -0.82283387 -0.38611006 -0.89084471  0.71962254
 -0.27046291 -0.46181703 -0.54262842 -0.47738543 -0.35895791 -0.11213444
  0.21866073 -0.80596448 -0.3742141  -0.259011    0.24183011 -0.72305378
  0.52912622  0.44143557 -0.55508401 -0.84478064 -0.32453597 -0.5204528
 -0.27144818 -0.14506588  0.3474953  -0.2762199  -0.23749036 -0.42681346
 -0.11346227 -0.92865163 -0.23923637 -0.54847467 -0.29885558 -0.13462329
  0.37544838 -0.38181484 -0.3979689   0.24688229 -0.28737877 -0.30392857
  0.32023803 -0.15482672  0.26446328 -0.44107247  0.23700078 -0.25960074
  0.84902914 -0.97489394  0.25780913  0.34253541  0.68491652  0.1458815
 -0.0790751   0.34963245 -0.40763017  0.13759114  0.45519008 -0.36640928
 -0.41761354 -0.27737275  0.35359527 -0.55642453 -0.26835056  0.37806997
  0.5635008   0.98524613 -0.37730642 -0.13494018  0.72156345  0.4393144
  0.37669187 -0.50879949  0.32069822 -0.32918234  0.50586811  0.70189701
  0.45874066 -0.42656093  0.34388638 -0.27701652 -0.21760695 -0.50582628
  0.39496892  0.5225394   0.46819316  0.47048887 -0.52288378 -0.29447689
 -0.74677216  0.29395018 -0.40932638 -0.63176179  0.18594183 -0.36039155
 -0.20606883  0.49198061  0.35758529  0.40039116  0.47517891  0.41845488
  0.36156993 -0.19306055 -0.26509108  1.06977381 -0.43789487  0.32659962
  0.36015625 -1.27989784 -0.47717001  0.18673158  0.49199768 -0.38902607
 -0.4099326  -0.23893829  0.21939852 -0.64118383  0.14654192  0.32690242
  0.19352159  0.90250403 -0.19941385  0.45686488  0.38754498 -0.40044403
 -0.89979495  0.43127352  0.31724748 -0.50834669 -0.65407345 -0.23594741
 -0.45373825 -0.33189649 -0.34693116 -0.27748297 -0.20303227 -0.761938
 -0.11166949  0.26096688  0.46235734  1.23276322  0.1772494   0.29475729
  0.41813372  0.49935488 -0.3242351  -0.32164894  0.40542174 -0.10911097
  0.40774514  0.3688781  -0.31420373 -0.37824268  0.21257354  0.13223122
 -0.6009239   0.52135628]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]
/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.46445151  0.31210252  0.2071586   0.23521019  0.3460248  -0.39085409
 -0.21448679 -0.17827181 -0.84532555  0.31753703 -0.19844575 -0.23356287
 -0.72390052  0.337471   -0.25292752  0.00333198 -0.2414048  -0.4803094
  0.07050105 -0.32256281 -0.33673839 -0.24344895 -0.30828936 -0.07002321
  0.69664784 -0.38002636  0.43052439 -0.69647676 -0.52570347 -0.43223811
 -0.94558716 -0.22669933 -0.26495942 -0.14352812  0.07727313 -0.16585369
 -0.12793422  0.12947832  0.44894118  0.3965021  -0.48157547 -0.33056303
 -0.5026669  -0.20135915  0.43654059 -0.08382497 -0.40902481 -0.15178978
 -0.14086115  0.42626975 -0.33105666  2.66830272  0.08267684 -0.34055503
 -0.2780764  -0.97701204 -0.76904321 -0.17178074  0.39061093  0.33204866
  0.16700582  0.41771011  0.32011029  0.22127989 -0.30826546 -0.19594418
  0.93953508 -0.31976517  0.33580763  0.63787533  0.25975007 -0.4090199
 -0.27133132  0.54428588 -0.2604081  -0.57549344 -0.62451851 -0.39898739
  0.35766058  0.32315309 -0.3455787  -1.76938924 -0.33077791  0.84059659
  0.27773916  0.18721961 -0.42070216 -0.29307894 -0.29040496 -0.11164336
  0.30801428 -0.63145765 -0.36229721 -0.7183213  -0.20537239  0.57497133
 -0.40971451 -1.0478149  -0.2022694  -0.28793965  0.73620043  0.37995148
  0.44034143  0.16729934  0.57555667 -0.12602589 -0.30258836 -0.21330489
  0.12643338 -0.54946613 -0.25237385  0.37346242  0.38664439 -0.19522048
  0.31773249  0.35685659 -0.76551578 -0.35818818 -0.85770305  0.71379496
 -0.19639157 -0.45497382 -0.49308901 -0.43671339 -0.29697385 -0.11093047
  0.19335474 -0.76164461 -0.33045366 -0.26581005  0.15046841 -0.64763097
  0.45833604  0.42759501 -0.52371684 -0.78632606 -0.34552543 -0.4407441
 -0.25185755 -0.08262762  0.20955754 -0.20139439 -0.21584869 -0.39105767
 -0.15353099 -0.44090055 -0.19165311 -0.52952642 -0.25687826 -0.14440313
  0.36558109 -0.3557685  -0.3728017   0.20618434 -0.24677734 -0.40563153
  0.24142709 -0.1341485   0.21332038 -0.4127235   0.24095343 -0.25593849
  0.82318565 -0.93787193  0.31085111  0.34085295  0.65619602  0.20004571
 -0.08715287  0.14182171 -0.3524345   0.15543889  0.40777529 -0.32787604
 -0.44776364 -0.17959454  0.31246528 -0.50315838 -0.18635733  0.31162937
  0.48678162  0.96731463 -0.30982217 -0.14284368  0.70840442  0.45680975
  0.22340039 -0.48590459  0.25876233 -0.23378898  0.41761914  0.44472928
  0.41609756 -0.23673246  0.3281693  -0.26941005 -0.20382572 -0.41449394
  0.29940408  0.49381358  0.46071578  0.51467878 -0.47157601 -0.28253972
 -0.70320881  0.34528361 -0.35496521 -0.58480327  0.17053355 -0.36688072
 -0.1791801   0.4750961   0.37844763  0.44655733  0.46255204  0.45225989
  0.33394414 -0.18734424 -0.21465348  1.09626585 -0.40740709  0.30032898
  0.30707253 -1.09624382 -0.40473912  0.13993297  0.31435066 -0.34924649
 -0.36478514 -0.18729553  0.23378866 -0.56274196  0.14240705  0.36134123
  0.17499368  0.78169071 -0.17362138  0.43287622  0.33260052 -0.23407142
 -0.87630767  0.38141554  0.28932752 -0.47847075 -0.61319673 -0.18916963
 -0.39052966 -0.29902145 -0.30635777 -0.26777093 -0.1493046  -0.71657509
 -0.11190804  0.22469748  0.28828895  1.17596503  0.04605464  0.27140177
  0.41204736  0.45038148 -0.25162755 -0.33214688  0.37985554 -0.08584922
  0.38753143  0.3913758  -0.32040415 -0.31562602  0.20666506  0.14146014
 -0.49483021  0.46548565]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]
/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.51360404  0.3526622   0.14178172  0.30032256  0.27473466 -0.36039124
 -0.19915229 -0.3463957  -0.84393879  0.3470322  -0.21801058 -0.27147638
 -0.66915861  0.43630286 -0.25303562  0.27608125 -0.24172936 -0.41924916
  0.39043099 -0.30555476 -0.26621427 -0.21118195 -0.33024148 -0.1200934
  0.47050007 -0.49134788  0.4006384  -0.67615583 -0.52947014 -0.38123858
 -0.91086115 -0.24288506 -0.26187318 -0.2508375   0.12457463 -0.17213391
 -0.17112545  0.17164037  0.37721075  0.39707334 -0.43570876 -0.40323693
 -0.49308082 -0.29144964  0.41664518 -0.13250409 -0.32460215 -0.17647111
 -0.18548699  0.39912165 -0.36448491  2.63839492  0.13261154 -0.32554486
 -0.16648163 -0.82067551 -0.74749202 -0.15431775  0.3036385   0.38128176
  0.14435658  0.41254026  0.23975175  0.25562101 -0.38290784 -0.15502277
  1.0255944  -0.33419691  0.23470929  0.56698123  0.22459503 -0.38786097
 -0.30600112  0.49250658 -0.23913258 -0.74423444 -0.49992603 -0.33830583
  0.40112097  0.33211396 -0.35357216 -1.93822704 -0.22056785  0.83655963
  0.33121115  0.17973991 -0.3792751  -0.40742212 -0.29741525 -0.20764616
  0.25698813 -0.37236994 -0.33542779 -0.81355891 -0.4022378   0.49544762
 -0.41591669 -1.16391264 -0.22145669 -0.25975706  0.77055693  0.36183977
  0.51443479  0.21546937  0.49383567 -0.22490789 -0.4110503  -0.28580122
  0.15483071 -0.52736735 -0.33366883  0.37885764  0.36654158 -0.19140188
  0.2961768   0.38771439 -0.8442104  -0.33945327 -0.83113104  0.65659559
 -0.20729558 -0.33096286 -0.4951075  -0.5289668  -0.30760009 -0.16463854
  0.34029699 -0.82025869 -0.32033952 -0.21572354  0.19687677 -0.65876628
  0.39983874  0.33361635 -0.48860152 -0.75279476 -0.27612417 -0.53495337
 -0.21859151 -0.16855999  0.29403621 -0.30256652 -0.17868848 -0.36990843
 -0.16811207 -0.73557339 -0.1450031  -0.57662917 -0.33774775 -0.20506733
  0.41960523 -0.29962609 -0.35969836  0.26339697 -0.14175439 -0.34027234
  0.36781941 -0.22692365  0.22740131 -0.36332782  0.18453133 -0.23452436
  0.78614172 -0.96198293  0.18709059  0.22031034  0.64864685  0.13961899
 -0.1332405   0.36647501 -0.41843391  0.19816856  0.34445247 -0.28991905
 -0.29694479 -0.2805943   0.28990953 -0.50499811 -0.26192169  0.3026309
  0.46505254  1.03677675 -0.3339276  -0.16252457  0.76754476  0.40973995
  0.33870235 -0.38671001  0.22926418 -0.35889779  0.37624054  0.61646265
  0.34324153 -0.32379515  0.2798623  -0.238206   -0.2191744  -0.36297788
  0.42889714  0.48131837  0.42451502  0.39509079 -0.40181778 -0.2613544
 -0.69528982  0.32203479 -0.33986518 -0.57580588  0.2486918  -0.32700656
 -0.12738314  0.39897842  0.28864246  0.21025759  0.34195604  0.35783232
  0.26073504 -0.2522353  -0.21759136  0.95231426 -0.41313847  0.30454132
  0.26349462 -1.2938487  -0.4023437   0.2514342   0.35677554 -0.25315197
 -0.38219564 -0.20043548  0.19169105 -0.53144017  0.20686618  0.28723116
  0.21934901  0.87806451 -0.15573967  0.39227149  0.27842096 -0.30546673
 -0.94324303  0.35944081  0.25859521 -0.47370458 -0.69845101 -0.18757429
 -0.32760418 -0.28038927 -0.28140826 -0.33325304 -0.25353632 -0.71537631
 -0.16936936  0.19779776  0.35710285  1.17169681  0.30273986  0.38558345
  0.34523269  0.31280141 -0.3413814  -0.31179531  0.31437814 -0.11975717
  0.31860156  0.46471421 -0.21460005 -0.29336885  0.25858084  0.19742893
 -0.51556759  0.46101602]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]
/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.45840656  0.35965569  0.16407016  0.23700318  0.23628087 -0.39706024
 -0.20744805 -0.31221516 -0.85895064  0.25068565 -0.17011284 -0.34486791
 -0.72587872  0.44604904 -0.28481061  0.29422735 -0.26247361 -0.38151896
  0.38135208 -0.29203348 -0.20462924 -0.15646859 -0.3023545  -0.08362149
  0.37098514 -0.49539562  0.45263989 -0.70481478 -0.5293524  -0.40700517
 -0.92826028 -0.13914562 -0.25546666 -0.15928516  0.20481987 -0.19474441
 -0.10212483  0.17807338  0.32256264  0.40652976 -0.56444405 -0.34190759
 -0.38528294 -0.22006956  0.43401744 -0.09744561 -0.37108815 -0.13660575
 -0.14643383  0.39375928 -0.43716705  2.60762225  0.08868561 -0.32965251
 -0.14994596 -0.83622685 -0.71516638 -0.17278952  0.35833887  0.32545466
  0.17812615  0.30891824  0.1931685   0.21013035 -0.36820028 -0.15876519
  0.95125794 -0.34130328  0.17888446  0.62911085  0.24862001 -0.42842592
 -0.25487148  0.4681781  -0.18672998 -0.59240888 -0.57975258 -0.23326894
  0.3941957   0.2878822  -0.41261325 -1.89056797 -0.18727495  0.7460171
  0.30896484  0.24235666 -0.36465306 -0.32252082 -0.31275774 -0.16070433
  0.1993575  -0.30013124 -0.38891195 -0.90551554 -0.46806758  0.48647422
 -0.3997641  -1.05712888 -0.17441226 -0.25821178  0.70369271  0.26963167
  0.60415469  0.1798777   0.4206258  -0.19826416 -0.43439773 -0.30528906
  0.09845817 -0.5013169  -0.27321189  0.33938763  0.28856451 -0.17538947
  0.22833881  0.32867198 -0.80564022 -0.36522223 -0.85728905  0.65394722
 -0.17447791 -0.31751278 -0.58591894 -0.49324428 -0.30486356 -0.14959231
  0.24271149 -0.81191718 -0.28111632 -0.24001296  0.28778933 -0.64134473
  0.40807739  0.38600237 -0.44328042 -0.81501001 -0.24167478 -0.52220714
 -0.2590529  -0.15038616  0.35241975 -0.33563557 -0.21535983 -0.38089845
 -0.16549528 -0.44602499 -0.18709582 -0.51846684 -0.30945804 -0.14544064
  0.37999603 -0.27401568 -0.3844057   0.24282095 -0.12372625 -0.23717619
  0.29909028 -0.16529126  0.27460862 -0.35016735  0.2032407  -0.21764897
  0.81847325 -0.95399918  0.20246157  0.27214787  0.66502407  0.11681744
 -0.1129003   0.44325398 -0.37777139  0.13946211  0.25603151 -0.27599229
 -0.27222971 -0.33424258  0.25692824 -0.50775127 -0.20109012  0.28600396
  0.33642694  0.96301156 -0.38630231 -0.15100541  0.68692621  0.33473284
  0.18995093 -0.50439805  0.31275091 -0.33738584  0.40609343  0.42343105
  0.44579603 -0.43997404  0.26653004 -0.18273752 -0.23332163 -0.43345499
  0.21731813  0.33987279  0.28219817  0.32027435 -0.37634411 -0.24366424
 -0.69202314  0.25191685 -0.33285851 -0.57994006  0.19299568 -0.24526053
 -0.20309718  0.46519985  0.26512914  0.32905728  0.28176417  0.25275173
  0.27894593 -0.1803924  -0.24773055  0.75949229 -0.43452035  0.31376407
  0.27265167 -1.23285012 -0.42105634  0.17907412  0.38015885 -0.25618463
 -0.4190799  -0.20262406  0.16735653 -0.56958994  0.10570921  0.22056942
  0.17896495  0.81905472 -0.18066218  0.38614699  0.33493987 -0.39352151
 -0.89242953  0.41634851  0.25040737 -0.48612847 -0.62869665 -0.17632245
 -0.28561874 -0.29608097 -0.31801469 -0.27692227 -0.2329933  -0.73832191
 -0.11020085  0.21633719  0.35425854  1.16249451  0.23042903  0.28980938
  0.40329155  0.29631352 -0.35996376 -0.30403855  0.37375004 -0.11972536
  0.32601096  0.32673882 -0.22103143 -0.29382036  0.25660603  0.13910279
 -0.58422793  0.45273608]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, tgfb_lfc.columns] = tgfb_lfc.loc[common_idx, tgfb_lfc.columns]
/tmp/ipykernel_3987877/2713876191.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.62440221  0.25244289  0.03630561  0.37639577  0.30521425 -0.22520318
 -0.08790878 -0.40514676 -0.76356914  0.23271514 -0.16203279 -0.21228278
 -0.43664953  0.44760839 -0.05466286  0.23538995 -0.12924989 -0.34994043
  0.40756192 -0.38421211 -0.12369442 -0.32120422 -0.39904637 -0.23383296
  0.35366819 -0.241078    0.3697603  -0.52950042 -0.35200637 -0.17812171

In [26]:
common_idx = Data_norm_df.index.intersection(smad_lfc.index)
Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]

/tmp/ipykernel_3987877/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.80006032 -0.38077041  0.6067599   0.14613308  1.04119834  0.64850065
  0.33453216 -0.3657465  -0.14819256 -0.93501364  0.2000188  -0.20626723
 -0.54663673  0.37336362 -0.33119211 -0.45995065 -0.39305895  0.17315114
  1.80734362  1.34024181  0.32793335  0.54169673  0.40003945  1.75711503
  0.2348163   0.40610619 -0.27040384  0.74169684 -0.37149541 -0.22467869
 -0.89065041 -0.14976776 -0.35416148 -0.35196214 -0.30704198 -1.10837272
 -0.68850645 -0.18754113 -0.25961763  0.44222036  0.71956938  0.31011175
 -0.87380603 -0.25761065 -0.35763975  0.29971468  0.49584234  0.71244868
 -0.12837556 -0.82204431 -0.56970768  0.51936367 -0.25994771 -0.31303677
  0.29745721  0.52000627 -0.43751303  0.81274654 -0.30501018 -0.4858665
 -1.15673013  0.61185731 -0.83667314 -1.04763391 -0.8749282  -0.85027437
 -0.80667006 -1.15082152 -0.50176086 -0.28247085 -0.57403414 -0.89586339
 -0.30154763 -1.27864636 -0.64428637 -0.34732146 -0.95440842 -0.58400207
 -0.56164047  0.42910928 -0.7194021   0.45394428 -0.40140866 -0.21552794
  0.21660092 -0.40331345  0.57083078 -0.40620457 -0.87154168 -0.93037528
  0.42318783 -0.55677381  0.51991449 -0.21498862 -0.62889894 -0.7310395
  0.83344799 -0.38436892 -0.46528423  0.22162629  0.56548572 -0.2879666
 -0.15450754  0.23302806 -0.61538875 -0.89331121  0.50987186  0.63446117
  0.70321349 -0.16774786  0.32471221 -0.25056786 -0.38379283 -0.48411309
 -0.51167024 -0.68777637  0.47633003  0.88099401 -0.34805496 -0.41444802
  1.51419685  0.2910269  -0.71760529  0.29995767 -0.28067722  0.49664637
 -0.35536628 -0.33340661 -0.2413385  -0.44966508 -0.34742168  0.65514237
 -0.15515501 -0.39359499 -0.29369876 -0.55719443  0.72754183 -0.32067279
 -0.71387578 -0.34421475 -0.65133345  0.59417723 -0.76814647 -1.91697024
  0.65747656 -0.38098042  0.16168959 -0.7632737   0.90268032 -0.36226437
  0.77827209  0.41275804 -0.64405918 -0.42535875 -0.71045734  0.13518809
 -0.55650268 -0.41295036 -0.56538223 -0.53872827  0.88577918 -0.42567881
 -0.43090046 -0.28807682  0.85838231  0.31897246  0.26637661 -0.21632547
 -1.12315095 -0.82766375 -0.68913927 -0.31375431  0.58341011 -0.73445097
 -0.47166555 -0.15677545 -0.21379924  1.29547683  1.22290772  0.96166435
  0.36886261 -0.81006161 -0.85387961 -1.1871119  -0.2401783   0.62922691
  0.86680208  0.40595944 -0.31492843  0.50744346 -0.67256484  0.38366318
 -0.41815186  0.47397905  0.73707082  0.63721299 -0.55849735  0.47263805
 -0.49081177 -0.45068031  0.18195014  0.74879301  0.41771788 -0.1786751
 -0.5430082   0.64096438 -0.71133666 -0.31225251 -0.46303779 -0.27645976
 -0.22821213 -0.40210804 -0.57045036  0.81007135  0.4948709   0.23253504
 -1.03575012  0.99647286  1.61112651  0.28649853 -0.64963052  0.68241769
 -0.31198809 -0.43641235 -0.59602028 -0.69089668 -0.32231635  0.52552738
  0.19314204 -0.22711298  0.60796881 -0.31743094  0.73493596 -0.53248104
 -0.79964915  0.28195728  0.3211772   0.91022181  2.532258    0.22494879
 -0.53276114 -0.49982166 -0.27995073  1.69769375 -0.24047415 -0.51080838
 -0.28206341  1.07371611 -0.460241   -0.31179495  0.4608802   0.54341875
  0.38977444  0.52080105 -0.29653071 -0.22272926  0.65384671 -0.33339561
 -0.91778996 -0.2111408  -1.29054925 -0.93478164  0.30076322 -0.62784199
 -0.65753317  0.39963969 -0.3074642  -0.43309201  0.70687333  0.7377968
  0.27786023  0.16097203 -0.40075001 -0.53347244  0.36945323 -0.32444274
  0.35309277 -0.2687524   0.54656124 -0.24678238  0.41918071 -0.59181359
 -0.43087589 -0.53568816 -0.17992484 -0.54931721 -0.46386096  0.27749566
 -2.39635246 -0.48659073 -0.23703151 -0.6712405  -0.20484458 -0.53127669
 -0.3412399  -0.37263312  0.22141131 -0.17980212  1.05136226  0.25722156
 -0.52356672 -1.35643877 -1.18134223  0.78260107  0.64500387 -0.22459746
 -0.71755907  0.80418554  0.4710218  -0.13781126 -0.32107344  0.69813824
  0.53999481 -0.39215783  0.72070946 -0.44353451 -0.18303722  0.32914763
  0.17164109 -0.6694949  -0.4821728   0.24732522  0.81183522  0.715652
 -0.40249091 -0.35127292 -0.55109385 -0.86886966 -0.58357378 -0.83971426
 -0.31077941 -0.52336476 -0.71145402  0.52490292  0.51151939 -0.50301667
 -0.44189499 -0.67016456 -0.3444173   0.29396459 -0.40383193 -0.32912858
  1.51386157 -0.1462138  -0.38845946 -0.26313285  0.82857291  0.17357201
 -0.16108357  0.78066782 -0.33709611  0.48994201 -0.18548486  0.84637851
  0.26582518 -0.57073344  0.33038371  0.37837935 -0.91984055  0.35008438
 -0.26504017 -0.23372037  0.43898518 -1.42578916 -0.38684193 -0.35103443
 -0.43278917 -0.42805825 -0.62739196 -0.41629353 -0.61326218 -0.38814303
 -0.4447628  -0.38735456 -0.4364791   0.48048099  0.52426529  0.32939162
 -0.71915598 -0.16204169  0.63236839  0.47613798 -0.17852488  0.73102265
 -0.41131916 -0.38189302  0.82484482 -0.4850706  -0.22774964  0.49137732
  0.21635493 -0.41373926 -0.4698664  -0.48275075 -0.79930386 -0.64744814
  0.62168446 -0.23886301  0.69007616  0.3362596   0.20808997 -0.61516283
 -0.52835607 -0.40158525  0.7859417  -0.27988758  0.44092763  0.41634757
 -0.50631788  0.52363286 -0.65180043  0.80701024 -0.28007376  0.42093398
 -0.4290547   0.21189755 -0.35746049 -0.47281174 -1.27724438  0.7918108
 -0.49253264 -0.25602181 -0.29296379 -0.35162089  0.33067683 -0.81767305
 -0.55895066 -0.86625121 -0.81108965 -0.50082874  1.83873857  0.25287176
  0.36134852 -0.53201562 -0.13418389 -0.48507031  0.37651687 -0.33315134
  0.76836107  0.3565912   0.39250447  0.28448581  0.62697861 -0.58530492
 -0.20462772 -0.56502919 -0.17330545 -0.29629042 -0.3868664  -0.27603618
 -0.64335139  0.96325689  0.41119468  0.74821012 -0.65469231  0.28732422
 -2.19233894  0.43322592  0.18354273  0.25345175 -0.35795164 -0.21755911
  0.69036499  0.63540615  0.13754378  0.59654199 -0.37021297  0.33806098
  0.25788149 -0.30026738 -0.24329598 -1.28309101  0.47158918  0.65314343
  0.22319372 -0.39501256 -0.61818327  1.10413375  1.36548635 -0.29148678
 -0.64033398 -0.52596999  0.32062153  0.37791436 -0.39910946  0.39407903
  0.53273892 -0.41518692 -0.43191329 -0.41824202 -0.453712   -1.07268551
 -1.06240836 -0.44950575  0.3892222   0.36986823 -0.18350884 -0.37753094
 -0.25019958 -0.66991449  0.16381632  0.41061141 -0.38552137  0.37202201
  0.38811619 -0.62891642 -0.18233203 -0.39643173 -0.36755889 -0.8102038
 -0.22679034 -0.2582321  -0.26007243  0.37635416 -0.73705663 -0.70716273
  1.2188438   0.33447069  0.65388253  0.66163962  1.2353296  -0.36147451
 -0.36906384 -0.39628777 -0.26544208 -0.63053441 -0.36982696 -0.23805516
 -0.96685488  0.32365573  0.7686388   0.209128   -0.45899359 -0.44502292
  0.25882973  0.19679428 -0.38225258 -0.3698888  -0.26953199 -0.29739171
 -0.38154621  0.77757521  0.99630614 -0.43658014 -0.39520264  0.20658216
 -0.54837826  0.49732045  0.2508183   0.35138356  0.75865424 -0.24626907
 -0.13741468  0.41862184  0.33407303 -0.69142026 -0.42177633]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]
/tmp/ipykernel_3987877/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.72335254 -0.27060418  0.54086516  0.11913994  1.03810434  0.66274374
  0.34247537 -0.18842255 -0.11829654 -0.93144919  0.27374193 -0.07310747
 -0.4805432   0.29850472 -0.26315125 -0.4191094  -0.36663469  0.22997872
  1.81136342  1.12840133  0.08849673  0.55860181  0.08858616  0.95886487
  0.28350024  0.4630527  -0.31406311  0.73520501 -0.30588061 -0.1883028
 -0.79712742 -0.0091266  -0.32841942 -0.20164506 -0.25301066 -1.06627093
 -0.6226932  -0.23864557 -0.19249846  0.54964817  0.77002825  0.38752694
 -0.83754687 -0.22347755 -0.24211468  0.37394213  0.54881599  0.7684978
 -0.15250735 -0.79735781 -0.53880534  0.41314402 -0.22200375 -0.20304191
  0.33575039  0.33184812 -0.3729469   0.72852517 -0.42611407 -0.51388042
 -1.10625244  0.689385   -0.78159081 -1.0129503  -0.84886501 -0.76996197
 -0.68538552 -1.08345059 -0.27612098 -0.23820651 -0.61488487 -0.87389555
 -0.15632202 -1.2382144  -0.66318027 -0.37831853 -1.13300575 -0.55060774
 -0.53151954  0.84298498 -0.66982258  0.51459945 -0.32441521 -0.30723087
  0.24993185 -0.32108674  0.35813176 -0.37050092 -0.82082588 -0.90869622
  0.35897536 -0.51735972  0.18593928 -0.19439705 -0.68925309 -0.66218697
  0.7934388  -0.32701523 -0.37301501  0.25016575  0.56090769 -0.26032039
 -0.08929913  0.26879543 -0.60472271 -0.92788716  0.36759015  0.58315272
  0.70014062 -0.1675599   0.33475672 -0.19182794 -0.30429502 -0.39098622
 -0.49190164 -0.63805832  0.41641665  0.83206358 -0.22589615 -0.41215422
  1.37021027  0.34090609 -0.61246034  0.27762789 -0.28659503  0.5330865
 -0.19115469 -0.28584619 -0.35418437 -0.46747962 -0.16567071  0.61054751
  0.0180187  -0.28226053 -0.19000943 -0.53873795  0.73575003 -0.22908048
 -0.69701526 -0.43865113 -0.57364343  0.56413754 -0.74518068 -1.72112876
  0.7208995  -0.39775746  0.12221427 -0.71255367  0.94852665 -0.27281921
  0.72857203  0.40831643 -0.38264361 -0.3200317  -0.57974647  0.00626839
 -0.52840689 -0.38918678 -0.56309407 -0.49469414  0.78922179 -0.42707134
 -0.50671993 -0.23579071  0.83413805  0.22643631  0.35044236 -0.08660325
 -1.04256961 -0.81303636 -0.56171852 -0.32845688  0.53199741 -0.6917304
 -0.36692818 -0.26144513 -0.17995865  1.25761188  1.23718237  0.89623749
  0.37173689 -0.77059228 -0.56743616 -1.16145678 -0.19402878  0.55822712
  1.14110613  0.3953743  -0.22033737  0.44748535 -0.58558383  0.24533947
 -0.37863357  0.30316855  0.66574694  0.60806924 -0.64433588  0.39605633
 -0.48308079 -0.33983432  0.34268649  0.70676636  0.46711781 -0.2194376
 -0.51971294  0.61956905 -0.66520517 -0.30929673 -0.43056302 -0.17590354
 -0.09732245 -0.32491803 -0.54190906  0.73255163  0.47937658  0.28002926
 -0.82959684  1.00141347  1.63196151  0.17500111 -0.66008827  0.77071305
 -0.0874868  -0.34399004 -0.4836565  -0.66513367 -0.21858694  0.45135509
  0.24468973 -0.12937354  0.75060369 -0.23529141  0.56488122 -0.38379794
 -0.7841726   0.31664796  0.02910188  1.02833041  2.08675875  0.33332774
 -0.57219308 -0.43301646 -0.3225914   1.73446646 -0.2502209  -0.53505087
 -0.15651117  1.07180066 -0.32636403 -0.15282268  0.48089241  0.53937884
  0.177341    0.42656325 -0.30355139 -0.22587514  0.57650869 -0.39361651
 -0.88972165 -0.13124944 -1.25851252 -0.89955311  0.35447194 -0.54619818
 -0.66421889  0.34531672 -0.19170236 -0.32805826  0.64208394  0.41217807
  0.29432754  0.21304567 -0.40154786 -0.48268952  0.27788484 -0.3075342
  0.35335816 -0.27184797  0.56001359 -0.17794168  0.22291124 -0.45031015
 -0.34732926 -0.55736719 -0.19089618 -0.56282107 -0.43969694  0.2842801
 -2.4017956  -0.3652337  -0.22567677 -0.6797106  -0.14866827 -0.50834835
 -0.38313191 -0.29397632  0.29464029 -0.23435879  0.86327284  0.25581081
 -0.46076086 -1.31681908 -1.08267553  0.69524381  0.20117192 -0.34080757
 -0.69574701  0.77709829  0.41178738 -0.01026501 -0.2740785   0.64973259
  0.00497867 -0.41315534  0.66279225 -0.42432626 -0.11019998  0.26217008
  0.22095615 -0.64853369 -0.55427731  0.29412057  0.83880363  0.68220709
 -0.3215679  -0.35295092 -0.44507078 -0.81958363 -0.54538682 -0.81664714
 -0.36148829 -0.45017845 -0.63896326  0.5598874   0.52384336 -0.53399351
 -0.2980644  -0.66081763 -0.35323049  0.31595436 -0.37869941 -0.31205581
  1.41439406 -0.13516808 -0.3232065  -0.25639732  0.8182968   0.25807306
 -0.1423715   0.74662037 -0.23291484  0.56338557 -0.05883878  0.74027379
  0.16526012 -0.36606487  0.12091143  0.37141507 -0.48599018  0.29589107
 -0.31174255 -0.24728981  0.34321067 -1.39789097 -0.25844442 -0.30722921
 -0.48115586 -0.37469012 -0.40742497 -0.31269196 -0.71141167 -0.38936515
 -0.31821752 -0.30139614 -0.42148482  0.41552109  0.70648566  0.29696626
 -0.61889471 -0.04618156  0.70731263  0.47699472 -0.03662266  0.63621394
 -0.39874002 -0.39551331  0.91056651 -0.40252226 -0.22811275  0.42069568
  0.08202693 -0.33603507 -0.0762612  -0.38028513 -0.76039869 -0.47018299
  0.53962011 -0.1609916   0.60405698  0.31324513  0.27481762 -0.59886521
 -0.47517911 -0.34567658  0.69639888 -0.22992919  0.23290438  0.44955285
 -0.51657302  0.3213087  -0.59519352  0.75123231 -0.16296131  0.59346669
 -0.3427965   0.26001002 -0.29282075 -0.39111325 -1.28167449  0.78821258
 -0.49047198 -0.24462125 -0.3728449  -0.3530104   0.35453536 -0.76000562
 -0.50847954 -0.8388662  -0.77106736 -0.48195489  1.6581568   0.26837936
  0.41012173 -0.55784937 -0.12237509 -0.50281825  0.31447503 -0.21669332
  0.65232154  0.40060075  0.35337287  0.33083707  0.60627065 -0.40002925
 -0.19086521 -0.57702339 -0.1118639  -0.33708386 -0.37813451 -0.29698703
 -0.63298641  0.96352561  0.32434185  0.71285592 -0.56410197  0.37964055
 -2.47759828  0.23789829  0.16070694  0.15262576 -0.46474757 -0.31188606
  0.6314915   0.58140254  0.18373006  0.3004657  -0.32585748  0.24813526
  0.23583888 -0.25581866 -0.28399222 -0.92796864  0.45418984  0.65641355
  0.28259564 -0.37698907 -0.76328222  0.5453736   1.33175948 -0.27875428
 -0.53084053 -0.52280845  0.26437554  0.34316864 -0.38787165  0.24795375
  0.21478497 -0.49754076 -0.32591614 -0.40239115 -0.44095753 -0.9606388
 -1.08967737 -0.43928912  0.33603404  0.42356639 -0.31487359 -0.29013942
 -0.20816386 -0.54440612  0.23204463  0.44946495 -0.32144376  0.44893207
  0.43573613 -0.53961471 -0.04893838 -0.38650526 -0.36540458 -0.78418149
 -0.22687513 -0.19593196 -0.24698569  0.43680933 -0.68665468 -0.7069126
  1.24135163  0.18953288  0.31477324  0.45113145  1.16074285 -0.35296327
 -0.36509146 -0.4271405  -0.16998501 -0.57447124 -0.40529124 -0.09630049
 -0.95718147  0.29564828  0.68786238  0.14723332 -0.39082847 -0.30811479
  0.34792553  0.13146078 -0.33384668 -0.30772484 -0.28193693 -0.30987893
 -0.34993228  0.71902425  0.90712768 -0.35624536 -0.35419528  0.25129839
 -0.41877534  0.49757772  0.4752921   0.32108866  0.7456354  -0.28182508
 -0.12763909  0.3129133   0.06499953 -0.58446144 -0.35508918]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data_norm_df.loc[common_idx, smad_lfc.columns] = smad_lfc.loc[common_idx, smad_lfc.columns]
/tmp/ipykernel_3987877/1508837703.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 0.77537487 -0.31442553  0.56262093  0.10835197  1.0039888   0.59484648
  0.30054524 -0.28887373 -0.25816145 -0.88024437  0.17613884 -0.15498075
 -0.45177083  0.26231319 -0.20959453 -0.29953972 -0.34523555  0.21838738
  1.73833605  1.3250437   0.30374116  0.51556491  0.20038979  1.18089157
  0.22585974  0.33138281 -0.25886754  0.69576981 -0.41336533 -0.13502606
 -0.77259807 -0.27059716 -0.33218288 -0.39402747 -0.23816384 -1.06722424
 -0.55293746 -0.16469066 -0.28832897  0.43711652  0.68393549  0.28276381
 -0.79508238 -0.17642924 -0.33933156  0.43302483  0.42597293  0.65433174
 -0.24486978 -0.77487017 -0.53307044  0.48970797 -0.2963119  -0.20259415
  0.25108206  0.38993914 -0.43023661  0.7158183  -0.26470115 -0.28503049
 -1.03265685  0.5860109  -0.80877488 -0.98239303 -0.82958819 -0.81400116
 -0.65435968 -1.09748349 -0.44550413 -0.3160452  -0.41026947 -0.86609507
 -0.25855852 -1.21229734 -0.52947808 -0.3163109  -1.02548271 -0.46917885
 -0.48621964  0.46520536 -0.67384514  0.34421067 -0.40118573 -0.27863075
  0.29900453 -0.35535457  0.4872977  -0.41392964 -0.83448889 -0.94950321
  0.33531104 -0.53115219  0.51002248 -0.20435089 -0.58311136 -0.62842264
  0.78344123 -0.28627925 -0.31583975  0.21433644  0.57487509 -0.21212619
 -0.20026883  0.18782681 -0.5307722  -0.75745088  0.4206532   0.57927582
  0.73667108 -0.14385482  0.27196189 -0.16340386 -0.33853674 -0.39485152
 -0.42837773 -0.66563739  0.50242593  0.83392536 -0.32906161 -0.38913967
  1.4698136   0.27608238 -0.69105638  0.25179811 -0.237728    0.49161394
 -0.37154003 -0.30874597 -0.40130326 -0.40694029 -0.33127989  0.64715222
 -0.15938803 -0.30849047 -0.31096436 -0.53895738  0.53407357 -0.29873904
 -0.59200852 -0.23679291 -0.57334983  0.5439192  -0.70818215 -1.86697309
  0.50657326 -0.38666886  0.16677791 -0.60561596  0.88495257 -0.33429703
  0.77031309  0.32742629 -0.62195332 -0.29919572 -0.83865371  0.21098943
 -0.53472779 -0.40238686 -0.51350727 -0.51936894  0.81675256 -0.37060774
 -0.33787375 -0.28387729  0.74917955  0.25439171  0.18102079 -0.19946458
 -1.13448004 -0.49508403 -0.59749468 -0.22990785  0.55804482 -0.72922727
 -0.50343438 -0.30106505 -0.20043241  0.69309558  1.19250976  1.02076356
  0.32665971 -0.73778567 -0.85219965 -1.12648214 -0.22142834  0.54878947
  0.65086389  0.35903937 -0.28066688  0.4426674  -0.61631472  0.44266395
 -0.36467948  0.38114114  0.68623176  0.54777464 -0.58341928  0.56153958
 -0.42619962 -0.3716846   0.13211685  0.72202389  0.34458854 -0.23698685
 -0.49935064  0.59333131 -0.60469104 -0.16060448 -0.45949568 -0.20227433
 -0.15301995 -0.37038081 -0.55596134  0.76032207  0.40638404  0.2456281
 -0.96432011  0.95126058  1.56231592  0.31585459 -0.62470544  0.59236628
 -0.35179708 -0.41999032 -0.55354763 -0.65255034 -0.31374683  0.49504313
  0.18475278 -0.23887985  0.45495891 -0.28472095  0.69534863 -0.50954155
 -0.70783551  0.17523724  0.22923991  0.76157287  2.48923458  0.17322759
 -0.48538736 -0.46216797 -0.22007053  1.63254283 -0.19889902 -0.42915734
 -0.22821686  1.02594603 -0.14774627 -0.2805885   0.41255259  0.50735153
  0.31045807  0.38552256 -0.23165017 -0.20099082  0.44004428 -0.41824521
 -0.90730846 -0.23523198 -1.25100068 -0.89205342  0.25061814 -0.6055653
 -0.61898808  0.3060842  -0.27157566 -0.44195864  0.66393444  0.85383122
  0.2072456   0.13120625 -0.28858867 -0.4002929   0.30549188 -0.40030435
  0.32424339 -0.24438021  0.49011692 -0.22109696  0.36774984 -0.49312211
 -0.3905584  -0.53059193 -0.1252815  -0.49232405 -0.43972585  0.24973473
 -2.34597422 -0.48040462 -0.17957041 -0.55882003 -0.22438111 -0.29716542
 -0.36188122 -0.36472243  0.25648043 -0.15727588  0.75410576  0.24960099
 -0.49015882 -1.28801271 -1.11046502  0.70233261  0.50026539 -0.18917027
 -0.6822733   0.76528681  0.34912661 -0.16223937 -0.34898869  0.66362652
  0.48696941 -0.30806137  0.69315516 -0.35848584 -0.17598209  0.20914308
  0.3130628  -0.63253054 -0.4742456   0.18089236  0.76539457  0.65693457
 -0.41205035 -0.25268451 -0.49872566 -0.83619574 -0.51931551 -0.77095235
 -0.33547472 -0.45992981 -0.67079145  0.48774041  0.45772605 -0.34177878
 -0.36136935 -0.63381757 -0.33348035  0.2310997  -0.34766864 -0.25356665
  1.46078365 -0.23565593 -0.34597975 -0.29832202  0.79185285  0.18384116
 -0.28479773  0.76351532 -0.23553871  0.43440445 -0.24149605  0.82990049
  0.12747677 -0.42144714  0.27914935  0.28810406 -0.91735878  0.27369514
 -0.28657506 -0.27666514  0.39489771 -1.3819702  -0.29478409 -0.22337951
 -0.47151826 -0.28310666 -0.57540625 -0.33791373 -0.52672998 -0.3898663
 -0.30278228 -0.28305555 -0.35898248  0.43372125  0.54449591  0.27247278
 -0.66005545 -0.23068462  0.5187424   0.43909166 -0.20414528  0.66085522
 -0.41010111 -0.39486413  0.73134528 -0.43630828 -0.21750624  0.33807918
  0.31015281 -0.31181706 -0.47947937 -0.37360626 -0.64835426 -0.66213889
  0.56286458 -0.17632089  0.62945065  0.29396822  0.17176798 -0.51065335
 -0.47633163 -0.37547064  0.80258247 -0.27198527  0.36617145  0.38905256
 -0.45700385  0.77600152 -0.56034305  0.72676432 -0.36438401  0.31905246
 -0.39635575  0.17980255 -0.25912333 -0.45491256 -1.14295324  0.71574448
 -0.45708624 -0.20437558 -0.19575263 -0.31279286  0.31690788 -0.75816794
 -0.51196829 -0.74525101 -0.74303781 -0.40719188  1.72667406  0.38873964
  0.2901509  -0.47830457 -0.2523344  -0.34125173  0.39538214 -0.20765517
  0.68344826  0.26198438  0.4527495   0.26694956  0.50960727 -0.5486746
 -0.16686625 -0.5289534  -0.22133141 -0.27174558 -0.36914107 -0.31522565
 -0.64670061  0.92906257  0.2539914   0.68136383 -0.6638999   0.25669868

In [27]:
Data_norm_df

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
AARS,-0.496854,0.288446,0.189747,-0.016454,0.080746,0.282346,0.326246,0.303046,0.387546,0.434746,...,0.846946,0.739186,0.728520,0.661815,0.627668,0.680916,0.700434,0.746670,0.755803,0.789433
ABCB6,-0.658596,-0.142196,-0.075397,-0.383796,-0.199996,-0.074197,0.108804,-0.399196,-0.227496,-0.041146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ABCC5,-0.080204,0.231996,-0.329354,-0.225204,0.278446,0.034696,0.396596,-0.255704,-0.254154,-0.002004,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ABCF1,0.202535,0.602335,0.403335,0.313134,-0.083265,-0.056365,-0.387216,0.097235,0.540634,-0.262666,...,-0.374807,-0.352552,-0.198751,-0.306206,-0.173180,-0.224540,-0.200641,-0.301348,-0.327189,-0.400115
ABCF3,-0.520919,-0.192819,0.001032,-0.096419,0.210881,-0.731118,0.095381,0.313481,-0.078018,-0.257669,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF395,1.796254,1.773154,0.668354,0.825354,0.350654,0.205954,-0.998346,0.235354,0.230653,0.440854,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNF451,-0.244519,0.116732,0.058081,-0.178169,-0.080619,-0.139119,0.064681,-0.083019,-0.272119,-0.164119,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNF586,0.097627,0.061027,-0.337573,0.098427,-0.338173,0.017627,-0.197423,-0.078473,-0.300473,-0.147773,...,-0.796426,-0.374528,-0.369905,-0.345740,-0.201382,-0.056259,-0.226123,-0.499067,-0.395016,-0.387449
ZNF589,0.608573,0.106123,-0.014126,-0.003677,-0.123477,-0.243377,0.044623,-0.021477,0.201823,-0.413227,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZW10,-0.757496,-0.723196,-1.121396,-1.139496,0.077104,-1.088546,0.193104,0.163504,0.372704,-0.677496,...,-0.459066,-0.264433,-0.275769,-0.127617,-0.208151,-0.176909,-0.227164,-0.306851,-0.245169,-0.314552

In [28]:
genes = Data_norm_df.index.tolist()
print('Landmark genes list: ', len(genes), genes)

n_genes = len(genes)

Landmark genes list:  978 ['AARS', 'ABCB6', 'ABCC5', 'ABCF1', 'ABCF3', 'ABHD4', 'ABHD6', 'ABL1', 'ACAA1', 'ACAT2', 'ACBD3', 'ACD', 'ACLY', 'ACOT9', 'ADAM10', 'ADAT1', 'ADGRE5', 'ADGRG1', 'ADH5', 'ADI1', 'ADO', 'ADRB2', 'AGL', 'AKAP8', 'AKAP8L', 'AKR7A2', 'AKT1', 'ALAS1', 'ALDH7A1', 'ALDOA', 'ALDOC', 'AMDHD2', 'ANKRD10', 'ANO10', 'ANXA7', 'APBB2', 'APOE', 'APP', 'APPBP2', 'ARFIP2', 'ARHGAP1', 'ARHGEF12', 'ARHGEF2', 'ARID4B', 'ARID5B', 'ARL4C', 'ARNT2', 'ARPP19', 'ASAH1', 'ASCC3', 'ATF1', 'ATF5', 'ATF6', 'ATG3', 'ATMIN', 'ATP11B', 'ATP1B1', 'ATP2C1', 'ATP6V0B', 'ATP6V1D', 'AURKA', 'AURKB', 'AXIN1', 'B4GAT1', 'BACE2', 'BAD', 'BAG3', 'BAMBI', 'BAX', 'BCL2', 'BCL7B', 'BDH1', 'BECN1', 'BHLHE40', 'BID', 'BIRC2', 'BIRC5', 'BLCAP', 'BLMH', 'BLVRA', 'BMP4', 'BNIP3', 'BNIP3L', 'BPHL', 'BRCA1', 'BTK', 'BUB1B', 'BZW2', 'C2CD2', 'C2CD2L', 'C2CD5', 'C5', 'CAB39', 'CALM3', 'CALU', 'CAMSAP2', 'CANT1', 'CAPN1', 'CARMIL1', 'CASC3', 'CASK', 'CASP10', 'CASP2', 'CASP3', 'CASP7', 'CAST', 'CAT', 'CBLB', 'CBR1', 'CBR3', 'CCDC85B', 'CCDC86', 'CCDC92', 'CCL2', 'CCNA1', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND1', 'CCND3', 'CCNE2', 'CCNF', 'CCNH', 'CCP110', 'CD320', 'CD40', 'CD44', 'CD58', 'CDC20', 'CDC25A', 'CDC25B', 'CDC42', 'CDC45', 'CDCA4', 'CDH3', 'CDK1', 'CDK19', 'CDK2', 'CDK4', 'CDK5R1', 'CDK6', 'CDK7', 'CDKN1A', 'CDKN1B', 'CDKN2A', 'CEBPA', 'CEBPD', 'CEBPZ', 'CEMIP2', 'CENPE', 'CEP57', 'CERK', 'CETN3', 'CFLAR', 'CGRRF1', 'CHAC1', 'CHEK1', 'CHEK2', 'CHERP', 'CHIC2', 'CHMP4A', 'CHMP6', 'CHN1', 'CHP1', 'CIAO3', 'CIAPIN1', 'CIRBP', 'CISD1', 'CLIC4', 'CLPX', 'CLSTN1', 'CLTB', 'CLTC', 'CNDP2', 'CNOT4', 'CNPY3', 'COASY', 'COG2', 'COG4', 'COG7', 'COL1A1', 'COL4A1', 'COPB2', 'COPS7A', 'COQ8A', 'CORO1A', 'CPNE3', 'CPSF4', 'CREB1', 'CREG1', 'CRELD2', 'CRK', 'CRKL', 'CRTAP', 'CRYZ', 'CSK', 'CSNK1A1', 'CSNK1E', 'CSNK2A2', 'CSRP1', 'CTNNAL1', 'CTNND1', 'CTSD', 'CTSL', 'CTTN', 'CXCL2', 'CXCR4', 'CYB561', 'CYCS', 'CYTH1', 'DAG1', 'DAXX', 'DCK', 'DCTD', 'DCUN1D4', 'DDB2', 'DDIT4', 'DDR1', 'DDX10', 'DDX42', 'DECR1', 'DENND2D', 'DERA', 'DFFA', 'DFFB', 'DHDDS', 'DHRS7', 'DHX29', 'DIPK1A', 'DLD', 'DMAC2L', 'DMTF1', 'DNAJA3', 'DNAJB1', 'DNAJB2', 'DNAJB6', 'DNAJC15', 'DNM1', 'DNM1L', 'DNMT1', 'DNMT3A', 'DNTTIP2', 'DPH2', 'DRAP1', 'DSG2', 'DUSP11', 'DUSP14', 'DUSP22', 'DUSP3', 'DUSP4', 'DUSP6', 'DYNLT3', 'DYRK3', 'E2F2', 'EAPP', 'EBNA1BP2', 'EBP', 'ECD', 'ECH1', 'EDEM1', 'EDN1', 'EED', 'EFCAB14', 'EGF', 'EGFR', 'EGR1', 'EIF4EBP1', 'EIF4G1', 'EIF5', 'ELAC2', 'ELAVL1', 'ELOVL6', 'ELP1', 'EML3', 'ENOPH1', 'ENOSF1', 'EPB41L2', 'EPHA3', 'EPHB2', 'EPN2', 'EPRS', 'ERBB2', 'ERBB3', 'ERO1A', 'ETFB', 'ETS1', 'ETV1', 'EVL', 'EXOSC4', 'EXT1', 'EZH2', 'FAH', 'FAIM', 'FAM20B', 'FAM57A', 'FAS', 'FASTKD5', 'FAT1', 'FBXL12', 'FBXO11', 'FBXO21', 'FBXO7', 'FCHO1', 'FDFT1', 'FEZ2', 'FGFR2', 'FGFR4', 'FHL2', 'FIS1', 'FKBP14', 'FKBP4', 'FOS', 'FOSL1', 'FOXJ3', 'FOXO3', 'FOXO4', 'FPGS', 'FRS2', 'FSD1', 'FUT1', 'FYN', 'FZD1', 'FZD7', 'G3BP1', 'GAA', 'GABPB1', 'GADD45A', 'GADD45B', 'GALE', 'GAPDH', 'GATA2', 'GATA3', 'GDPD5', 'GFOD1', 'GFPT1', 'GHR', 'GLI2', 'GLOD4', 'GLRX', 'GMNN', 'GNA11', 'GNA15', 'GNAI1', 'GNAI2', 'GNAS', 'GNB5', 'GNPDA1', 'GOLT1B', 'GPATCH8', 'GPC1', 'GPER1', 'GRB10', 'GRB7', 'GRN', 'GRWD1', 'GSTM2', 'GSTZ1', 'GTF2A2', 'GTF2E2', 'GTPBP8', 'H2AFV', 'HACD3', 'HADH', 'HAT1', 'HDAC2', 'HDAC6', 'HDGFL3', 'HEATR1', 'HEBP1', 'HERC6', 'HERPUD1', 'HES1', 'HIF1A', 'HIST1H2BK', 'HIST2H2BE', 'HK1', 'HLA-DMA', 'HLA-DRA', 'HMG20B', 'HMGA2', 'HMGCR', 'HMGCS1', 'HMOX1', 'HOMER2', 'HOOK2', 'HOXA10', 'HOXA5', 'HPRT1', 'HS2ST1', 'HSD17B10', 'HSD17B11', 'HSPA1A', 'HSPA4', 'HSPA8', 'HSPB1', 'HSPD1', 'HTATSF1', 'HTRA1', 'HYOU1', 'IARS2', 'ICAM1', 'ICAM3', 'ICMT', 'ID2', 'IDE', 'IER3', 'IFNAR1', 'IFRD2', 'IGF1R', 'IGF2BP2', 'IGF2R', 'IGFBP3', 'IGHMBP2', 'IKBKB', 'IKBKE', 'IKZF1', 'IL13RA1', 'IL1B', 'IL4R', 'ILK', 'INPP1', 'INPP4B', 'INSIG1', 'INTS3', 'IPO13', 'IQGAP1', 'ISOC1', 'ITFG1', 'ITGAE', 'ITGB1BP1', 'ITGB5', 'JADE2', 'JMJD6', 'JPT2', 'JUN', 'KAT6A', 'KAT6B', 'KCNK1', 'KCTD5', 'KDELR2', 'KDM3A', 'KDM5A', 'KDM5B', 'KEAP1', 'KHDC4', 'KIAA0100', 'KIAA0355', 'KIAA0753', 'KIF14', 'KIF1BP', 'KIF20A', 'KIF2C', 'KIF5C', 'KIT', 'KLHDC2', 'KLHL21', 'KLHL9', 'KTN1', 'LAGE3', 'LAMA3', 'LAP3', 'LBR', 'LGALS8', 'LGMN', 'LIG1', 'LIPA', 'LOXL1', 'LPAR2', 'LPGAT1', 'LRP10', 'LRPAP1', 'LRRC41', 'LSM5', 'LSM6', 'LSR', 'LYN', 'LYPLA1', 'LYRM1', 'MACF1', 'MALT1', 'MAMLD1', 'MAN2B1', 'MAP2K5', 'MAP3K4', 'MAP4K4', 'MAP7', 'MAPK13', 'MAPK1IP1L', 'MAPK9', 'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MAST2', 'MAT2A', 'MBNL1', 'MBNL2', 'MBOAT7', 'MBTPS1', 'MCM3', 'MCOLN1', 'MCUR1', 'ME2', 'MEF2C', 'MELK', 'MEST', 'METRN', 'MFSD10', 'MICALL1', 'MIF', 'MINDY1', 'MKNK1', 'MLEC', 'MLLT11', 'MMP1', 'MMP2', 'MNAT1', 'MOK', 'MPC2', 'MPZL1', 'MRPL12', 'MRPL19', 'MRPS16', 'MRPS2', 'MSH6', 'MSRA', 'MTA1', 'MTERF3', 'MTF2', 'MTFR1', 'MTHFD2', 'MUC1', 'MVP', 'MYBL2', 'MYC', 'MYCBP', 'MYCBP2', 'MYL9', 'MYLK', 'MYO10', 'NCAPD2', 'NCK1', 'NCK2', 'NCOA3', 'NENF', 'NET1', 'NFATC3', 'NFATC4', 'NFE2L2', 'NFIL3', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NGRN', 'NIPSNAP1', 'NISCH', 'NIT1', 'NMT1', 'NNT', 'NOL3', 'NOLC1', 'NOS3', 'NOSIP', 'NOTCH1', 'NPC1', 'NPDC1', 'NPEPL1', 'NPRL2', 'NR1H2', 'NR2F6', 'NR3C1', 'NRAS', 'NRIP1', 'NSDHL', 'NT5DC2', 'NUCB2', 'NUDCD3', 'NUDT9', 'NUP133', 'NUP62', 'NUP85', 'NUP88', 'NUP93', 'NUSAP1', 'NVL', 'ORC1', 'OXA1L', 'OXCT1', 'OXSR1', 'P4HA2', 'P4HTM', 'PACSIN3', 'PAF1', 'PAFAH1B1', 'PAFAH1B3', 'PAICS', 'PAK1', 'PAK4', 'PAK6', 'PAN2', 'PARP1', 'PARP2', 'PAX8', 'PCBD1', 'PCCB', 'PCK2', 'PCM1', 'PCMT1', 'PCNA', 'PDGFA', 'PDHX', 'PDIA5', 'PDLIM1', 'PDS5A', 'PECR', 'PEX11A', 'PFKL', 'PGAM1', 'PGM1', 'PGRMC1', 'PHGDH', 'PHKA1', 'PHKB', 'PHKG2', 'PIGB', 'PIH1D1', 'PIK3C2B', 'PIK3C3', 'PIK3CA', 'PIK3R3', 'PIK3R4', 'PIN1', 'PIP4K2B', 'PKIG', 'PLA2G15', 'PLA2G4A', 'PLCB3', 'PLEKHJ1', 'PLEKHM1', 'PLK1', 'PLOD3', 'PLP2', 'PLS1', 'PLSCR1', 'PLSCR3', 'PMAIP1', 'PMM2', 'PNKP', 'PNP', 'POLB', 'POLD4', 'POLE2', 'POLG2', 'POLR1C', 'POLR2I', 'POLR2K', 'POP4', 'PPARD', 'PPARG', 'PPIC', 'PPIE', 'PPOX', 'PPP1R13B', 'PPP2R3C', 'PPP2R5A', 'PPP2R5E', 'PRAF2', 'PRCP', 'PRKACA', 'PRKAG2', 'PRKCD', 'PRKCH', 'PRKCQ', 'PRKX', 'PROS1', 'PRPF4', 'PRR15L', 'PRR7', 'PRSS23', 'PRUNE1', 'PSIP1', 'PSMB10', 'PSMB8', 'PSMD10', 'PSMD2', 'PSMD4', 'PSMD9', 'PSME1', 'PSME2', 'PSMF1', 'PSMG1', 'PSRC1', 'PTGS2', 'PTK2', 'PTK2B', 'PTPN1', 'PTPN12', 'PTPN6', 'PTPRC', 'PTPRF', 'PTPRK', 'PUF60', 'PWP1', 'PXMP2', 'PXN', 'PYCR1', 'PYGL', 'RAB11FIP2', 'RAB21', 'RAB27A', 'RAB31', 'RAB4A', 'RAC2', 'RAD51C', 'RAD9A', 'RAE1', 'RAI14', 'RALA', 'RALB', 'RALGDS', 'RAP1GAP', 'RASA1', 'RB1', 'RBKS', 'RBM15B', 'RBM34', 'RBM6', 'REEP5', 'RELB', 'RFC2', 'RFC5', 'RFNG', 'RFX5', 'RGS2', 'RHEB', 'RHOA', 'RNF167', 'RNH1', 'RNMT', 'RNPS1', 'RPA1', 'RPA2', 'RPA3', 'RPIA', 'RPL39L', 'RPN1', 'RPP38', 'RPS5', 'RPS6', 'RPS6KA1', 'RRAGA', 'RRP12', 'RRP1B', 'RRP8', 'RRS1', 'RSU1', 'RTN2', 'RUVBL1', 'RXYLT1', 'S100A13', 'S100A4', 'SACM1L', 'SATB1', 'SCAND1', 'SCARB1', 'SCCPDH', 'SCP2', 'SCRN1', 'SCYL3', 'SDHB', 'SENP6', 'SERPINE1', 'SESN1', 'SFN', 'SGCB', 'SH3BP5', 'SHB', 'SHC1', 'SIRT3', 'SKIV2L', 'SKP1', 'SLC11A2', 'SLC1A4', 'SLC25A13', 'SLC25A14', 'SLC25A4', 'SLC25A46', 'SLC27A3', 'SLC2A6', 'SLC35A1', 'SLC35A3', 'SLC35B1', 'SLC35F2', 'SLC37A4', 'SLC5A6', 'SMAD3', 'SMARCA4', 'SMARCC1', 'SMARCD2', 'SMC1A', 'SMC3', 'SMC4', 'SMNDC1', 'SNAP25', 'SNCA', 'SNX11', 'SNX13', 'SNX6', 'SNX7', 'SOCS2', 'SORBS3', 'SOX2', 'SOX4', 'SPAG4', 'SPAG7', 'SPDEF', 'SPEN', 'SPP1', 'SPR', 'SPRED2', 'SPTAN1', 'SPTLC2', 'SQOR', 'SQSTM1', 'SRC', 'SSBP2', 'ST3GAL5', 'ST6GALNAC2', 'ST7', 'STAMBP', 'STAP2', 'STAT1', 'STAT3', 'STAT5B', 'STIMATE', 'STK10', 'STK25', 'STMN1', 'STUB1', 'STX1A', 'STX4', 'STXBP1', 'STXBP2', 'SUPV3L1', 'SUV39H1', 'SUZ12', 'SYK', 'SYNE2', 'SYNGR3', 'SYPL1', 'TARBP1', 'TATDN2', 'TBC1D31', 'TBC1D9B', 'TBP', 'TBPL1', 'TBX2', 'TBXA2R', 'TCEA2', 'TCEAL4', 'TCERG1', 'TCFL5', 'TCTA', 'TCTN1', 'TENT4A', 'TERF2IP', 'TERT', 'TES', 'TESK1', 'TEX10', 'TFAP2A', 'TFDP1', 'TGFB3', 'TGFBR2', 'THAP11', 'TIAM1', 'TICAM1', 'TIMELESS', 'TIMM17B', 'TIMM22', 'TIMM9', 'TIMP2', 'TIPARP', 'TJP1', 'TLE1', 'TLK2', 'TLR4', 'TM9SF2', 'TM9SF3', 'TMCO1', 'TMED10', 'TMEM109', 'TMEM50A', 'TMEM97', 'TNFRSF21', 'TNIP1', 'TOMM34', 'TOMM70', 'TOP2A', 'TOPBP1', 'TOR1A', 'TP53', 'TP53BP1', 'TP53BP2', 'TPD52L2', 'TPM1', 'TRAK2', 'TRAM2', 'TRAP1', 'TRAPPC3', 'TRAPPC6A', 'TRIB1', 'TRIB3', 'TRIM13', 'TRIM2', 'TSC22D3', 'TSEN2', 'TSKU', 'TSPAN3', 'TSPAN4', 'TSPAN6', 'TSTA3', 'TUBB6', 'TWF2', 'TXLNA', 'TXNDC9', 'TXNL4B', 'TXNRD1', 'UBE2A', 'UBE2C', 'UBE2J1', 'UBE2L6', 'UBE3B', 'UBE3C', 'UBQLN2', 'UBR7', 'UFM1', 'UGDH', 'USP1', 'USP14', 'USP22', 'USP6NL', 'USP7', 'UTP14A', 'VAPB', 'VAT1', 'VAV3', 'VDAC1', 'VGLL4', 'VPS28', 'VPS72', 'WASF3', 'WASHC4', 'WASHC5', 'WDR61', 'WDR7', 'WDTC1', 'WFS1', 'WIPF2', 'WRB', 'XBP1', 'XPNPEP1', 'XPO7', 'YKT6', 'YME1L1', 'YTHDF1', 'ZDHHC6', 'ZFP36', 'ZMIZ1', 'ZMYM2', 'ZNF131', 'ZNF274', 'ZNF318', 'ZNF395', 'ZNF451', 'ZNF586', 'ZNF589', 'ZW10']

## Inhibitor concentrations, IC50, and perturbation matrices

In [29]:
inhib_conc_matrix = np.zeros((n_modules, n_experiments))
ic50_matrix = np.ones((n_modules, n_experiments))
gamma_matrix = np.zeros((n_modules, n_experiments))

In [30]:

for i, module in enumerate(modules):
    drugs_for_module = IC50_df.Drug[IC50_df.Module == module].tolist()
    for drug in drugs_for_module:
        # get IC50 for this drug
        ic50 = IC50_df.IC50[IC50_df.Drug == drug].values
#       gamma = IC50_df.Gamma[IC50_df.Drug == drug].values
        print(drug, ic50)
        assert ic50.size == 1
#       assert gamma.size == 1
        # get experiments with this drug
        exp_with_drug = sig_info_df.index[sig_info_df.pert_drug == drug].tolist()
        print(exp_with_drug) 
        for exp_id in exp_with_drug:
            j = exp_ids.index(exp_id)
            print(j)
            # extract inhibitor concentration
            inhib_conc = sig_info_df.dose_float[sig_info_df.index == exp_id].values
            assert inhib_conc.size == 1
            # insert values in matrices
            inhib_conc_matrix[i, j] = inhib_conc.item()
            ic50_matrix[i, j] = ic50.item()
#           gamma_matrix[i, j] = gamma.item()

flufenamic-acid [3.]
['MOAR008_BC3C_24H:L01', 'MOAR008_BC3C_24H:L02']
76
77
nandrolone [9.]
['MOAR011_BC3C_24H:J10']
103
oxandrolone [190.3]
['MOAR011_BC3C_24H:C01', 'MOAR011_BC3C_24H:C02', 'MOAR011_BC3C_24H:C03']
95
96
97
testosterone-enanthate [200.]
['MOAR011_BC3C_24H:C10', 'MOAR011_BC3C_24H:C11']
98
99
testosterone-propionate [124.]
['MOAR010_BC3C_24H:L19', 'MOAR010_BC3C_24H:L20']
93
94
JNJ-7706621 [0.027]
['ASG002_BC3C_24H:N13', 'ASG002_BC3C_24H:N14', 'ASG002_BC3C_24H:N15']
57
58
59
PHA-793887 [0.18]
['ASG002_BC3C_24H:L01', 'ASG002_BC3C_24H:L02', 'ASG002_BC3C_24H:L03']
46
47
48
roscovitine [2.]
['ASG002_BC3C_24H:E22', 'ASG002_BC3C_24H:E23', 'ASG002_BC3C_24H:E24']
18
19
20
alvocidib [0.12]
['ASG002_BC3C_24H:F05', 'ASG002_BC3C_24H:F06']
24
25
palbociclib [0.045]
['ASG002_BC3C_24H:P16', 'ASG002_BC3C_24H:P18']
72
73
afatinib [0.03]
['ASG002_BC3C_24H:N23', 'ASG002_BC3C_24H:N24']
62
63
erlotinib [0.006]
['ASG002_BC3C_24H:H16', 'ASG002_BC3C_24H:H17', 'ASG002_BC3C_24H:H18']
33
34
35
gefitinib [0.171]
['ASG002_BC3C_24H:F16', 'ASG002_BC3C_24H:F17', 'ASG002_BC3C_24H:F18']
28
29
30
lapatinib [0.0324]
['ASG002_BC3C_24H:I13', 'ASG002_BC3C_24H:I14', 'ASG002_BC3C_24H:I15']
41
42
43
vandetanib [1.5]
['ASG002_BC3C_24H:N20', 'ASG002_BC3C_24H:N21']
60
61
dienestrol [200.]
['ASG002_BC3C_24H:M22', 'ASG002_BC3C_24H:M23', 'ASG002_BC3C_24H:M24']
54
55
56
estradiol-cypionate [200.]
['ASG002_BC3C_24H:L16', 'ASG002_BC3C_24H:L17']
52
53
raloxifene [0.0171]
['ASG002_BC3C_24H:O10', 'ASG002_BC3C_24H:O11', 'ASG002_BC3C_24H:O12']
64
65
66
masitinib [2.5]
['ASG002_BC3C_24H:E19', 'ASG002_BC3C_24H:E20', 'ASG002_BC3C_24H:E21']
15
16
17
sorafenib [1.74]
['ASG002_BC3C_24H:F13', 'ASG002_BC3C_24H:F14']
26
27
ponatinib [0.0066]
['ASG002_BC3C_24H:I20', 'ASG002_BC3C_24H:I21']
44
45
KU-0063794 [0.03]
['ASG002_BC3C_24H:L07', 'ASG002_BC3C_24H:L08', 'ASG002_BC3C_24H:L09']
49
50
51
PI-103 [0.09]
['ASG002_BC3C_24H:O22', 'ASG002_BC3C_24H:O23']
67
68
AS-605240 [0.1595]
['ASG002_BC3C_24H:A19', 'ASG002_BC3C_24H:A20', 'ASG002_BC3C_24H:A21']
2
3
4
GDC-0349 [3.]
['MOAR010_BC3C_24H:D01', 'MOAR010_BC3C_24H:D03']
85
86
LY-294002 [1.36]
['ASG002_BC3C_24H:F01', 'ASG002_BC3C_24H:F02', 'ASG002_BC3C_24H:F03']
21
22
23
NVP-BEZ235 [1.71]
['ASG002_BC3C_24H:C16', 'ASG002_BC3C_24H:C17', 'ASG002_BC3C_24H:C18']
12
13
14
taselisib [0.00262]
['ASG002_BC3C_24H:A10', 'ASG002_BC3C_24H:A11']
0
1
AZD-8055 [0.2743]
[]
AMG-232 [0.0018]
['ASG002_BC3C_24H:B10', 'ASG002_BC3C_24H:B11']
5
6
HLI-373 [3.]
['MOAR008_BC3C_24H:L08']
78
nutlin-3 [0.54]
['ASG002_BC3C_24H:C13', 'ASG002_BC3C_24H:C14', 'ASG002_BC3C_24H:C15', 'MOAR009_BC3C_24H:C10', 'MOAR009_BC3C_24H:C11', 'MOAR009_BC3C_24H:C12']
9
10
11
79
80
81
RITA [9.75]
['ASG002_BC3C_24H:B14', 'ASG002_BC3C_24H:B15', 'MOAR010_BC3C_24H:A13', 'MOAR010_BC3C_24H:A14', 'MOAR010_BC3C_24H:A15']
7
8
82
83
84
SAR405838 [0.0264]
['MOAR010_BC3C_24H:K07', 'MOAR010_BC3C_24H:K08', 'MOAR010_BC3C_24H:K09']
90
91
92
serdemetan [62.15]
['MOAR010_BC3C_24H:J22', 'MOAR010_BC3C_24H:J23', 'MOAR010_BC3C_24H:J24', 'MOAR011_BC3C_24H:F07', 'MOAR011_BC3C_24H:F08', 'MOAR011_BC3C_24H:F09']
87
88
89
100
101
102
daunorubicin [0.02]
['ASG002_BC3C_24H:I05', 'ASG002_BC3C_24H:I06']
36
37
epirubicin [0.17]
['ASG002_BC3C_24H:G02', 'ASG002_BC3C_24H:G03']
31
32
idarubicin [0.0099]
['ASG002_BC3C_24H:P20', 'ASG002_BC3C_24H:P21']
74
75
mitoxantrone [5.3]
['ASG002_BC3C_24H:P07', 'ASG002_BC3C_24H:P08', 'ASG002_BC3C_24H:P09']
69
70
71
dasatinib [0.0024]
['ASG002_BC3C_24H:I07', 'ASG002_BC3C_24H:I08', 'ASG002_BC3C_24H:I09']
38
39
40
Agent1 [200.]
[]
Agent2 [10.]
[]

In [31]:
inhib_conc_matrix

array([[ 0.,  0.,  0., ...,  0.,  0., 10.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [32]:
# transform matrices into pandas dfs for export with row and column names
inhib_conc_df = pd.DataFrame(inhib_conc_matrix, index = modules, columns = exp_ids)
ic50_df = pd.DataFrame(ic50_matrix, index = modules, columns = exp_ids)
# gamma_df = pd.DataFrame(gamma_matrix, index = modules, columns = exp_ids)

# create binary perturbation matrix
pert_df = pd.DataFrame(
    np.where(inhib_conc_matrix != 0, 1, 0),
    index = inhib_conc_df.index,
    columns = inhib_conc_df.columns,
)

In [33]:
display(ic50_df)
# display(gamma_df)
display(inhib_conc_df)
display(pert_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:L20,MOAR011_BC3C_24H:C01,MOAR011_BC3C_24H:C02,MOAR011_BC3C_24H:C03,MOAR011_BC3C_24H:C10,MOAR011_BC3C_24H:C11,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09,MOAR011_BC3C_24H:J10
Androgen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,124.0,190.3,190.3,190.3,200.0,200.0,1.00,1.00,1.00,9.0
CDK1_2,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
CDK4_6,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
EGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
Estrogen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
FGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
PI3K,0.00262,0.00262,0.1595,0.1595,0.1595,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
p53,1.00000,1.00000,1.0000,1.0000,1.0000,0.0018,0.0018,9.75,9.75,0.54,...,1.0,1.0,1.0,1.0,1.0,1.0,62.15,62.15,62.15,1.0
TOP2A,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
Src,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
TGFb,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0
SMAD3,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:L20,MOAR011_BC3C_24H:C01,MOAR011_BC3C_24H:C02,MOAR011_BC3C_24H:C03,MOAR011_BC3C_24H:C10,MOAR011_BC3C_24H:C11,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09,MOAR011_BC3C_24H:J10
Androgen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,3.33,10.0,3.33,1.11,10.0,3.33,0.0,0.00,0.00,10.0
CDK1_2,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
CDK4_6,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
EGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
Estrogen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
FGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
PI3K,10.0,1.11,10.0,1.11,0.12,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
p53,0.0,0.00,0.0,0.00,0.00,10.0,1.11,1.11,0.08,10.0,...,0.00,0.0,0.00,0.00,0.0,0.00,10.0,3.33,1.11,0.0
TOP2A,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
Src,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
TGFb,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0
SMAD3,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,MOAR010_BC3C_24H:L20,MOAR011_BC3C_24H:C01,MOAR011_BC3C_24H:C02,MOAR011_BC3C_24H:C03,MOAR011_BC3C_24H:C10,MOAR011_BC3C_24H:C11,MOAR011_BC3C_24H:F07,MOAR011_BC3C_24H:F08,MOAR011_BC3C_24H:F09,MOAR011_BC3C_24H:J10
Androgen,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,0,0,0,1
CDK1_2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDK4_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
EGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Estrogen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PI3K,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
p53,0,0,0,0,0,1,1,1,1,1,...,0,0,0,0,0,0,1,1,1,0
TOP2A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Src,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGFb,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMAD3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
cols = list(tgfb_lfc.columns) + list(smad_lfc.columns)

ic50_df[cols] = 1.0
inhib_conc_df[cols] = 0.0
pert_df[cols] = 0

In [35]:
ic50_df.loc['TGFb',tgfb_lfc.columns] = 200
ic50_df.loc['SMAD3',smad_lfc.columns] = 7

In [36]:
inhib_conc_df.loc['TGFb',tgfb_lfc.columns] = 15
inhib_conc_df.loc['SMAD3',smad_lfc.columns] = 10

In [37]:
pert_df.loc['TGFb',tgfb_lfc.columns] = 1
pert_df.loc['SMAD3',smad_lfc.columns] = 1

In [38]:
display(ic50_df)
# display(gamma_df)
display(inhib_conc_df)
display(pert_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
Androgen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
CDK1_2,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
CDK4_6,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
EGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Estrogen,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
FGFR,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
PI3K,0.00262,0.00262,0.1595,0.1595,0.1595,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
p53,1.00000,1.00000,1.0000,1.0000,1.0000,0.0018,0.0018,9.75,9.75,0.54,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
TOP2A,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Src,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
TGFb,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
SMAD3,1.00000,1.00000,1.0000,1.0000,1.0000,1.0000,1.0000,1.00,1.00,1.00,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
Androgen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CDK1_2,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CDK4_6,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Estrogen,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
FGFR,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PI3K,10.0,1.11,10.0,1.11,0.12,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
p53,0.0,0.00,0.0,0.00,0.00,10.0,1.11,1.11,0.08,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TOP2A,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Src,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TGFb,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SMAD3,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
Androgen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDK1_2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDK4_6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
EGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Estrogen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGFR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PI3K,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
p53,0,0,0,0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
TOP2A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Src,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGFb,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMAD3,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

## Global responses for DPD modules

According to our discussion, $R$ for DPD vectors can not be calculated with the same formula as for pathway activities. Instead we are assuming:

\begin{equation}
R_{DPD},j = DPD = STV_{DPD} \cdot Data_j
\end{equation}

In [39]:
# load STV data frame
STVs = pd.read_excel(os.path.join(info_dir, "ALL_DATA_2020_oct25.xlsx"), sheet_name = "STV", index_col = 0)
STV_df = pd.DataFrame(np.zeros((len(Data_norm_df.index), 3)), index = Data_norm_df.index, columns = STVs.columns)
STV_df.loc[STVs.index] = STVs

display(STV_df)

        blca_basal_luminal  blca_oncogenesis  blca_survival
AARS                   0.0          0.078487       0.000000
ABCB6                  0.0          0.027125      -2.890931
ABCC5                  0.0          0.002121       0.000000
ABCF1                  0.0         -0.028959      -0.496186
ABCF3                  0.0          0.036671       0.000000
...                    ...               ...            ...
ZNF395                 0.0          0.000000       0.000000
ZNF451                 0.0          0.013403       0.000000
ZNF586                 0.0          0.000000       0.119103
ZNF589                 0.0          0.000000       0.000000
ZW10                   0.0          0.009722       0.000000

[978 rows x 3 columns]

In [40]:
# create empty DPD data frame
DPD_df = pd.DataFrame(
    np.zeros((len(Data_norm_df.columns), len(STV_df.columns))),
    index = Data_norm_df.columns,
    columns = STV_df.columns,
)

# populate
for exp_id in DPD_df.index:
    for state in STV_df.columns:
        DPD_df.loc[exp_id, state] = np.dot(Data_norm_df.T.loc[exp_id], STV_df.loc[:, state])

display(DPD_df)

                     blca_basal_luminal  blca_oncogenesis  blca_survival
ASG002_BC3C_24H:A10          -56.563525         -0.610650     -17.377163
ASG002_BC3C_24H:A11          -51.696023         -0.936049      -5.764659
ASG002_BC3C_24H:A19           -7.483112         -0.048496       9.872480
ASG002_BC3C_24H:A20            3.688500         -0.647673      -0.584775
ASG002_BC3C_24H:A21          -12.723954          0.031650      -6.200738
...                                 ...               ...            ...
SMAD3in_V16                  -46.656824         -0.604149     -12.661158
SMAD3in_V17                  -47.118911         -0.604757     -17.312730
SMAD3in_V18                  -53.112170         -0.868735     -19.128066
SMAD3in_V19                  -52.279880         -0.735904     -16.796479
SMAD3in_V20                  -60.038526         -1.067935     -22.067899

[144 rows x 3 columns]

In [41]:
# transform to R global
R_global_DPD_df = DPD_df.T
display(R_global_DPD_df)

,ASG002_BC3C_24H:A10,ASG002_BC3C_24H:A11,ASG002_BC3C_24H:A19,ASG002_BC3C_24H:A20,ASG002_BC3C_24H:A21,ASG002_BC3C_24H:B10,ASG002_BC3C_24H:B11,ASG002_BC3C_24H:B14,ASG002_BC3C_24H:B15,ASG002_BC3C_24H:C13,...,SMAD3in_V11,SMAD3in_V12,SMAD3in_V13,SMAD3in_V14,SMAD3in_V15,SMAD3in_V16,SMAD3in_V17,SMAD3in_V18,SMAD3in_V19,SMAD3in_V20
blca_basal_luminal,-56.563525,-51.696023,-7.483112,3.688500,-12.723954,-14.104169,4.258746,-26.565452,-5.792472,-15.570078,...,-67.688514,-47.014115,-45.027390,-45.999619,-44.159687,-46.656824,-47.118911,-53.112170,-52.279880,-60.038526
blca_oncogenesis,-0.610650,-0.936049,-0.048496,-0.647673,0.031650,0.185978,0.911126,-0.079387,-0.459741,-0.521443,...,-1.136658,-0.816257,-0.719123,-0.512626,-0.501798,-0.604149,-0.604757,-0.868735,-0.735904,-1.067935
blca_survival,-17.377163,-5.764659,9.872480,-0.584775,-6.200738,1.836483,-3.060844,-3.581400,1.041249,-6.062045,...,-26.074401,-17.264842,-16.611898,-12.734232,-12.923143,-12.661158,-17.312730,-19.128066,-16.796479,-22.067899

## Save outputs

In [42]:
# save metadata as pickle
all_metadata = {
    "modules": modules,
    "n_modules": n_modules,
    "drugs": drugs,
    "n_drugs": n_drugs,
    "exp_ids": exp_ids,
    "n_experiments": n_experiments,
    "genes": genes,
    "n_genes": n_genes,
}

print(all_metadata)

with open(os.path.join(out_dir, "metadata.pickle"), "wb") as f:
    pickle.dump(all_metadata, f, protocol = pickle.HIGHEST_PROTOCOL)

{'modules': ['Androgen', 'CDK1_2', 'CDK4_6', 'EGFR', 'Estrogen', 'FGFR', 'PI3K', 'p53', 'TOP2A', 'Src', 'TGFb', 'SMAD3'], 'n_modules': 12, 'drugs': ['estradiol-cypionate', 'nutlin-3', 'sorafenib', 'NVP-BEZ235', 'AZD-8055', 'idarubicin', 'PI-103', 'Agent1', 'PHA-793887', 'KU-0063794', 'erlotinib', 'GDC-0349', 'Agent2', 'alvocidib', 'SAR405838', 'JNJ-7706621', 'testosterone-propionate', 'HLI-373', 'AMG-232', 'afatinib', 'flufenamic-acid', 'roscovitine', 'AS-605240', 'vandetanib', 'lapatinib', 'dasatinib', 'epirubicin', 'serdemetan', 'RITA', 'nandrolone', 'ponatinib', 'testosterone-enanthate', 'LY-294002', 'daunorubicin', 'palbociclib', 'gefitinib', 'raloxifene', 'taselisib', 'masitinib', 'dienestrol', 'mitoxantrone', 'oxandrolone'], 'n_drugs': 42, 'exp_ids': ['ASG002_BC3C_24H:A10', 'ASG002_BC3C_24H:A11', 'ASG002_BC3C_24H:A19', 'ASG002_BC3C_24H:A20', 'ASG002_BC3C_24H:A21', 'ASG002_BC3C_24H:B10', 'ASG002_BC3C_24H:B11', 'ASG002_BC3C_24H:B14', 'ASG002_BC3C_24H:B15', 'ASG002_BC3C_24H:C13', 'ASG002_BC3C_24H:C14', 'ASG002_BC3C_24H:C15', 'ASG002_BC3C_24H:C16', 'ASG002_BC3C_24H:C17', 'ASG002_BC3C_24H:C18', 'ASG002_BC3C_24H:E19', 'ASG002_BC3C_24H:E20', 'ASG002_BC3C_24H:E21', 'ASG002_BC3C_24H:E22', 'ASG002_BC3C_24H:E23', 'ASG002_BC3C_24H:E24', 'ASG002_BC3C_24H:F01', 'ASG002_BC3C_24H:F02', 'ASG002_BC3C_24H:F03', 'ASG002_BC3C_24H:F05', 'ASG002_BC3C_24H:F06', 'ASG002_BC3C_24H:F13', 'ASG002_BC3C_24H:F14', 'ASG002_BC3C_24H:F16', 'ASG002_BC3C_24H:F17', 'ASG002_BC3C_24H:F18', 'ASG002_BC3C_24H:G02', 'ASG002_BC3C_24H:G03', 'ASG002_BC3C_24H:H16', 'ASG002_BC3C_24H:H17', 'ASG002_BC3C_24H:H18', 'ASG002_BC3C_24H:I05', 'ASG002_BC3C_24H:I06', 'ASG002_BC3C_24H:I07', 'ASG002_BC3C_24H:I08', 'ASG002_BC3C_24H:I09', 'ASG002_BC3C_24H:I13', 'ASG002_BC3C_24H:I14', 'ASG002_BC3C_24H:I15', 'ASG002_BC3C_24H:I20', 'ASG002_BC3C_24H:I21', 'ASG002_BC3C_24H:L01', 'ASG002_BC3C_24H:L02', 'ASG002_BC3C_24H:L03', 'ASG002_BC3C_24H:L07', 'ASG002_BC3C_24H:L08', 'ASG002_BC3C_24H:L09', 'ASG002_BC3C_24H:L16', 'ASG002_BC3C_24H:L17', 'ASG002_BC3C_24H:M22', 'ASG002_BC3C_24H:M23', 'ASG002_BC3C_24H:M24', 'ASG002_BC3C_24H:N13', 'ASG002_BC3C_24H:N14', 'ASG002_BC3C_24H:N15', 'ASG002_BC3C_24H:N20', 'ASG002_BC3C_24H:N21', 'ASG002_BC3C_24H:N23', 'ASG002_BC3C_24H:N24', 'ASG002_BC3C_24H:O10', 'ASG002_BC3C_24H:O11', 'ASG002_BC3C_24H:O12', 'ASG002_BC3C_24H:O22', 'ASG002_BC3C_24H:O23', 'ASG002_BC3C_24H:P07', 'ASG002_BC3C_24H:P08', 'ASG002_BC3C_24H:P09', 'ASG002_BC3C_24H:P16', 'ASG002_BC3C_24H:P18', 'ASG002_BC3C_24H:P20', 'ASG002_BC3C_24H:P21', 'MOAR008_BC3C_24H:L01', 'MOAR008_BC3C_24H:L02', 'MOAR008_BC3C_24H:L08', 'MOAR009_BC3C_24H:C10', 'MOAR009_BC3C_24H:C11', 'MOAR009_BC3C_24H:C12', 'MOAR010_BC3C_24H:A13', 'MOAR010_BC3C_24H:A14', 'MOAR010_BC3C_24H:A15', 'MOAR010_BC3C_24H:D01', 'MOAR010_BC3C_24H:D03', 'MOAR010_BC3C_24H:J22', 'MOAR010_BC3C_24H:J23', 'MOAR010_BC3C_24H:J24', 'MOAR010_BC3C_24H:K07', 'MOAR010_BC3C_24H:K08', 'MOAR010_BC3C_24H:K09', 'MOAR010_BC3C_24H:L19', 'MOAR010_BC3C_24H:L20', 'MOAR011_BC3C_24H:C01', 'MOAR011_BC3C_24H:C02', 'MOAR011_BC3C_24H:C03', 'MOAR011_BC3C_24H:C10', 'MOAR011_BC3C_24H:C11', 'MOAR011_BC3C_24H:F07', 'MOAR011_BC3C_24H:F08', 'MOAR011_BC3C_24H:F09', 'MOAR011_BC3C_24H:J10'], 'n_experiments': 104, 'genes': ['AARS', 'ABCB6', 'ABCC5', 'ABCF1', 'ABCF3', 'ABHD4', 'ABHD6', 'ABL1', 'ACAA1', 'ACAT2', 'ACBD3', 'ACD', 'ACLY', 'ACOT9', 'ADAM10', 'ADAT1', 'ADGRE5', 'ADGRG1', 'ADH5', 'ADI1', 'ADO', 'ADRB2', 'AGL', 'AKAP8', 'AKAP8L', 'AKR7A2', 'AKT1', 'ALAS1', 'ALDH7A1', 'ALDOA', 'ALDOC', 'AMDHD2', 'ANKRD10', 'ANO10', 'ANXA7', 'APBB2', 'APOE', 'APP', 'APPBP2', 'ARFIP2', 'ARHGAP1', 'ARHGEF12', 'ARHGEF2', 'ARID4B', 'ARID5B', 'ARL4C', 'ARNT2', 'ARPP19', 'ASAH1', 'ASCC3', 'ATF1', 'ATF5', 'ATF6', 'ATG3', 'ATMIN', 'ATP11B', 'ATP1B1', 'ATP2C1', 'ATP6V0B', 'ATP6V1D', 'AURKA', 'AURKB', 'AXIN1', 'B4GAT1', 'BACE2', 'BAD', 'BAG3', 'BAMBI', 'BAX', 'BCL2', 'BCL7B', 'BDH1', 'BECN1', 'BHLHE40', 'BID', 'BIRC2', 'BIRC5', 'BLCAP', 'BLMH', 'BLVRA', 'BMP4', 'BNIP3', 'BNIP3L', 'BPHL', 'BRCA1', 'BTK', 'BUB1B', 'BZW2', 'C2CD2', 'C2CD2L', 'C2CD5', 'C5', 'CAB39', 'CALM3', 'CALU', 'CAMSAP2', 'CANT1', 'CAPN1', 'CARMIL1', 'CASC3', 'CASK', 'CASP10', 'CASP2', 'CASP3', 'CASP7', 'CAST', 'CAT', 'CBLB', 'CBR1', 'CBR3', 'CCDC85B', 'CCDC86', 'CCDC92', 'CCL2', 'CCNA1', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND1', 'CCND3', 'CCNE2', 'CCNF', 'CCNH', 'CCP110', 'CD320', 'CD40', 'CD44', 'CD58', 'CDC20', 'CDC25A', 'CDC25B', 'CDC42', 'CDC45', 'CDCA4', 'CDH3', 'CDK1', 'CDK19', 'CDK2', 'CDK4', 'CDK5R1', 'CDK6', 'CDK7', 'CDKN1A', 'CDKN1B', 'CDKN2A', 'CEBPA', 'CEBPD', 'CEBPZ', 'CEMIP2', 'CENPE', 'CEP57', 'CERK', 'CETN3', 'CFLAR', 'CGRRF1', 'CHAC1', 'CHEK1', 'CHEK2', 'CHERP', 'CHIC2', 'CHMP4A', 'CHMP6', 'CHN1', 'CHP1', 'CIAO3', 'CIAPIN1', 'CIRBP', 'CISD1', 'CLIC4', 'CLPX', 'CLSTN1', 'CLTB', 'CLTC', 'CNDP2', 'CNOT4', 'CNPY3', 'COASY', 'COG2', 'COG4', 'COG7', 'COL1A1', 'COL4A1', 'COPB2', 'COPS7A', 'COQ8A', 'CORO1A', 'CPNE3', 'CPSF4', 'CREB1', 'CREG1', 'CRELD2', 'CRK', 'CRKL', 'CRTAP', 'CRYZ', 'CSK', 'CSNK1A1', 'CSNK1E', 'CSNK2A2', 'CSRP1', 'CTNNAL1', 'CTNND1', 'CTSD', 'CTSL', 'CTTN', 'CXCL2', 'CXCR4', 'CYB561', 'CYCS', 'CYTH1', 'DAG1', 'DAXX', 'DCK', 'DCTD', 'DCUN1D4', 'DDB2', 'DDIT4', 'DDR1', 'DDX10', 'DDX42', 'DECR1', 'DENND2D', 'DERA', 'DFFA', 'DFFB', 'DHDDS', 'DHRS7', 'DHX29', 'DIPK1A', 'DLD', 'DMAC2L', 'DMTF1', 'DNAJA3', 'DNAJB1', 'DNAJB2', 'DNAJB6', 'DNAJC15', 'DNM1', 'DNM1L', 'DNMT1', 'DNMT3A', 'DNTTIP2', 'DPH2', 'DRAP1', 'DSG2', 'DUSP11', 'DUSP14', 'DUSP22', 'DUSP3', 'DUSP4', 'DUSP6', 'DYNLT3', 'DYRK3', 'E2F2', 'EAPP', 'EBNA1BP2', 'EBP', 'ECD', 'ECH1', 'EDEM1', 'EDN1', 'EED', 'EFCAB14', 'EGF', 'EGFR', 'EGR1', 'EIF4EBP1', 'EIF4G1', 'EIF5', 'ELAC2', 'ELAVL1', 'ELOVL6', 'ELP1', 'EML3', 'ENOPH1', 'ENOSF1', 'EPB41L2', 'EPHA3', 'EPHB2', 'EPN2', 'EPRS', 'ERBB2', 'ERBB3', 'ERO1A', 'ETFB', 'ETS1', 'ETV1', 'EVL', 'EXOSC4', 'EXT1', 'EZH2', 'FAH', 'FAIM', 'FAM20B', 'FAM57A', 'FAS', 'FASTKD5', 'FAT1', 'FBXL12', 'FBXO11', 'FBXO21', 'FBXO7', 'FCHO1', 'FDFT1', 'FEZ2', 'FGFR2', 'FGFR4', 'FHL2', 'FIS1', 'FKBP14', 'FKBP4', 'FOS', 'FOSL1', 'FOXJ3', 'FOXO3', 'FOXO4', 'FPGS', 'FRS2', 'FSD1', 'FUT1', 'FYN', 'FZD1', 'FZD7', 'G3BP1', 'GAA', 'GABPB1', 'GADD45A', 'GADD45B', 'GALE', 'GAPDH', 'GATA2', 'GATA3', 'GDPD5', 'GFOD1', 'GFPT1', 'GHR', 'GLI2', 'GLOD4', 'GLRX', 'GMNN', 'GNA11', 'GNA15', 'GNAI1', 'GNAI2', 'GNAS', 'GNB5', 'GNPDA1', 'GOLT1B', 'GPATCH8', 'GPC1', 'GPER1', 'GRB10', 'GRB7', 'GRN', 'GRWD1', 'GSTM2', 'GSTZ1', 'GTF2A2', 'GTF2E2', 'GTPBP8', 'H2AFV', 'HACD3', 'HADH', 'HAT1', 'HDAC2', 'HDAC6', 'HDGFL3', 'HEATR1', 'HEBP1', 'HERC6', 'HERPUD1', 'HES1', 'HIF1A', 'HIST1H2BK', 'HIST2H2BE', 'HK1', 'HLA-DMA', 'HLA-DRA', 'HMG20B', 'HMGA2', 'HMGCR', 'HMGCS1', 'HMOX1', 'HOMER2', 'HOOK2', 'HOXA10', 'HOXA5', 'HPRT1', 'HS2ST1', 'HSD17B10', 'HSD17B11', 'HSPA1A', 'HSPA4', 'HSPA8', 'HSPB1', 'HSPD1', 'HTATSF1', 'HTRA1', 'HYOU1', 'IARS2', 'ICAM1', 'ICAM3', 'ICMT', 'ID2', 'IDE', 'IER3', 'IFNAR1', 'IFRD2', 'IGF1R', 'IGF2BP2', 'IGF2R', 'IGFBP3', 'IGHMBP2', 'IKBKB', 'IKBKE', 'IKZF1', 'IL13RA1', 'IL1B', 'IL4R', 'ILK', 'INPP1', 'INPP4B', 'INSIG1', 'INTS3', 'IPO13', 'IQGAP1', 'ISOC1', 'ITFG1', 'ITGAE', 'ITGB1BP1', 'ITGB5', 'JADE2', 'JMJD6', 'JPT2', 'JUN', 'KAT6A', 'KAT6B', 'KCNK1', 'KCTD5', 'KDELR2', 'KDM3A', 'KDM5A', 'KDM5B', 'KEAP1', 'KHDC4', 'KIAA0100', 'KIAA0355', 'KIAA0753', 'KIF14', 'KIF1BP', 'KIF20A', 'KIF2C', 'KIF5C', 'KIT', 'KLHDC2', 'KLHL21', 'KLHL9', 'KTN1', 'LAGE3', 'LAMA3', 'LAP3', 'LBR', 'LGALS8', 'LGMN', 'LIG1', 'LIPA', 'LOXL1', 'LPAR2', 'LPGAT1', 'LRP10', 'LRPAP1', 'LRRC41', 'LSM5', 'LSM6', 'LSR', 'LYN', 'LYPLA1', 'LYRM1', 'MACF1', 'MALT1', 'MAMLD1', 'MAN2B1', 'MAP2K5', 'MAP3K4', 'MAP4K4', 'MAP7', 'MAPK13', 'MAPK1IP1L', 'MAPK9', 'MAPKAPK2', 'MAPKAPK3', 'MAPKAPK5', 'MAST2', 'MAT2A', 'MBNL1', 'MBNL2', 'MBOAT7', 'MBTPS1', 'MCM3', 'MCOLN1', 'MCUR1', 'ME2', 'MEF2C', 'MELK', 'MEST', 'METRN', 'MFSD10', 'MICALL1', 'MIF', 'MINDY1', 'MKNK1', 'MLEC', 'MLLT11', 'MMP1', 'MMP2', 'MNAT1', 'MOK', 'MPC2', 'MPZL1', 'MRPL12', 'MRPL19', 'MRPS16', 'MRPS2', 'MSH6', 'MSRA', 'MTA1', 'MTERF3', 'MTF2', 'MTFR1', 'MTHFD2', 'MUC1', 'MVP', 'MYBL2', 'MYC', 'MYCBP', 'MYCBP2', 'MYL9', 'MYLK', 'MYO10', 'NCAPD2', 'NCK1', 'NCK2', 'NCOA3', 'NENF', 'NET1', 'NFATC3', 'NFATC4', 'NFE2L2', 'NFIL3', 'NFKB2', 'NFKBIA', 'NFKBIB', 'NFKBIE', 'NGRN', 'NIPSNAP1', 'NISCH', 'NIT1', 'NMT1', 'NNT', 'NOL3', 'NOLC1', 'NOS3', 'NOSIP', 'NOTCH1', 'NPC1', 'NPDC1', 'NPEPL1', 'NPRL2', 'NR1H2', 'NR2F6', 'NR3C1', 'NRAS', 'NRIP1', 'NSDHL', 'NT5DC2', 'NUCB2', 'NUDCD3', 'NUDT9', 'NUP133', 'NUP62', 'NUP85', 'NUP88', 'NUP93', 'NUSAP1', 'NVL', 'ORC1', 'OXA1L', 'OXCT1', 'OXSR1', 'P4HA2', 'P4HTM', 'PACSIN3', 'PAF1', 'PAFAH1B1', 'PAFAH1B3', 'PAICS', 'PAK1', 'PAK4', 'PAK6', 'PAN2', 'PARP1', 'PARP2', 'PAX8', 'PCBD1', 'PCCB', 'PCK2', 'PCM1', 'PCMT1', 'PCNA', 'PDGFA', 'PDHX', 'PDIA5', 'PDLIM1', 'PDS5A', 'PECR', 'PEX11A', 'PFKL', 'PGAM1', 'PGM1', 'PGRMC1', 'PHGDH', 'PHKA1', 'PHKB', 'PHKG2', 'PIGB', 'PIH1D1', 'PIK3C2B', 'PIK3C3', 'PIK3CA', 'PIK3R3', 'PIK3R4', 'PIN1', 'PIP4K2B', 'PKIG', 'PLA2G15', 'PLA2G4A', 'PLCB3', 'PLEKHJ1', 'PLEKHM1', 'PLK1', 'PLOD3', 'PLP2', 'PLS1', 'PLSCR1', 'PLSCR3', 'PMAIP1', 'PMM2', 'PNKP', 'PNP', 'POLB', 'POLD4', 'POLE2', 'POLG2', 'POLR1C', 'POLR2I', 'POLR2K', 'POP4', 'PPARD', 'PPARG', 'PPIC', 'PPIE', 'PPOX', 'PPP1R13B', 'PPP2R3C', 'PPP2R5A', 'PPP2R5E', 'PRAF2', 'PRCP', 'PRKACA', 'PRKAG2', 'PRKCD', 'PRKCH', 'PRKCQ', 'PRKX', 'PROS1', 'PRPF4', 'PRR15L', 'PRR7', 'PRSS23', 'PRUNE1', 'PSIP1', 'PSMB10', 'PSMB8', 'PSMD10', 'PSMD2', 'PSMD4', 'PSMD9', 'PSME1', 'PSME2', 'PSMF1', 'PSMG1', 'PSRC1', 'PTGS2', 'PTK2', 'PTK2B', 'PTPN1', 'PTPN12', 'PTPN6', 'PTPRC', 'PTPRF', 'PTPRK', 'PUF60', 'PWP1', 'PXMP2', 'PXN', 'PYCR1', 'PYGL', 'RAB11FIP2', 'RAB21', 'RAB27A', 'RAB31', 'RAB4A', 'RAC2', 'RAD51C', 'RAD9A', 'RAE1', 'RAI14', 'RALA', 'RALB', 'RALGDS', 'RAP1GAP', 'RASA1', 'RB1', 'RBKS', 'RBM15B', 'RBM34', 'RBM6', 'REEP5', 'RELB', 'RFC2', 'RFC5', 'RFNG', 'RFX5', 'RGS2', 'RHEB', 'RHOA', 'RNF167', 'RNH1', 'RNMT', 'RNPS1', 'RPA1', 'RPA2', 'RPA3', 'RPIA', 'RPL39L', 'RPN1', 'RPP38', 'RPS5', 'RPS6', 'RPS6KA1', 'RRAGA', 'RRP12', 'RRP1B', 'RRP8', 'RRS1', 'RSU1', 'RTN2', 'RUVBL1', 'RXYLT1', 'S100A13', 'S100A4', 'SACM1L', 'SATB1', 'SCAND1', 'SCARB1', 'SCCPDH', 'SCP2', 'SCRN1', 'SCYL3', 'SDHB', 'SENP6', 'SERPINE1', 'SESN1', 'SFN', 'SGCB', 'SH3BP5', 'SHB', 'SHC1', 'SIRT3', 'SKIV2L', 'SKP1', 'SLC11A2', 'SLC1A4', 'SLC25A13', 'SLC25A14', 'SLC25A4', 'SLC25A46', 'SLC27A3', 'SLC2A6', 'SLC35A1', 'SLC35A3', 'SLC35B1', 'SLC35F2', 'SLC37A4', 'SLC5A6', 'SMAD3', 'SMARCA4', 'SMARCC1', 'SMARCD2', 'SMC1A', 'SMC3', 'SMC4', 'SMNDC1', 'SNAP25', 'SNCA', 'SNX11', 'SNX13', 'SNX6', 'SNX7', 'SOCS2', 'SORBS3', 'SOX2', 'SOX4', 'SPAG4', 'SPAG7', 'SPDEF', 'SPEN', 'SPP1', 'SPR', 'SPRED2', 'SPTAN1', 'SPTLC2', 'SQOR', 'SQSTM1', 'SRC', 'SSBP2', 'ST3GAL5', 'ST6GALNAC2', 'ST7', 'STAMBP', 'STAP2', 'STAT1', 'STAT3', 'STAT5B', 'STIMATE', 'STK10', 'STK25', 'STMN1', 'STUB1', 'STX1A', 'STX4', 'STXBP1', 'STXBP2', 'SUPV3L1', 'SUV39H1', 'SUZ12', 'SYK', 'SYNE2', 'SYNGR3', 'SYPL1', 'TARBP1', 'TATDN2', 'TBC1D31', 'TBC1D9B', 'TBP', 'TBPL1', 'TBX2', 'TBXA2R', 'TCEA2', 'TCEAL4', 'TCERG1', 'TCFL5', 'TCTA', 'TCTN1', 'TENT4A', 'TERF2IP', 'TERT', 'TES', 'TESK1', 'TEX10', 'TFAP2A', 'TFDP1', 'TGFB3', 'TGFBR2', 'THAP11', 'TIAM1', 'TICAM1', 'TIMELESS', 'TIMM17B', 'TIMM22', 'TIMM9', 'TIMP2', 'TIPARP', 'TJP1', 'TLE1', 'TLK2', 'TLR4', 'TM9SF2', 'TM9SF3', 'TMCO1', 'TMED10', 'TMEM109', 'TMEM50A', 'TMEM97', 'TNFRSF21', 'TNIP1', 'TOMM34', 'TOMM70', 'TOP2A', 'TOPBP1', 'TOR1A', 'TP53', 'TP53BP1', 'TP53BP2', 'TPD52L2', 'TPM1', 'TRAK2', 'TRAM2', 'TRAP1', 'TRAPPC3', 'TRAPPC6A', 'TRIB1', 'TRIB3', 'TRIM13', 'TRIM2', 'TSC22D3', 'TSEN2', 'TSKU', 'TSPAN3', 'TSPAN4', 'TSPAN6', 'TSTA3', 'TUBB6', 'TWF2', 'TXLNA', 'TXNDC9', 'TXNL4B', 'TXNRD1', 'UBE2A', 'UBE2C', 'UBE2J1', 'UBE2L6', 'UBE3B', 'UBE3C', 'UBQLN2', 'UBR7', 'UFM1', 'UGDH', 'USP1', 'USP14', 'USP22', 'USP6NL', 'USP7', 'UTP14A', 'VAPB', 'VAT1', 'VAV3', 'VDAC1', 'VGLL4', 'VPS28', 'VPS72', 'WASF3', 'WASHC4', 'WASHC5', 'WDR61', 'WDR7', 'WDTC1', 'WFS1', 'WIPF2', 'WRB', 'XBP1', 'XPNPEP1', 'XPO7', 'YKT6', 'YME1L1', 'YTHDF1', 'ZDHHC6', 'ZFP36', 'ZMIZ1', 'ZMYM2', 'ZNF131', 'ZNF274', 'ZNF318', 'ZNF395', 'ZNF451', 'ZNF586', 'ZNF589', 'ZW10'], 'n_genes': 978}

In [43]:
# save doses and perturbation matrix
inhib_conc_df.to_csv(os.path.join(out_dir, "inhib_conc_annotated.csv"))
ic50_df.to_csv(os.path.join(out_dir, "ic50_annotated.csv"))
# gamma_df.to_csv(os.path.join(out_dir, "gamma_annotated.csv"))
pert_df.to_csv(os.path.join(out_dir, "pert_annotated.csv"))

In [44]:
# save log fold change L1000 data
Data_norm_df.to_csv(os.path.join(out_dir, "L1000_Data_norm_data.csv"))

In [45]:
# save R_global for DPDs
R_global_DPD_df.to_csv(os.path.join(out_dir, "R_global_DPDonly_annotated.csv"))